### ISSUE TITLE
System cannot find -lmqttv3a & -lmqttpp

### ISSUE THREAD

**Issue by Jason-Gew** [eclipse/paho.mqtt.cpp#1]
Hi,

I encountered a problem when compiling the sample c++ code. It seems lack of libraries files. Is it because there's no "make install" option to add those libraries into system path?

I also tried paho.mqtt.c, that compile has no issue happen.

jason2015@ubuntu:~/mqtt/paho.mqtt.cpp/src/samples$ make sync_publish
g++ -I.. -I/home/fmp/static/opensrc/mqtt/paho/org.eclipse.paho.mqtt.c/src -D_NDEBUG -Wall -std=c++0x -O2 -o sync_publish sync_publish.cpp -L../lib -L/home/fmp/static/opensrc/mqtt/paho/org.eclipse.paho.mqtt.c/src/linux_ia64 -lmqttpp -lmqttv3a
/usr/bin/ld: cannot find -lmqttv3a
collect2: error: ld returned 1 exit status
make: **\* [sync_publish] Error 1

Best Regards!

**Comment by ristomet** [comment]
Same here.

**Comment by guilhermeferreira** [comment]
Hi Jason,

I faced the same issues. The first problem is the lack of "make install" to copy the paho-mqtt-cpp library to one of the standard paths. The second one is the handling of the dependencies. The paho-mqtt-c (C library).

Then, I started to work on two building system versions for this library, one is Autotools and the other is CMake. Those building systems address both of those problems.

The Autotools checks the existence of the libpaho-mqtta.so (the asynchronous version of the Paho C). Besides, it's possible to conditionally compile a static library version (passing --enable-static to configure), the documentation (--enable-doc) and the sample applications (--enable-samples).

$ git clone https://github.com/guilhermeferreira/paho.mqtt.cpp.git
$ git checkout -t origin/build-autotools
$ ./bootstrap
$ ./configure [options]
$ make

The CMake building system for Paho C++ was modeled after the one Rainer Poisel made to Paho C. To configure, use the "ccmake .." command inside the "build" directory. You have similar options as those for Autotools.

$ git clone https://github.com/guilhermeferreira/paho.mqtt.cpp.git
$ cd paho.mqtt.cpp
$ git checkout -t origin/build-cmake
$ mkdir build
$ cd build
$ cmake ..
$ ccmake .. 

Best regards,

**Comment by Jason-Gew** [comment]
Hi,

Thanks for the suggestions above.
We checked the Makefile inside the /src/samples and utilized the c library paho-mqtt3a to compile it successfully. Not sure it's the very correct way, but at least it's working fine now.

1. Copy 3 .so Libraries files in lib folder to /usr/local/lib.

2. Use Paho MQTT C library paho-mqtt3a instead of the previous cpp library which can be re-edit in the Makefile.

3. Try make the samples, it will work.


Best Regards!

**Comment by prateekbansal** [comment]
For me, this worked from inside my samples directory:
LDLIBS += -L../../lib -L$(PAHO_C_LIB) -lmqttpp -lpaho-mqtt3as

I am using the ssl enabled version of paho client C and have the libs installed. For me it goes under /usr/local/lib when I did `sudo make install` when I built paho client C.

**Comment by griera** [comment]
I used the same approach that @prateekbansal explain above, and it works. As a prerequisite, Paho MQTT Client C must be compiled and installed properly.

**Comment by guilhermeferreira** [comment]
I made a patch to add the "install" target (#5)

**Comment by janoshh** [comment]
I'm having the same problem. How do i add the library in the make file of my cpp project?

**Comment by guilhermeferreira** [comment]
@janoshh I guess your command is lacking the library path (-L) for the Paho MQTT C++ (-lmqttpp). You check the @prateekbansal comment above. But adding the path to libmqttpp.

**Comment by janoshh** [comment]
@guilhermeferreira Allright it seems the library is found, but i'm still getting reference errors like:

/tmp/ccT57dw6.o: In function `connlost(void*, char*)':
main.cpp:(.text+0x284): undefined reference to `MQTTAsync_connect'
/tmp/ccT57dw6.o: In function `onSend(void*, MQTTAsync_successData*)':
main.cpp:(.text+0x308): undefined reference to `MQTTAsync_disconnect

etc.. 

Any idea why tis error occurs?

**Comment by guilhermeferreira** [comment]
@janoshh it seems you are missing the -lpaho-mqtt3as. But, for accurate diagnostics, could you paste your Makefile?

**Comment by janoshh** [comment]
Yes that did the job! I was using the paho-mqtt3c and didn't notice that there was the paho-mqtt3a etc.. thx, saved my day!

**Comment by fpagliughi** [comment]
The raw Makefiles now have a "make install" and the CMake/autotools deal with this properly.
