### ISSUE TITLE
Definition missing for set_user_name and set_password functions in connect_options.h

### ISSUE THREAD

**Issue by phariprasadreddy** [eclipse/paho.mqtt.cpp#10]
We are trying to connect to the MQTT broker with username and password using this Paho MQTT CPP library. But found definitions for the following functions are missing,

/**
 * Sets the password to use for the connection.
 */
void set_password(const std::string& password);

/**
 * Sets the user name to use for the connection.
 * @param userName 
 */
void set_user_name(const std::string& userName);

Could you please suggest a solution?

**Comment by guilhermeferreira** [comment]
Indeed there are many definitions missing. I guess the author is working on such issues. For now, you can implement the set_password() and set_user_name(), acessing the underlying MQTTAsync_connectOptions:

`void set_password(const std::string& password) {
    char *pswd = new char[password.size() + 1];
    std::copy(password.begin(), password.end(), pswd);
    pswd[password.size()] = '\0';
    opts_.password = pswd;
}
`

`void set_user_name(const std::string& userName) {
    char *user_name = new char[userName.size() + 1];
    std::copy(userName.begin(), userName.end(), user_name);
    user_name[userName.size()] = '\0';
    opts_.username = user_name;
}`

And don't forget to delete those strings before assing new ones and at the destructor.

**Comment by guilhermeferreira** [comment]
Hi, you can check my branch #13.

**Comment by phariprasadreddy** [comment]
@guilhermeferreira Thanks for your efforts.

**Comment by fpagliughi** [comment]
Merged in 43cc619d0c098ebc9b7eae05cb1d89eb8b6d095b
