### ISSUE TITLE
Segmentation fault with SSL

### ISSUE THREAD

**Issue by berat66** [eclipse/paho.mqtt.cpp#104]
If I am trying to create an instance of a mqtt::client (paho.mqtt.cpp built with SSL option on), there is a heap error.
This error occurs, when I create an instance in a class method initialize() of my class MQTT, which shouldn't make any difference. If I create the instance in the main function, I cannot reproduce the error.

My program flow is as following:

1. create last will message instance and configure the message
2. create connect_options instance and configure the options
3. Create client instance with hostname and clientid.

All the instances are created on the heap. 
After creating the connect_options, it isn't possible to create the client on the heap.

After building mqttpp withOUT SSL, the error doesn't occur.

**Output of the console:**
`
sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.

*** Error in `./IoT_Gateway': malloc(): memory corruption: 0x0000000001d34f30 ***

**Valgrind output:**
`
==17065== Memcheck, a memory error detector
==17065== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==17065== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==17065== Command: ./IoT_Gateway
==17065== 
==17065== Invalid write of size 8
==17065==    at 0x4E518A9: mqtt::ssl_options::ssl_options() (ssl_options.cpp:26)
==17065==    by 0x4E5099C: mqtt::connect_options::connect_options() (connect_options.cpp:25)
==17065==    by 0x404CF8: MQTT::initClient() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x4070B5: MQTT::initialize() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x402E91: main (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==  Address 0x9e16018 is 0 bytes after a block of size 200 alloc'd
==17065==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17065==    by 0x404CED: MQTT::initClient() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x4070B5: MQTT::initialize() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x402E91: main (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065== 
==17065== Invalid write of size 8
==17065==    at 0x4E518B1: mqtt::ssl_options::ssl_options() (ssl_options.cpp:26)
==17065==    by 0x4E5099C: mqtt::connect_options::connect_options() (connect_options.cpp:25)
==17065==    by 0x404CF8: MQTT::initClient() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x4070B5: MQTT::initialize() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x402E91: main (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==  Address 0x9e16020 is 8 bytes after a block of size 200 alloc'd
==17065==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17065==    by 0x404CED: MQTT::initClient() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x4070B5: MQTT::initialize() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x402E91: main (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065== 
==17065== Invalid write of size 4
==17065==    at 0x4E518B9: mqtt::ssl_options::ssl_options() (ssl_options.cpp:26)
==17065==    by 0x4E5099C: mqtt::connect_options::connect_options() (connect_options.cpp:25)
==17065==    by 0x404CF8: MQTT::initClient() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x4070B5: MQTT::initialize() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x402E91: main (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==  Address 0x9e16028 is 16 bytes after a block of size 200 alloc'd
==17065==    at 0x4C2B0E0: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==17065==    by 0x404CED: MQTT::initClient() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x4070B5: MQTT::initialize() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x402E91: main (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065== 
==17065== Invalid write of size 8
==17065==    at 0x4E518C0: _Alloc_hider (basic_string.h:275)
==17065==    by 0x4E518C0: basic_string (basic_string.h:439)
==17065==    by 0x4E518C0: mqtt::ssl_options::ssl_options() (ssl_options.cpp:26)
==17065==    by 0x4E5099C: mqtt::connect_options::connect_options() (connect_options.cpp:25)
==17065==    by 0x404CF8: MQTT::initClient() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x4070B5: MQTT::initialize() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x402E91: main (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==  Address 0x9e16030 is 16 bytes after a block of size 208 in arena "client"
==17065== 
==17065== Invalid write of size 8
==17065==    at 0x4E518C4: _Alloc_hider (basic_string.h:275)
==17065==    by 0x4E518C4: basic_string (basic_string.h:439)
==17065==    by 0x4E518C4: mqtt::ssl_options::ssl_options() (ssl_options.cpp:26)
==17065==    by 0x4E5099C: mqtt::connect_options::connect_options() (connect_options.cpp:25)
==17065==    by 0x404CF8: MQTT::initClient() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x4070B5: MQTT::initialize() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x402E91: main (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==  Address 0x9e16038 is 24 bytes after a block of size 208 in arena "client"
==17065== 

valgrind: m_mallocfree.c:304 (get_bszB_as_is): Assertion 'bszB_lo == bszB_hi' failed.
valgrind: Heap block lo/hi size mismatch: lo = 272, hi = 94864344.
This is probably caused by your program erroneously writing past the
end of a heap block and corrupting heap metadata.  If you fix any
invalid writes reported by Memcheck, this assertion failure will
probably go away.  Please try that before reporting this as a bug.

host stacktrace:
==17065==    at 0x3805DB16: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==17065==    by 0x3805DC24: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==17065==    by 0x3805DDA6: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==17065==    by 0x3806AB83: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==17065==    by 0x380571EB: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==17065==    by 0x38055CCB: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==17065==    by 0x38059B3B: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==17065==    by 0x380552C7: ??? (in /usr/lib/valgrind/memcheck-amd64-linux)
==17065==    by 0x802DD871B: ???
==17065==    by 0x802B99EEF: ???

sched status:
  running_tid=1

Thread 1: status = VgTs_Runnable
==17065==    at 0x4E518C8: _Alloc_hider (basic_string.h:275)
==17065==    by 0x4E518C8: basic_string (basic_string.h:439)
==17065==    by 0x4E518C8: mqtt::ssl_options::ssl_options() (ssl_options.cpp:26)
==17065==    by 0x4E5099C: mqtt::connect_options::connect_options() (connect_options.cpp:25)
==17065==    by 0x404CF8: MQTT::initClient() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x4070B5: MQTT::initialize() (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)
==17065==    by 0x402E91: main (in /home/renesas/ws_berat/SVN/IoT_Gateway_Embedded_Linux/Software/sw-c/IoT_Gateway/build-IoT_Gateway-Desktop_Qt_5_7_0_GCC_64bit-Release/IoT_Gateway)

Note: see also the FAQ in the source distribution.
It contains workarounds to several common problems.
In particular, if Valgrind aborted or crashed after
identifying problems in your program, there's a good chance
that fixing those problems will prevent Valgrind aborting or
crashing, especially if it happened in m_mallocfree.c.

If that doesn't help, please report this bug to: www.valgrind.org

In the bug report, send all the above text, the valgrind
version, and what OS and version you are using.  Thanks.

`

**Comment by fpagliughi** [comment]
Please verify if this is still an issue with the latest update of the code.
