### ISSUE TITLE
Old Visual Studio support

### ISSUE THREAD

**Issue by dontsovcmc** [eclipse/paho.mqtt.cpp#106]
I got this errors:
error C3646: 'noexcept' : unknown override specifier	
error C2797: 'mqtt::topic::name_': list initialization inside member initializer list or non-static data member initializer is not implemented

and need modified mqtt\types.h
#ifdef WIN32
#include <stdint.h>
#endif

Maybe it is more better to have universe code.

**Comment by fpagliughi** [comment]
What do you mean by "old" Visual Studio. This library requires full C++11 support, which I would guess means VC2015. I don't think it would work with anything earlier than that.

**Comment by dontsovcmc** [comment]
Ah.. I work with VC2013  :D... 

I have build successfully with with changes:

#ifdef _MSC_VER <= 1800
#define NOEXCEPT
#else
#define NOEXCEPT noexcept
#endif

and change constructor of topic:
topic(const std::string& name, iasync_client& cli) : name_{name}, cli_{&cli} {}
to:
topic(const std::string& name, iasync_client& cli) : name_(name), cli_(&cli) {}

**Comment by dontsovcmc** [comment]
1. Build sync_publish failed  ..\Debug\paho-mqttpp3.lib not found :(.
2. I change build type of paho-mqttpp3 to static library and got lib file :).
3. change ADDRESS to tcp://iot.eclipse.org:1883
4. sync_publish build ok
4. run sync_publish failed Unhandeled exception at "idelivery_token_ptr tok = std::make_shared<delivery_token>(*this, topic, msg);"
something goes wrong...

**Comment by fpagliughi** [comment]
I'm guessing that you haven't tried this with the latest code in the _develop_ branch. I had to do a bit of work to even get VC2015 to compile this code. If the compiler doesn't support universal initialization, I think we'd be in a lot of trouble. I think VS2015 is probably the bare minimum for code that want to make non-trivial use of C++11.

**Comment by smkhadishi** [comment]
I got this errors:
Error	1	error C2610: 'mqtt::buffer_ref<T>::buffer_ref(mqtt::buffer_ref<T> &&)' : is not a special member function which can be defaulted	d:\newgame\newgame\classes\lib\mqtt\src\mqtt\buffer_ref.h	96	1	OBJS
