### ISSUE TITLE
[Suggestion] why not use an enum for QoS?

### ISSUE THREAD

**Issue by guilhermeferreira** [eclipse/paho.mqtt.cpp#11]
I understand that the Paho C does not use enumerations for QoS. Though it would help to document the code, the C language allows interchange of integer and enumeration. But the C++ considers enumerations as types and has more strict rules. I guess it should increase type safety (and prevent programming mistakes) if all QoS become enumeration type, or even an enum class.

**Comment by guilhermeferreira** [comment]
@fpagliughi please check the pull request #52 for a proposed enhancement.

**Comment by fpagliughi** [comment]
See #52
