### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by guilhermeferreira** [eclipse/paho.mqtt.cpp#111]
Up to now, neither [Paho MQTT C](https://www.eclipse.org/paho/clients/c) nor [Paho MQTT C++](https://www.eclipse.org/paho/clients/cpp) libraries have support for WebSockets ([RFC 6455](https://www.ietf.org/rfc/rfc6455.txt)). Also, there is [an issue open for Paho MQTT C requesting WebSocket support](https://github.com/eclipse/paho.mqtt.c/issues/166).

There are some explanations regarding the need of MQTT over WebSockets [here](http://www.hivemq.com/blog/mqtt-essentials-special-mqtt-over-websockets) and [here](http://www.hivemq.com/blog/mqtt-over-websockets-with-hivemq). 

These are the implementation options I see so far:
- Wait for Paho MQTT C add the WebSocket support and create a wrapper for it. It might take time until the Paho MQTT C implementation stabilizes.
- Implement our own WebSocket. This might incur a lot of work for us.
- Use a [3rd party library](https://en.wikipedia.org/wiki/Comparison_of_WebSocket_implementations), like [libwebsockets](https://libwebsockets.org/), [websocket++](https://github.com/zaphoyd/websocketpp), or [Beast C++ Library](http://vinniefalco.github.io/beast/index.html). We will add another dependency to Paho MQTT C++, creating more building problems.

**Comment by fpagliughi** [comment]
At this time, the C++ library is just a wrapper around the Paho C lib which handles all the network communications, connect/read/write, etc. As such, would it even be possible to implement WebSockets in the C++ library and bypass the C networking? Wouldn't we need the C library to manage this?

**Comment by guilhermeferreira** [comment]
>  would it even be possible to implement WebSockets in the C++ library and bypass the C networking? Wouldn't we need the C library to manage this?

@fpagliughi probably we will need some changes in the Paho MQTT C library.

**Comment by fpagliughi** [comment]
If this Paho C enhancement goes through, we can use and test from the C++ library.
https://github.com/eclipse/paho.mqtt.c/pull/415

**Comment by tbeu** [comment]
> If this Paho C enhancement goes through, we can use and test from the C++ library.

It did.

**Comment by windbender** [comment]
I have successfully used the paho c support for web socket.    It works!

**Comment by fpagliughi** [comment]
Yes, the C library with WebSockets and MQTT v5 is just being released. This C++ library is soon to follow!

**Comment by fpagliughi** [comment]
Wow. I didn't need to do anything!!!

Just build the latest C++ v1.0.1 (or master branch) against Paho C v1.3.0, and boom!
WebSocket support.

**Comment by fpagliughi** [comment]
See https://github.com/eclipse/paho.mqtt.c/pull/415 for some hints on how to use it. Documentation will be added to the C++ library in the near future.
