### ISSUE TITLE
ssl example error -13

### ISSUE THREAD

**Issue by priema** [eclipse/paho.mqtt.cpp#118]
I tested your ssl_publish.cpp example but I always get:

```
pi@raspberrypi:~/paho.mqtt.cpp/src/samples $ ./ssl_publish 
Initializing for server 'ssl://localhost:18885'...
  ...OK

Connecting...
Error: MQTT exception -13
```

can you help me out?

**Comment by fpagliughi** [comment]
For the SSL example, we use the certificates from the Paho C library test cases. But the broker must also be configured to use those certificates. We assume mosquitto as the broker. The basic instructions are in a comment at the top of the ssl_publish.cpp source code. But now I realize that the starting directory for mosquitto is incorrect.

First make sure no other instance of mosquitto is running:
```
$ sudo service mosquitto stop
```

Download/clone the Paho C library, then enter the top-level directory for it and run mosquitto from there with the test configuration file:
```
$ cd paho.mqtt.c
$ mosquitto -c test/tls-testing/mosquitto.conf
1496692100: mosquitto version 1.4.11 (build date Mon, 20 Feb 2017 22:47:27 +0000) starting
1496692100: Config loaded from test/tls-testing/mosquitto.conf.
...
```

Go into the C++ samples directory, and copy the file "test-root-ca.crt" from the C test directory (paho.mqtt.c/test/tls-testing) for the trust store for this program. Then run the sample.
```
$ cd paho.mqtt.cpp/src/samples
$ cp ../../../paho.mqtt.c/test/tls-testing/test-root-ca.crt .
$ ./ssl_publish 
Initializing for server 'ssl://localhost:18885'...
  ...OK

Connecting...
Waiting for the connection...
  ...OK

Sending message...
	Delivery complete for token: 1
  ...OK

Sending next message...
	Delivery complete for token: 2
  ...OK

Disconnecting...
  ...OK

$
```

**Comment by priema** [comment]
I did it exactly that way but im getting the error code -13:

```
[100%] Linking CXX executable ssl_publish
[100%] Built target ssl_publish
pi@raspberrypi:~/temp/paho.mqtt.cpp $ cd src/samples/
pi@raspberrypi:~/temp/paho.mqtt.cpp/src/samples $ ./ssl_publish
Initializing for server 'ssl://localhost:18885'...
  ...OK

Connecting...
MQTT error [-13]
```

**Comment by woohyeok** [comment]
-13 Error Code indicates that Your Library does not support SSL.
Replace it with an MQTT library that supports SSL.

**Comment by fpagliughi** [comment]
Oh, wow, how did I miss that!?! I just added that error to the C library a few weeks ago.

Thanks.

Yes, -13 means that the app is being linked against a version of the Paho C library which was not compiled to support SSL. It appears that you're building with CMake? I will check that the build system is  linking to the correct library. (I primarily test with GNU Make, so a few things may have slipped by in the CMake and Autotools builds).

**Comment by priema** [comment]
yes I build it with CMake..
what can I do to build it correct?

**Comment by zhaoboc** [comment]
```
    set(PAHO_MQTT_C paho-mqtt3a)
    target_link_libraries(ssl_publish
        ${PAHO_MQTT_C}
        ${PAHO_MQTT_CPP})
```
it's possible that ssl_publish is linked to paho-mqtt3a, which is paho async library without ssl.

however in Makefile ssl_publish is linked to paho-mqtt3as correctly:
```
ssl_publish: ssl_publish.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ $< $(LDLIBS_SSL)
```

**Comment by fpagliughi** [comment]
It appears that this was already fixed in the `develop` branch a few weeks ago. Try to pull the latest code, checkout that branch, and try again. It should work.
