### ISSUE TITLE
undefined reference async_client

### ISSUE THREAD

**Issue by priema** [eclipse/paho.mqtt.cpp#120]
I put my project on a clean jessie installation and I get following error:

undefined reference to `mqtt::async_client::async_client(std::string const&, std::string const&)'

I call the async client like this:
`this->client = new mqtt::async_client("tcp://192.168.1.36:1883", "AsyncSubcriber");`

what I'm doing wrong or what I forgot to install?
I installed:
```
git clone https://github.com/eclipse/paho.mqtt.c.git
cd paho.mqtt.c
make
sudo make install
and
git clone https://github.com/eclipse/paho.mqtt.cpp
mkdir build
make
sudo make install
```

my CMakeLists contains this:
```

set(PAHO_MQTT_CPP paho-mqttpp3)
set(PAHO_MQTT_C paho-mqtt3a)


## Paho MQTT C include directory
get_filename_component(PAHO_MQTT_C_DEV_INC_DIR ${PAHO_MQTT_C_PATH}/src ABSOLUTE)
get_filename_component(PAHO_MQTT_C_STD_INC_DIR ${PAHO_MQTT_C_PATH}/include ABSOLUTE)
set(PAHO_MQTT_C_INC_DIR
        ${PAHO_MQTT_C_DEV_INC_DIR}
        ${PAHO_MQTT_C_STD_INC_DIR})

## Paho MQTT C++ include directory
get_filename_component(PAHO_MQTT_CPP_INC_DIR ${CMAKE_SOURCE_DIR}/src ABSOLUTE)

## include directories
include_directories(${CMAKE_CURRENT_SOURCE_DIR})
include_directories(${PAHO_MQTT_C_INC_DIR})
include_directories(${PAHO_MQTT_CPP_INC_DIR})

## Paho MQTT C library directory
##get_filename_component(PAHO_MQTT_C_LIB_DIR ${PAHO_MQTT_C_LIB} DIRECTORY)

## Paho MQTT C++ library directory
get_filename_component(PAHO_MQTT_CPP_LIB_DIR ${CMAKE_BINARY_DIR}/src ABSOLUTE)

## link directories
link_directories(${PAHO_MQTT_C_LIB_DIR})
link_directories(${PAHO_MQTT_CPP_LIB_DIR})
```

sorry for bothering you
I really don't know what I did wrong...

**Comment by priema** [comment]
oh got it.. I unintentional merged two different paho_mqtt libraries

**Comment by kandizzy** [comment]
@priema Hi, I know this was a while ago, but I am having the same trouble. Would you let me know what you meant by unintentionally merging two different paho_mqtt libraries? Thanks!

**Comment by fpagliughi** [comment]
The common cause of this error is forgetting to link both the Paho C and C++ libraries into your application. It needs both libpaho-mqttpp3.so (C++) and libpaho-mqtt3as.so (C).
If you're not using SSL/TLS, you can use libpaho-mqtt3a.so instead of the "as" version.

**Comment by kandizzy** [comment]
^ that was it.

**Comment by darthShana** [comment]
HI All..
Im facing the same issue.. Any chance you could post a simple working CMakeLists which can build a executable that uses mqtt::async_client
