### ISSUE TITLE
Too many tries with invalid URI in MQTTAsync_connect leads OS connection stuck

### ISSUE THREAD

**Issue by hackerick4** [eclipse/paho.mqtt.cpp#122]
```
int MQ::connectToMQ() {
        int rc;
	MQTTAsync_connectOptions conn_opts = MQTTAsync_connectOptions_initializer;
	MQTTAsync_disconnectOptions disc_opts = MQTTAsync_disconnectOptions_initializer;
	rc = MQTTAsync_create(&client, "" , CLIENTID, MQTTCLIENT_PERSISTENCE_NONE, NULL);
	MQTTAsync_setCallbacks(client, NULL, connlost, msgarrvd, NULL);
	conn_opts.keepAliveInterval = 20;
	conn_opts.onSuccess = onConnect;
	conn_opts.onFailure = onConnectFailure;
	conn_opts.cleansession = 1;
	conn_opts.context = client;
        if ((rc = MQTTAsync_connect(client, &conn_opts)) != MQTTASYNC_SUCCESS) {
	   //	cout << "Failed to start connect, return code : " << rc << endl;
	}
	return rc;
}

```
issue 1 : Why "MQTTAsync_create" function returned success even I try to input empty connection URL ?

issue 2 : Why "MQTTAsync_connect" also returned success here?

issue 3 : After I tried MQTTAsync_connect with empty URI many times(over 60,000) would lead OS connection stuck. Every external connections would fail. For example, I cannot ssh to MSSQL and even cannot surf internet until I close MQ Client program.
I want to ask that MQTTAsync_connect free the socket when URI is invalid. Why did I get this result? and how can I avoid them ?

BTW, My OS is Windows 7 32bit.

**Comment by fpagliughi** [comment]
This is an issue for Paho C.
https://github.com/eclipse/paho.mqtt.c/issues/319
