### ISSUE TITLE
CMake build fails to find paho.mqtt.c development libs

### ISSUE THREAD

**Issue by rstoica** [eclipse/paho.mqtt.cpp#124]
The error can be easily replicated
```
git clone https://github.com/eclipse/paho.mqtt.c.git
cd paho.mqtt.c
mkdir build && cd build
cmake <whatever_options> ..


git clone https://github.com/eclipse/paho.mqtt.cpp.git
cd paho.mqtt.cpp
mkdir build && cd build
cmake <whatever_options> -DPAHO_MQTT_C_PATH=../../paho.mqtt.c ..
```

where the two repos are side by side of course.

It fails due to line:
```get_filename_component(PAHO_MQTT_C_DEV_LIB_DIR ${PAHO_MQTT_C_PATH}/build/output ABSOLUTE)```

in the accompanying CMakeLists.txt from source directory, as the paho.mqtt.c builds the libs under /src in its build directory.

I mention that I do not have the option to install the paho.mqtt.c library and use it in "dev" mode together with the paho.mqtt.cpp.

My temp fix is to change output to src in the CMakeLists.txt

I did not look under the other build systems from paho.mqtt.c/cpp so, I don't know if this breaks anything for others. Any suggestions to properly handle this going forward ?

**Comment by fpagliughi** [comment]
I wonder if the build for the Paho C library work completely differently when using _make_ and _CMake_. I believe that I have always been building it with _make_, like:
```
git clone https://github.com/eclipse/paho.mqtt.c.git
cd paho.mqtt.c
make
```
If you do that, then any of the build tools for the C++ library should work with the repositories side-by-side.

But I will keep this issue open and see if I can't fix it to work with either C build system.

**Comment by ptrsr** [comment]
even when using the `make` command directly in the paho.mqtt.c folder, making the c++ library with cmake with any kind of `PAHO_MQTT_C_PATH` specified doesn't work. What am I doing wrong? It constantly gives me  "Make Error at src/CMakeLists.txt:152 (message):                                                                                                                  Could not find Paho MQTT C library".

**Comment by rstoica** [comment]
The cmake declared paths for C++ library and the ones in C are not matching. I think there is difference of a folder name from /lib to /src or something like this (I cannot check now explicitly as I don't have access to my dev machine). What you can do is check where is the C lib created in dev mode and then modify the C++ cmake lib C lookup to that folder instance. Then it will work. In my project I had them as submodules and to not care about dependencies I had a script doing this automatically within cmake. Hope this helps. Can look more into it next week and let you know the exact local fix or submit a quick fix PR

**Comment by fpagliughi** [comment]
There are several scenario that the C++ build systems are trying to consider.

First, if you are just working with the C++ library, then first you build and install the Paho C library, and the C++ lib needs to locate it in the install path.

When developing the C++ library, you might also want to test against multiple versions of the C library which are installed in different directories.

But if (like me) you are developing and modifying both the C++ and the C library at the same time, then the most convenient work flow it to build the C library but _not_ install it. Leave it in the development tree, and let the C++ library find it there. That creates a totally different directory tree to search.

To complicate this even further, the C library can be built with GNU Make or CMake, and each of those tools creates a different development tree.

So the C++ library is trying to deal with any of these possibilities as to the location of the Paho C library:

1. The C library was built and installed to the default location.
2. The C library was built and installed to a user-defined location.
2. The C library was built in the development tree using GNU Make.
3. The C library was built in the development tree using CMake.

So, hopefully the C++ build systems can handle these scenarios. But it may not be perfect yet.

**Comment by ptrsr** [comment]
Thank you for all the responses! It was my own fault, I didn't use the `PAHO_MQTT_C_PATH ` properly. I should've added a D before it to tell the compiler it's a directory. I kept overlooking it. Lesson learned the hard way

**Comment by fpagliughi** [comment]
This is fixed, but changed with the latest build system. Set the CMAKE_PREFIX_PATH to the location of the Paho C library if it's not installed to a default location, or if you want to work with a specific C version for development. Use like:
```
$ cmake -DCMAKE_PREFIX_PATH=/home/fmp/mqtt/paho.mqtt.c/build/_install/usr/local ..
```

**Comment by veenusav** [comment]
A windows story!
I have fixed by adding -DPAHO_MQTT_C_LIBRARIES=C:\mqtt\paho-c\lib
I have installed C in C:\mqtt\paho-c.  

See in full :
`D:\code\paho.mqtt.cpp-master> cmake -G "Visual Studio 16 2019" -A x64 -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\lib\mqtt\paho-cpp -DPAHO_WITH_SSL=OFF -DCMAKE_PREFIX_PATH=C:\lib\mqtt\paho-c -DPAHO_MQTT_C_LIBRARIES=C:\mqtt\paho-c\lib
D:\code\paho.mqtt.cpp-master> cmake --build build/ --target install
`

**Comment by timsschoen** [comment]
@veenusav Yes, just had the same problem on Windows. I propose adding this to the README.

**Comment by jasonpp** [comment]
> A windows story!
> I have fixed by adding -DPAHO_MQTT_C_LIBRARIES=C:\mqtt\paho-c\lib
> I have installed C in C:\mqtt\paho-c.
> 
> See in full :
> `D:\code\paho.mqtt.cpp-master> cmake -G "Visual Studio 16 2019" -A x64 -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\lib\mqtt\paho-cpp -DPAHO_WITH_SSL=OFF -DCMAKE_PREFIX_PATH=C:\lib\mqtt\paho-c -DPAHO_MQTT_C_LIBRARIES=C:\mqtt\paho-c\lib D:\code\paho.mqtt.cpp-master> cmake --build build/ --target install `

1. cmake -G "Visual Studio 16 2019" -A x64 -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\mqtt\paho-cpp -DPAHO_WITH_SSL=OFF -DCMAKE_PREFIX_PATH=C:\mqtt\paho-c - DPAHO_MQTT_C_LIBRARIES=C:\mqtt\paho-c\lib
2. cmake --build build/ --target install
