### ISSUE TITLE
Migration guide from v0.5 to v1.0.0

### ISSUE THREAD

**Issue by amitmangalvedkar** [eclipse/paho.mqtt.cpp#132]
I had been using the paho cpp v0.5 for sometime and now wish to move to v1.0. However, I am seeing that v1.0.0 is incompatible with v0.5 with many methods / fields being renamed or made redundant. This is causing delay in migration. So I would like to know if there is any migration guide or cheat-sheet that can be used for this purpose.

**Comment by fpagliughi** [comment]
Closing as no one has taken this on.
