### ISSUE TITLE
VS 2015: building an app integrating the paho-mqttpp3 dynamic and static libs

### ISSUE THREAD

**Issue by cavalleydude** [eclipse/paho.mqtt.cpp#133]
I'm using Windows 7 and VS 2015 to build a C++ plugin and I'd like to integrate the paho-mqttpp3 DLL into my project, but I've run into a multitude of linker issues, because my app compiles to a DLL also and I keep ending up with missing external symbols, etc. It would be great to see some sample VS apps that uses the dynamic and static library files.

**Comment by fpagliughi** [comment]
This should be fixed in the 'develop' and 'master' branches.
