### ISSUE TITLE
PUBREL is delayed by 10 seconds, when message is published in message_arrived().

### ISSUE THREAD

**Issue by coldmund** [eclipse/paho.mqtt.cpp#134]
Environment: Ubuntu 14 for both clients. Using Mosquitto as broker. Both clients inherited async_client.
I'm testing with modification of sample codes(async_subscribe.cpp, async_publish.cpp). When a client publishs a message with QOS2 in message_arrived(), the message arrives the other client after 10 seconds.
Below is the mosquitto's log, and the delay is found at PUBREL packet.
>1512528454: Received PUBLISH from SERVER1 (d0, q2, r0, m14, 'DN/CLIENT1', ... (12 bytes))
>1512528454: Sending PUBREC to SERVER1 (Mid: 14)
>1512528454: Received PUBREL from SERVER1 (Mid: 14)
>1512528454: Sending PUBCOMP to SERVER1 (Mid: 14)
>1512528454: Sending PUBLISH to CLIENT1 (d0, q2, r0, m1, 'DN/CLIENT1', ... (12 bytes))
>1512528454: Received PUBREC from CLIENT1 (Mid: 1)
>1512528454: Sending PUBREL to CLIENT1 (Mid: 1)
>1512528454: Received PUBCOMP from CLIENT1 (Mid: 1)
>1512528454: Received PUBLISH from CLIENT1 (d0, q2, r0, m5, 'UP/CLIENT1', ... (528 bytes))
>1512528454: Sending PUBREC to CLIENT1 (Mid: 5)
>1512528464: Received PUBREL from CLIENT1 (Mid: 5)
>1512528464: Sending PUBCOMP to CLIENT1 (Mid: 5)
>1512528464: Sending PUBLISH to SERVER1 (d0, q2, r0, m15, 'UP/CLIENT1', ... (528 bytes))
>1512528464: Received PUBREC from SERVER1 (Mid: 15)
>1512528464: Sending PUBREL to SERVER1 (Mid: 15)
>1512528464: Received PUBCOMP from SERVER1 (Mid: 15)

If I change QOS to 1 or publish the message in other thead, there's no delay.
Is it normal operation?

**Comment by fpagliughi** [comment]
No, this isn't normal operation. The price of QoS 2 is a second round-trip set of packets for each message, but that should be on the order of 10ms, not 10 sec! I'm assuming that you're running on a LAN with the latest release versions of the Paho C & C++ libraries installed?

Ten seconds sounds like a timeout value... as if a packet is getting hung up in a buggy place somewhere, then a timeout occurs and un-jams it. But that's just a wild guess. I'll try it out.

**Comment by coldmund** [comment]
Yes, I'm running on a LAN both client in same site. Paho.c and c++ are both the latest commit.
As you mentioned, my time out value is 10 seconds.

**Comment by coldmund** [comment]
I modified 'async_publish.cpp' in src/samples and the code is like the below:
```
class callback : public virtual mqtt::callback
{
  mqtt::async_client &cli_;
public:
  callback(mqtt::async_client &cli) : cli_(cli) {}
  void connected(const string &cause) override {
    cli_.subscribe(TOPIC, 2)->wait_for(TIMEOUT);  // return after timeout
  }
  void message_arrived(mqtt::const_message_ptr msg) override {
    cli_.publish(TOPIC, PAYLOAD, strlen(PAYLOAD), 2, false)->wait_for(TIMEOUT);  // return after timeout
  }
 ...
};
```
Is this usage wrong? In 'async_subscribe.cpp', `callback` class inherits both `mqtt::callback` and `mqtt::iaction_listener`, and does not override `mqtt::callback::connected` but override `mqtt::iaction_listener::on_success`. I added `subscribe()` and `publish()` in `on_success()`, it was OK.

**Comment by fpagliughi** [comment]
Apologies for the slow response on this. I missed your last comment.

Yes, unfortunately, that usage is wrong. You should not make blocking calls from the asynchronous callback functions, especially not anything waiting on the library itself. So, don't use token `wait_...()` in the callbacks.

There is a single thread emanating from the Paho C library to service the callbacks. If you block it, then it is not available to service incoming events.
