### ISSUE TITLE
Unable to compile and run C++ file with MQTT Paho Client

### ISSUE THREAD

**Issue by UsesWincrt** [eclipse/paho.mqtt.cpp#136]
I am not able to compile c++ file with Mqtt paho client. I am finished the installation described in this repository, after library installation, i got this message

Paho MQTT C++ has been configured with the following options:

Build as shared library : no
        Build as static library : yes
                  Build samples : yes
            Build documentation : no
      Enable peak warning level : no
               With Paho MQTT C : /home/yahya/Desktop/DevTools/paho.mqtt.c
           With OpenSSL library : yes
                  With CPPFLAGS :  -I/home/yahya/Desktop/DevTools/paho.mqtt.c/src -I/home/yahya/Desktop/DevTools/paho.mqtt.c/include
                    With CFLAGS : -g -O2
                  With CXXFLAGS : -g -O2
                   With LDFLAGS :  -L/home/yahya/Desktop/DevTools/paho.mqtt.c/build/output -L/home/yahya/Desktop/DevTools/paho.mqtt.c/lib -L/home/yahya/Desktop/DevTools/paho.mqtt.c/lib64
                 With libraries : -lpaho-mqtt3as -lssl -lcrypto -lpthread

   Compiling C programs works, i just need to add -lpaho-mqtt3as to gcc  command. For c++ even when i add all C/C++  CPPFLAGS, LDFLAGS and libraries i get this: 

hello.cpp:(.text+0x30d): undefined reference to `mqtt::async_client::async_client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mqtt::iclient_persistence*)'
hello.cpp:(.text+0x335): undefined reference to `mqtt::async_client::set_callback(mqtt::callback&)'
hello.cpp:(.text+0x344): undefined reference to `mqtt::connect_options::connect_options()'
hello.cpp:(.text+0x399): undefined reference to `mqtt::message::message(mqtt::buffer_ref<char>, mqtt::buffer_ref<char>, int, bool)'
hello.cpp:(.text+0x3d0): undefined reference to `mqtt::will_options::will_options(mqtt::message const&)'
hello.cpp:(.text+0x3e9): undefined reference to `mqtt::connect_options::set_will(mqtt::will_options const&)'
hello.cpp:(.text+0x43a): undefined reference to `mqtt::connect_options::connect_options(mqtt::connect_options const&)'
hello.cpp:(.text+0x45a): undefined reference to `mqtt::async_client::connect(mqtt::connect_options)'
hello.cpp:(.text+0x59b): undefined reference to `mqtt::async_client::publish(std::shared_ptr<mqtt::message const>)'
hello.cpp:(.text+0x67f): undefined reference to `mqtt::async_client::publish(mqtt::buffer_ref<char>, void const*, unsigned long, int, bool)'
hello.cpp:(.text+0x8c8): undefined reference to `mqtt::async_client::publish(std::shared_ptr<mqtt::message const>, void*, mqtt::iaction_listener&)'
hello.cpp:(.text+0xa3c): undefined reference to `mqtt::async_client::publish(std::shared_ptr<mqtt::message const>, void*, mqtt::iaction_listener&)'
hello.cpp:(.text+0xad9): undefined reference to `mqtt::async_client::get_pending_delivery_tokens() const'
hello.cpp:(.text+0xc4c): undefined reference to `mqtt::async_client::~async_client()'
hello.cpp:(.text+0xf88): undefined reference to `mqtt::async_client::~async_client()'
/tmp/cccJnSS2.o: In function `mqtt::message::create(mqtt::buffer_ref<char>, mqtt::buffer_ref<char>)':
hello.cpp:(.text._ZN4mqtt7message6createENS_10buffer_refIcEES2_[_ZN4mqtt7message6createENS_10buffer_refIcEES2_]+0x48): undefined reference to `mqtt::message::DFLT_RETAINED'
hello.cpp:(.text._ZN4mqtt7message6createENS_10buffer_refIcEES2_[_ZN4mqtt7message6createENS_10buffer_refIcEES2_]+0x4d): undefined reference to `mqtt::message::DFLT_QOS'
/tmp/cccJnSS2.o: In function `mqtt::message::get_payload[abi:cxx11]() const':
hello.cpp:(.text._ZNK4mqtt7message11get_payloadB5cxx11Ev[_ZNK4mqtt7message11get_payloadB5cxx11Ev]+0x33): undefined reference to `mqtt::message::EMPTY_BIN[abi:cxx11]'
/tmp/cccJnSS2.o: In function `mqtt::async_client::disconnect()':
hello.cpp:(.text._ZN4mqtt12async_client10disconnectEv[_ZN4mqtt12async_client10disconnectEv]+0x36): undefined reference to `mqtt::disconnect_options::disconnect_options()'
/tmp/cccJnSS2.o: In function `void __gnu_cxx::new_allocator<mqtt::message>::construct<mqtt::message, mqtt::buffer_ref<char>, mqtt::buffer_ref<char>, int const&, bool const&>(mqtt::message*, mqtt::buffer_ref<char>&&, mqtt::buffer_ref<char>&&, int const&, bool const&)':
hello.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN4mqtt7messageEE9constructIS2_JNS1_10buffer_refIcEES6_RKiRKbEEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorIN4mqtt7messageEE9constructIS2_JNS1_10buffer_refIcEES6_RKiRKbEEEvPT_DpOT0_]+0xdc): undefined reference to `mqtt::message::message(mqtt::buffer_ref<char>, mqtt::buffer_ref<char>, int, bool)'
collect2: error: ld returned 1 exit status

**Comment by InFaMoUsZero** [comment]
You've probably compiled something as shared.

Try this script if you're on Linux:

`#!/bin/sh
#
# Installs all required dependencies
#

PROJECT_DIR="$( cd "$( dirname "$0" )" && pwd )"
BUILD_DEPS_DIR="$PROJECT_DIR/build-deps/"

# Create temp directory for building/pulling external libs
if [ ! -d "$BUILD_DEPS_DIR" ]; then
sudo mkdir ${PROJECT_DIR}/build-deps/
fi

## Install dependencies required via apt-get
apt-get update
apt-get install -y  build-essential                 \
                    libssl-dev                      \
                    gcc                             \
                    make                            \
                    cmake                           \
                    cmake-gui                       \
                    cmake-curses-gui                \
                    automake                        \
                    autoconf                        \
                    libtool                         \
                    doxygen                         \
                    graphviz                        \
                    git                             \
                    gcc-arm-linux-gnueabihf         \
                    g++-arm-linux-gnueabihf         \
                    pkg-config-arm-linux-gnueabihf

# Pull PAHO.MQTT.C from github
cd ${PROJECT_DIR}/build-deps/
git clone https://github.com/eclipse/paho.mqtt.c

# Build PAHO.MQTT.C & installing..
cd ${PROJECT_DIR}/build-deps/paho.mqtt.c/
cmake -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SAMPLES=TRUE ${CROSS_COMPILE_ARG}
make
sudo make install

# Pull PAHO.MQTT.CPP from github
cd ${PROJECT_DIR}/build-deps/
git clone https://github.com/eclipse/paho.mqtt.cpp

# Building PAHO.MQTT.CPP & installing..
cd ${PROJECT_DIR}/build-deps/paho.mqtt.cpp/
cmake -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE \
        -DPAHO_MQTT_C_PATH=../paho.mqtt.c/ -DPAHO_MQTT_C_LIB=../paho.mqtt.c/src/libpaho.mqtt3as-static.a ${CROSS_COMPILE_ARG}
make
make install

echo "Cleaning up temporary files.."
sudo rm -r ${PROJECT_DIR}/build-deps
echo "Cleaning up done"

# Regenerate cache and links to libs
sudo ldconfig
`

This will install the libs and headers for you to reference in your project directly. No need to add their locations.

**Comment by fpagliughi** [comment]
You need to link with both the Paho C (libpaho-mqtt3as.so) and the Paho C++ (libpaho-mqttpp3.so). It looks like maybe you remembered the C library but forgot the C++ one?
Try adding "-lpaho-mqttpp3" to the compile/link line.

**Comment by UsesWincrt** [comment]
@InFaMoUsZero @fpagliughi thank you, it works now, the problem was missing to link the c++ library

**Comment by srkyboy** [comment]
@fpagliughi Thank you, that solved my problem also, the missing lib -lpaho-mqttpp3.

**Comment by neilyoung** [comment]
> echo "Cleaning up temporary files.."
> sudo rm -r ${PROJECT_DIR}/build-deps
> echo "Cleaning up done"
> 
> # Regenerate cache and links to libs
> sudo ldconfig
> ```

I could compile paho.mqtt.c , but CMAKE for *.cpp fails like

```
-- Configuring done
CMake Error at src/CMakeLists.txt:80 (add_library):
  Target "paho-mqttpp3-static" links to target
  "eclipse-paho-mqtt-c::paho-mqtt3as-static" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

What am I missing?
