### ISSUE TITLE
TLS issue cpp on macOS

### ISSUE THREAD

**Issue by JeffLabonte** [eclipse/paho.mqtt.cpp#137]
Hi guys,

I am trying to connect to my mosquitto server using c++ on my mac and I am getting this error :

```
123145416470528:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:s3_pkt.c:1500:SSL alert number 40
MQTT error [-1]: TCP/TLS connect failure
```

I am using the same certificates I am using on my raspberry pi which is currently running and publishing data.

This is the code I use right now. I scrapped it from tests and samples.

``` 
 try{
        mqtt::client client(ADDRESS, "10");
        mqtt::connect_options connOpts;
        mqtt::ssl_options sslOptions;
        sslOptions.set_trust_store("/Users/jefflabonte/Documents/Development/Projects/MyProject/certificates/device001_certs/mycert.pem");
//        sslOptions.set_key_store("/Users/jefflabonte/Documents/Development/Projects/MyProject/certificates/device001_certs/device001.crt");
        connOpts.set_ssl(sslOptions);
        connOpts.set_mqtt_version(MQTTVERSION_3_1_1);
        connOpts.set_keep_alive_interval(20);
        connOpts.set_clean_session(true);

        client.connect(connOpts);

    }catch(mqtt::exception ex){
        std::cerr << ex.to_string() << std::endl;

    }
```

Any idea on what I did wrong?

**Comment by JeffLabonte** [comment]
I will have a second look on the .crt file, make sure I generated it correctly. The certificate concept is still a bit fuzzy for me. 

I am not using the library for a RPI, I am looking to use it in my web service.

**Comment by fpagliughi** [comment]
The C++ wrapper just passes the names of the files that you send it down to the underlying Paho C library, which does all of the hard work. To test the sample C++ app, all I did was run mosquitto with the configuration provided by the C library. You can do this on the RPi just as a sanity check:
```
$ git clone https://github.com/eclipse/paho.mqtt.c.git
$ cd paho.mqtt.c
$ mosquitto -c test/tls-testing/mosquitto.conf
```

Just make sure that there isn't another copy of mosquitto running.

Then, copy the file `paho.mqtt.c/test/tls-testing/keys/test-root-ca.crt` onto your Mac into the same directory as the C++ sample executable and run it. See if that works.

Actually, you need to modify the server URL in the sample app to point at your RPi. Then rebuild and try it.

If that works, then try something similar with your own certificates.

**Comment by JeffLabonte** [comment]
I will try it this evening and I will come back with the results. Thank you.

**Comment by JeffLabonte** [comment]
It seems to be working like a charm. So I believe this is must be the way I have generated my certificate.

Thank you for your time, I really appreciate it!

**Comment by JeffLabonte** [comment]
Well, I am unable to do connect to my broker when I am using my setup. I have generated a crt file from my CA. 

This is the type of certificate, I generate :
```
-----BEGIN TRUSTED CERTIFICATE-----
MIIDOjCCAiICCQDy6l/nnavyfzANBgkqhkiG9w0BAQsFADBDMQswCQYDVQQGEwJD
QTEPMA0GA1UECAwGUXVlYmVjMRQwEgYDVQQHDAtRdWViZWMgY2l0eTENMAsGA1UE
CgwESG9tZTAeFw0xODAxMTQwMzMwNDBaFw0yODAxMTIwMzMwNDBaMHsxCzAJBgNV
BAYTAkNBMQ8wDQYDVQQIDAZRdWViZWMxDzANBgNVBAcMBlFVZWJlYzEhMB8GA1UE
CgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMScwJQYJKoZIhvcNAQkBFhhqZWZm
LmxhYm9udGUxMkBnbWFpbC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDS7pnbUZ7zXG0h5zGyzEixPd/5HQnHegBWIwlDsI/KrplwninyzqxnMX09
Pyz9CGAXGnhj8mYi6Y9Rys7+nN0HwJ903mq5N3vsDQu0TVR3qqze6YV0nEBgA3Je
UhHedII3ytIrqHQB9S1mNPOlmQc28PTotgXbxunPLWPAlEwe+wUxTilEhCiVedNd
OC4ckGnEBqXotVfnHMNl6Znj7A29cujifUcF+R39Rt2RtfqckUjVXYKvD9Jv0BsA
UO+KWKUC/cClKr6037bx9wpgus1fUWCp2kuXzckGOhdeGrzaDVbT7uJ1sWkfJ/WF
+aDFtoRWHv4Z4P3GrkxJw/iwyU4bAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAA39
wJlDAYAHWt5F8gXDtuw9Brc/MlTvMdtbjCKlWHyD6Zm5jzY5lO/J6iwdHXxJ9Fjb
zLLJ85eJyXUmd/tJ8FkQttk+G69AGoM1azM+GbSV1geVaahcbQ0d4zF3N3dPNjL8
K2mYPATKjzvUXyKlRDxxdqdDVFYGkU1/y13i6S6Jkuv8eeL0jhdAZg+qX6gg+fux
95uu2mEaLux6jBX2HctncSifZcLX5jCKysA4KYob+fBWGTJBh4Ejny0lVt3JBVNW
29Xr08T1U1dIlWA5gpc5tDSYJhf34JvvtnWWCGady3h7C610DHqFINgEed82fES0
7OCoIHQwNe4wvoABd18wDDAKBggrBgEFBQcDAg==
-----END TRUSTED CERTIFICATE-----

```

**Comment by JeffLabonte** [comment]
That is what I trying to figure out because I am using this certificate with the python library of paho mqtt. 

On python, I am using this CA plus the device key and certificate, which may be the reason why it doesn't work with the cpp library.

I am trying to figure out what is wrong, the library or my certificate.

**Comment by JeffLabonte** [comment]
Would it be possible to have the command you guys used to generate your CA?

I have tried many things to make it work and I still have the TLS error.

**Comment by fpagliughi** [comment]
Is this working? Can the issue be closed?
