### ISSUE TITLE
Async Client's Connect Method gives pure virtual method called

### ISSUE THREAD

**Issue by xBartu** [eclipse/paho.mqtt.cpp#138]
Hi all,

I am developing an application for developers in order to increase the efficient work. To do so, I created new methods for the codes in heavily use. Whenever I try to put the async client as attribute and a connect method in a different method, I get the following-up error:

```
pure virtual method called
terminate called without an active exception
Aborted (core dumped)

```
To give insights and make the understanding clear, a few snippet from my code as follow:

```
void A::connect(mqtt:connect_options opts, SCallback cb) {
        try {
            this->aclient.connect(opts, nullptr, cb);
        } catch (const mqtt::exception&) {
            throw std::runtime_error("Couldn't connect");
        }
}


```
Above methos to connect and I have setup:
```
void A::setup() {
        mqtt::connect_options opts;
        opts.set_keep_alive_interval(20);
        opts.set_clean_session(true);
        SCallback cb(this->aclient, opts, topic_name);
        this->aclient.set_callback(cb);
        this->connect(opts, cb); // throws the error.
}

```
Afterwards, the developer will do the job and close the connection. To illustrate:
```
void A::newJob() {
     this->setup();
     // here comes the work
     this->close();
}

```

Has anyone experienced it?
Thanks

**Comment by fpagliughi** [comment]
I've seen this error a few times. It can come from multiple deletions of the same of the same object and things like that. I've also seen it from proper code passed through a broken cross-compiler.

I'm going to guess that it has something to do with your `SCallback` object. You appear to be creating it on the stack in `setup()`, which means it is being destroyed when setup returns. So the client will be trying to call the virtual functions in a callback object that has already been deleted.

The callback object needs to remain alive as long as the client - or at least as long as the client is connected and making callbacks.

**Comment by xBartu** [comment]
Hey @fpagliughi,

I thought the same, however, I cannot purely put it as an attribute. I made it as a pointer. Then it becomes a segfault.

I thought it's better not to make it in the class. So whenever the developer want to subscribe they must create new one to pass it. 

Thanks again.

**Comment by xBartu** [comment]
Hi again,

I tried to created it in main loop, and passing address to client. Still it's the same. Any idea?

code:
```
    std::string s = "hi";
    Harmony::MQTTAsync client;
    mqtt::connect_options op = client.create_options(20, true);
    Harmony::SCallback cb = client.create_callback(op, "hello from async");
    client.subscribe(op, &cb);

    client.close();

```

**Comment by xBartu** [comment]
I found the mistake! For future reference, the problem is that it tries to close before connection!. So it crashes.

We can close for now.

**Comment by fpagliughi** [comment]
Do you mean that you are calling `client.close()` before the asynchronous `client.connect(...)` has completed?

**Comment by xBartu** [comment]
@fpagliughi that was the case for the approach in the comment, I thought this wasn't the case since I am working on local. I checked the stack and got the error.
