### ISSUE TITLE
There is no installation step in the readme

### ISSUE THREAD

**Issue by korish** [eclipse/paho.mqtt.cpp#139]
Hi,

According to the README.md, to install the library we need the pass following steps:
```

$ git clone https://github.com/eclipse/paho.mqtt.cpp
$ cd paho.mqtt.cpp
$ mkdir build
$ cd build
$ cmake -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE -DPAHO_MQTT_C_PATH=../../paho.mqtt.c ..
$ make
```
The question is, why there is no **make install** step there? I know that we can use it from the **build** folder or copy the results to **/usr/lib/** and **/usr/include/** folders but maybe it has sense to add such step in the installation manual. What do you think?

**Comment by fpagliughi** [comment]
OK. Thanks for pointing this out. I am going to start working on better documentation in the near future, including a wiki.
