### ISSUE TITLE
C++ naming conventions

### ISSUE THREAD

**Issue by thoism** [eclipse/paho.mqtt.cpp#142]
Hi,

I would like to know if the C++ naming conventions used for the project are mentioned somewhere like a reference document or something or Eclipse config tool etc.

Thank you in advance!

**Comment by fpagliughi** [comment]
I thought I ad added an .editorconfig file, but I don't see it, so maybe I didn't yet. I can do that soon. Other than that, there is nothing, currently, on the naming convention. Butt I can add a small note about the basic coding style. I plan on starting the Wiki soon.

**Comment by thoism** [comment]
Thank you very much man

**Comment by thoism** [comment]
Can I help in any way?
