### ISSUE TITLE
seg fault using shared pointer to an async mqtt client

### ISSUE THREAD

**Issue by saumilagg** [eclipse/paho.mqtt.cpp#146]
Hi @fpagliughi ,

I am using a mqtt::async_client_ptr in my code and publishing the message accordingly. However, my code is crashing in the end with a SEG fault from async_client.cpp file. 

After debugging I saw that in function remove_token(token *tok), the call cb->delivery_complete(dtok) is causing this. Could you help me out figuring this issue? I think maybe I am not initializing the pointer correctly?  Any examples using this smart pointer? 

This is how I am initializing: clientPtr = std::make_shared<mqtt::async_client>(tempStr,sn);

But I guess copy, move constructors are deleted!!

**Comment by fpagliughi** [comment]
Moving the conversation to #141
