### ISSUE TITLE
Unable to build on OSX

### ISSUE THREAD

**Issue by fjanicki** [eclipse/paho.mqtt.cpp#150]
I successfully installed this under Linux but when I try to build and install it under OSX, I get this error (with CMake and also Autotools)

Autotools
```
➜  paho.mqtt.cpp git:(master) ✗ make
c++ src/async_client.cpp
c++ src/client.cpp
c++ src/connect_options.cpp
c++ src/disconnect_options.cpp
c++ src/iclient_persistence.cpp
c++ src/message.cpp
c++ src/response_options.cpp
c++ src/ssl_options.cpp
c++ src/string_collection.cpp
c++ src/token.cpp
c++ src/topic.cpp
c++ src/will_options.cpp
Creating library: lib/libpaho-mqttpp3.so.1.0.0
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libpaho-mqttpp3.so.1.0.0] Error 1
```

CMake
```
➜  build git:(master) ✗ make
[  7%] Building CXX object src/CMakeFiles/OBJS.dir/async_client.cpp.o
[ 14%] Building CXX object src/CMakeFiles/OBJS.dir/client.cpp.o
[ 21%] Building CXX object src/CMakeFiles/OBJS.dir/disconnect_options.cpp.o
[ 28%] Building CXX object src/CMakeFiles/OBJS.dir/iclient_persistence.cpp.o
[ 35%] Building CXX object src/CMakeFiles/OBJS.dir/message.cpp.o
[ 42%] Building CXX object src/CMakeFiles/OBJS.dir/response_options.cpp.o
[ 50%] Building CXX object src/CMakeFiles/OBJS.dir/ssl_options.cpp.o
[ 57%] Building CXX object src/CMakeFiles/OBJS.dir/string_collection.cpp.o
[ 64%] Building CXX object src/CMakeFiles/OBJS.dir/token.cpp.o
[ 71%] Building CXX object src/CMakeFiles/OBJS.dir/topic.cpp.o
[ 78%] Building CXX object src/CMakeFiles/OBJS.dir/connect_options.cpp.o
[ 85%] Building CXX object src/CMakeFiles/OBJS.dir/will_options.cpp.o
[ 85%] Built target OBJS
make[2]: *** No rule to make target `/usr/local/lib/libpaho-mqtt3as.so', needed by `src/libpaho-mqttpp3.1.0.0.dylib'.  Stop.
make[1]: *** [src/CMakeFiles/paho-mqttpp3.dir/all] Error 2
make: *** [all] Error 2
```

Any idea on how to fix this?

**Comment by fpagliughi** [comment]
I don't have access to an OSX development machine. Can anyone else test this and possibly fix the CMake version?

The autotools version is deprecated at this point, and will disappear soon, so it's not worth spending time on that one.

**Comment by VilleViktor** [comment]
I had the same problem, but this solved it for me:

I actually found out that the files`/usr/local/lib/libpaho-mqtt3as.so` etc were linked to files with names: `/usr/local/lib/libpaho-mqtt3as.so.1` but the mac osx had named them `/usr/local/lib/libpaho-mqtt3as.so.1.0`

By just changing the name back to `/usr/local/lib/libpaho-mqtt3as.so.1` it solved the problem for me. Just removed the .0 by:

`mv /usr/local/lib/libpaho-mqtt3as.so.1.0 /usr/local/lib/libpaho-mqtt3as.so.1`

Hopes that helps you!

**Comment by dawagner** [comment]
@fjanicki, may you try again with #148? It might help.

@fpagliughi Travis CI has OSX builders.

**Comment by fjanicki** [comment]
Sorry for the delay, I just had been working on my Linux VM in the meantime. Just tried @VilleViktor solution and it worked. Seems like the linking/naming is not properly done and broken, and renaming all packages manually seems to work for now. Thanks!

**Comment by MGasztold** [comment]
I would appreciate if you prepare some solid fix for this issue. 

I tried @VilleViktor solution, i have the following packages under `/usr/local/lib/`:

```
libpaho-mqtt3a.so       libpaho-mqtt3as.so.1    libpaho-mqtt3cs.so.1
libpaho-mqtt3a.so.1     libpaho-mqtt3c.so       libpaho-mqtt3cs.so.1.0
libpaho-mqtt3a.so.1.0   libpaho-mqtt3c.so.1     
libpaho-mqtt3as.so      libpaho-mqtt3cs.so 
```

Still when I hit `make` i get this:
```mgasztold@mg:~/Dev/paho.mqtt.cpp$ make
Creating library: lib/libpaho-mqttpp3.so.1.0.0
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libpaho-mqttpp3.so.1.0.0] Error 1```

**Comment by fpagliughi** [comment]
Closing since this is ancient. The latest builds and passes all unit tests on MacOS.

But it would be good to update the CI and add a MacOS target.
