### ISSUE TITLE
Cross compiled code crashes with memory issues 

### ISSUE THREAD

**Issue by karanparmar26** [eclipse/paho.mqtt.cpp#153]
Hi,
I am testing cross-compiled code onto raspberry-pi board, it successfully publishes data for first 4 attempts, but during 5th attempt code crashes abruptly.

Please find attached debug logs file for more information.
[gdb_debug.log](https://github.com/eclipse/paho.mqtt.cpp/files/1991856/gdb_debug.log)

**Comment by fpagliughi** [comment]
Did you ever resolve this? If not:

- What cross-compiler were you using? 
- What host platform for the build?
