### ISSUE TITLE
PAHO_WITH_SSL build option doesn't have sufficient preprocessor guards 

### ISSUE THREAD

**Issue by kiranpradeep** [eclipse/paho.mqtt.cpp#156]
CMakeLists has a build option PAHO_WITH_SSL. But in connect_options.h, the header mqtt/ssl_options.h is not preprocessor guarded. A make install doesn't install the ssl_options.h when we turn off PAHO_WITH_SSL

**Comment by cyril3** [comment]
I have the same problem. help wanted. thanks very much.

**Comment by fpagliughi** [comment]
Actually, the quicker fix is to just install the _ssl_options.h_ even if you request a build with SSL turned off. The C++ library doesn't interface directly with the SSL library. Rather, it just passes some config options to the C library. 

If you try to connect using an SSL URL with this option turned off, you'll get a run-time connection error. But other than that, this is harmless.
