### ISSUE TITLE
Is there any plan to add hostname verification?

### ISSUE THREAD

**Issue by coldmund** [eclipse/paho.mqtt.cpp#158]
Hostname verification is added to paho.mqtt.c project at Mar 2, 2018(https://github.com/eclipse/paho.mqtt.c/issues/420). Is there any plan to add the feature to cpp project?

**Comment by fpagliughi** [comment]
Seems like a good idea. I'm just getting started on a couple of updates to the library.

**Comment by fpagliughi** [comment]
This was added in f4c192307f2eb3d5689e2669ed6f1cfead8c3a5b and ba3aceeb1a20677b37d7166252ce67819a08b435
