### ISSUE TITLE
[Suggestion] routine argument layout

### ISSUE THREAD

**Issue by guilhermeferreira** [eclipse/paho.mqtt.cpp#16]
I noticed many methods with a long parameter lists. For example:

**virtual** idelivery_token_ptr publish(**const** std::string& topic,
_________ **const** **void**\* payload, size_t n,
_________ **int** qos, **bool** retained, **void**\* userContext, 
_________ iaction_listener& cb) **throw**(exception) =0;

The section 31.7 (Laying Out Routines) from Code Complete suggests a layout with one parameter per line:

**virtual** idelivery_token_ptr publish(
_________ **const** std::string& topic,
_________ **const** **void**\* payload,
_________ size_t n,
_________ **int** qos,
_________ **bool** retained,
_________ **void**\* userContext, 
_________ iaction_listener& cb
) **throw**(exception) =0;

This layout provides a better visibility of all formal arguments and works better with version control systems, like Git, because the modification of each argument (or the routine's name) is spotted clearly.

What's your opinion about?

**Comment by fpagliughi** [comment]
Ehhhhh. I dunno. I think I lean toward better Doxygen-ation and documentation (which this projects still lacks to a great extent) and keeping the code more compact. Once published the API - and thus function signatures - won't change much.
