### ISSUE TITLE
Windows Cmake-GUI Static Build 

### ISSUE THREAD

**Issue by emesel** [eclipse/paho.mqtt.cpp#160]
When building with the windows Cmake-GUI, and adding the flag: PAHO_BUILD_STATIC=TRUE, the lib files are still being generated as dynamic. Can anyone point me in the right direction on what I am doing wrong?

**Comment by fpagliughi** [comment]
Unfortunately, I don't currently have a Windows machine running to check, but If I can remember back a year or two ago, I thought that on Windows, the static library had to be given a different base filename so as not to confuse the linker. I think it had "-static" in the name?

**Comment by emesel** [comment]
I was able to make a .lib file that is named "paho-mqtt3a-static.lib" as well as "paho-mqtt3c-static.lib" for the c version, but I haven't been able to make a .lib for the c++ version with "-static" in the name.
