### ISSUE TITLE
CONNACK

### ISSUE THREAD

**Issue by ciderglider** [eclipse/paho.mqtt.cpp#163]
I am looking at handling persistent connections with Paho. I have some code loosely based on the sample async_subscribe.cpp.

I'd like to examine the sessionPresent field CONNACK message from the broker to determine whether the client needs to re-subscribe to topics.

There is code in MQTTAsync.c that reads the sessionPresent field from the CONNACK and passes it to `on_success()` - (line 2162). But in` void token::on_success( MQTTAsync_successData* rsp)` the sessionPresent data within the `rsp.alt.connect` struct is discarded. (There doesn't seem to be a way of working out which member of the union in MQTTAsync_successData is active. )

Am I missing something? Is there a straightforward way for the c++ code to get hold of the sessionPresent data?

**Comment by ciderglider** [comment]
Thanks for letting me know. I'll look forward to the next release of the library!

**Comment by fpagliughi** [comment]
This got implemented over the summer. It's available from the GitHub repo, and will be part of the release, which should be ready as soon as I can figure out why Travis is giving me headaches.

The connect call now returns a `connect_response` object either through the token (in the case of the `async_client`) or directly (in the case of the synchronous `client`).

For the async client, something like this:
```
mqtt::token_ptr tok = cli.connect(connopts);
mqtt::connect_response rsp = tok->get_connect_response();
```
Note that the `get_connect_response()` blocks until the connect completes.

In the case of the synchronous client:
```
mqtt::connect_response rsp = cli.connect(connOpts);
```
Once you have the response, you can use it to see if the session is already present on the server, and if not, subscribe to topics:
```
if (!rsp.is_session_present())
    cli.subscribe(TOPICS, QOS);
```
Check out the new/updated sample apps, `rpc_math_cli.cpp` and `sync_consume.cpp`.
