### ISSUE TITLE
is_connected() returns false after the client auto reconnected to a server.

### ISSUE THREAD

**Issue by lgilson** [eclipse/paho.mqtt.cpp#166]
Hi,

I'm using the master-branch from the github, current version.

Auto-reconnecting to a broker fails partially. The client does reconnect automatically (broker sees the newly reconnected client), but is_connected() still return false and send still fails with the not-connected exception.

**Comment by fpagliughi** [comment]
I couldn't reproduce this issue. I wrote a quick test and it gave me these results:
```
Connecting to the MQTT server...
Connected

Is connected: 1
Is connected: 1

Connection lost

Is connected: 0
Is connected: 0
Is connected: 0

Connected: automatic reconnect

Is connected: 1
Is connected: 1
Is connected: 1
```
There were some recent updates. Can you fetch the latest code and verify if this is still a problem.

**Comment by fpagliughi** [comment]
I should mention that it might take a little while for the connection to be re-established using the auto reconnect - several seconds or more, after the network comes back up. Can you verify that `is_connected()` is still returning false _after_ the connection is actually made.
