### ISSUE TITLE
Unable to cross compile to ARRCH64  MQTT Paho C++ with error  “undefined reference to `mqtt::message::DFLT_RETAINED'”

### ISSUE THREAD

**Issue by KaleXia** [eclipse/paho.mqtt.cpp#167]
HI! used paho.mqtt.c and paho.mqtt.cpp   in x86 can run good.BUT when I compile it to arm ,I  encountered some mistakes like this.

`
CMakeFiles/mqtt_test.dir/PahoMqttImpl.cpp.o: In function `mqtt::message::create(mqtt::buffer_ref<char>, mqtt::buffer_ref<char>)':
PahoMqttImpl.cpp:(.text._ZN4mqtt7message6createENS_10buffer_refIcEES2_[_ZN4mqtt7message6createENS_10buffer_refIcEES2_]+0x44): undefined reference to `mqtt::message::DFLT_RETAINED'
PahoMqttImpl.cpp:(.text._ZN4mqtt7message6createENS_10buffer_refIcEES2_[_ZN4mqtt7message6createENS_10buffer_refIcEES2_]+0x48): undefined reference to `mqtt::message::DFLT_RETAINED'
PahoMqttImpl.cpp:(.text._ZN4mqtt7message6createENS_10buffer_refIcEES2_[_ZN4mqtt7message6createENS_10buffer_refIcEES2_]+0x4c): undefined reference to `mqtt::message::DFLT_QOS'
PahoMqttImpl.cpp:(.text._ZN4mqtt7message6createENS_10buffer_refIcEES2_[_ZN4mqtt7message6createENS_10buffer_refIcEES2_]+0x50): undefined reference to `mqtt::message::DFLT_QOS'
collect2: error: ld returned 1 exit status
CMakeFiles/mqtt_test.dir/build.make:224: recipe for target 'mqtt_test' failed
make[2]: *** [mqtt_test] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mqtt_test.dir/all' failed
make[1]: *** [CMakeFiles/mqtt_test.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

- I  compile PAHO.MQTT.C  IN ARM(aarch64)  like this:

`cmake -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -fPIC" -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fPIC" -DCMAKE_INSTALL_PREFIX=${C_PREFIX} -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=FALSE ..
`

- I compile PAHO.MQTT.CPP  IN ARM(aarch64)  like this:

`cmake -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -fPIC" -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fPIC" -DCMAKE_INSTALL_PREFIX=${CPP_PREFIX} -DPAHO_MQTT_C_PATH=${PAHO_C_PATH}  -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_STATIC=TRUE -DPAHO_BUILD_SHARED=FALSE -DPAHO_WITH_SSL=TRUE ..
`

- I compile my project CMakelist.txt:

`cmake_minimum_required(VERSION 3.6.2)
set(CMAKE_CXX_STANDARD 11)

set(CMAKE_C_FLAGS  "${CMAKE_C_FLAGS} -fPIC")
set(CMAKE_CXX_FLAGS  "${CMAKE_CXX_FLAGS} -fPIC")

set(MQTT_C_HOME ${C_PREFIX})
set(MQTT_CPP_HOME ${CPP_PREFIX})
set(OPENSSL_HOME /usr/lib/aarch64-linux-gnu)

LINK_LIBRARIES(pthread)
include_directories(${OPENSSL_HOME}/include)
include_directories(${MQTT_C_HOME}/include)
include_directories(${MQTT_CPP_HOME}/include)

link_directories(${OPENSSL_HOME}/lib)
link_directories(${MQTT_C_HOME}/lib)
link_directories(${MQTT_CPP_HOME}/lib)

set(THIRD_PARTY_LIBS -lssl -lcrypto
         -lpthread
         **-lpaho-mqttpp3
         -lpaho-mqtt3a**
        )

aux_source_directory(. MQTT_SRC) # IOT configure files

add_executable(mqtt_test main.cpp ${MQTT_SRC} )
target_link_libraries(mqtt_test
        ${THIRD_PARTY_LIBS}
        )

add_library(agiot-mqtt SHARED ${MQTT_SRC}   )
target_link_libraries(agiot-mqtt
        ${THIRD_PARTY_LIBS}
        )

SET_TARGET_PROPERTIES (agiot-mqtt PROPERTIES VERSION 1.0 SOVERSION 1.3)

INSTALL (TARGETS agiot-mqtt
        LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
        )

INSTALL (DIRECTORY iotmqtt DESTINATION ${CMAKE_INSTALL_PREFIX}/include)
`

**Comment by fpagliughi** [comment]
These types of issues seem to be from variations in different compilers.
What compiler are you using? Which version?

**Comment by fpagliughi** [comment]
Closing due to no reply
