### ISSUE TITLE
Update the Unit Test framework.

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.cpp#169]
It's probably time to move the Unit Tests to a more modern framework. I'm leaning heavily toward Catch2. 
Any thoughts?

**Comment by dawagner** [comment]
Catch2 is a great framework indeed.

**Comment by fpagliughi** [comment]
New code for MQTT v5 ('mqttv5' branch) is using Catch2. So far it is working well. 
Now comes the task of rewriting legacy tests to use Catch2, and integrating that with Travis.

**Comment by fpagliughi** [comment]
This is partially complete. Hopefully we can get it finished by v1.2

**Comment by fpagliughi** [comment]
Done
