### ISSUE TITLE
[Question] is the client::unsubscribe() calling the correct method?

### ISSUE THREAD

**Issue by guilhermeferreira** [eclipse/paho.mqtt.cpp#17]
The method [void client::unsubscribe(const topic_filter_collection& topicFilters)](https://github.com/eclipse/paho.mqtt.cpp/blob/develop/src/client.cpp#L163) calls [async_client::subscribe()](https://github.com/eclipse/paho.mqtt.cpp/blob/develop/src/client.cpp#L169) instead of async_client::unsubscribe(). Is it correct? If this is correct, should be there a comment explaining this counterintuitive behavior.

**Comment by fpagliughi** [comment]
Looks like a cut-and-paste error. Nice catch. I'll have it fixed in the next update.
