### ISSUE TITLE
Building paho.mqtt.cpp with cmake as library

### ISSUE THREAD

**Issue by m4rcs** [eclipse/paho.mqtt.cpp#172]
Hi, I'm struggeling to use this lib in combination with cmake. So I made a simple example 

Project structure:
```
libs/
  paho.mqtt.c/    <- precompiled C lib from https://projects.eclipse.org/projects/technology.paho/downloads
  paho.mqtt.cpp/  <- this repo
CMakeList.txt     <- see below
async_publish.cpp <- from /src/samples/
```
CMakeList.txt
```cmake
cmake_minimum_required (VERSION 3.8)

project ("async_publish")

include_directories (./libs/paho.mqtt.cpp/src ./libs/paho.mqtt.c/include)

add_executable (async_publish async_publish.cpp)

add_subdirectory (./libs/paho.mqtt.cpp)
target_link_libraries (async_publish paho-cpp-objs)
```

Now when I try to run `cmake` with that setup I get the following error:
```
CMake Error at libs/paho.mqtt.cpp/src/CMakeLists.txt:26 (find_package):
  By not providing "FindPahoMqttC.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "PahoMqttC", but CMake did not find one.

  Could not find a package configuration file provided by "PahoMqttC" with
  any of the following names:

    PahoMqttCConfig.cmake
    pahomqttc-config.cmake

  Add the installation prefix of "PahoMqttC" to CMAKE_PREFIX_PATH or set
  "PahoMqttC_DIR" to a directory containing one of the above files.  If
  "PahoMqttC" provides a separate development package or SDK, be sure it has
  been installed.
```

Can you help me with that issue? I tried setting `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` to different folders but nothing fixed it. I tried it with Visual Studio 2017 and Ubuntu 18.04 both show the exact same error.

Thank you!

**Comment by fpagliughi** [comment]
Apologies for the slow response. I'm a CMake novice; most of the build system was implemented by others.

First, I put the C lib under the C++ lib directory. I believe the C++ build system will find it there automatically, so:
```
libs/
  paho.mqtt.cpp/  <- this repo
      paho.mqtt.c/  <- precompiled C lib
CMakeList.txt     <- see below
async_publish.cpp <- from /src/samples/
```
As you did, I got the precompiled C lib from https://projects.eclipse.org/projects/technology.paho/downloads
I found the C lib v1.3.0, which is a good one to use.

I updated the CMakeLists.txt file to this:
```
cmake_minimum_required(VERSION 3.8)

project(async_publish)

include_directories(libs/paho.mqtt.cpp/src libs/paho.mqtt.cpp/paho.mqtt.c/include)

add_subdirectory (libs/paho.mqtt.cpp)

add_executable(async_publish async_publish.cpp)
target_link_libraries(async_publish paho-mqttpp3)
```
Note that I link with the actual library, not the obj library. (But you can fiddle with that.)

Looking at the error message we see:
```
By not providing "FindPahoMqttC.cmake" in CMAKE_MODULE_PATH...
```
So it means that the build can't find the files in the C++ library's `cmake` subdirectory directory. You can specify this at the command line, but it appears to need an absolute path. In my tree, this worked:

```
$ mkdir build ; cd build
$ cmake -DCMAKE_MODULE_PATH=/home/fmp/tmp/paho_cpp_client/libs/paho.mqtt.cpp/cmake ..
```

**Comment by fpagliughi** [comment]
Actually, it looks like I can fix this in the build file. It's setting the module path, with a cmake entry relative to the top-level source directory:
```
list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)
```
If we change this to the project source directory, instead *${PROJECT_SOURCE_DIR}/cmake*, then is should work for both a stand-alone build, and when included as a subdirectory.

I just pushed this to the 'develop' branch.

**Comment by jsrivaya** [comment]
@m4rcs  I would suggest ussing conan and avoid having to build the library yourself

Here is the recipe
https://conan.io/center/paho-c?os=Linux&tab=recipe
