### ISSUE TITLE
Build seems impossible using cmake

### ISSUE THREAD

**Issue by Laro88** [eclipse/paho.mqtt.cpp#173]
Both the async and syncc libraries are needed for linking the cpp project, however cmake only has a single parameter PAHO_MQTT_C_LIBRARIES. It seems to be required that to include all the libs needed so effectively cmake seems broken.

The shell instructions in the readme is also broken.

Regards

**Comment by fpagliughi** [comment]
The C++ library only wraps the asynchronous interface of the Paho C library. Thus it links to either the "a" or "as" variety of the C lib, depending on whether you want to use the SSL/TLS connections. (_libpaho-mqtt3as.so_ for SSL or _libpaho-mqtt3a.so_ to go without SSL).

The synchronous C++ client just calls to the async client and blocks waiting for operations to complere.

Let us know what system you're working on, and what specific errors you're seeing, and perhaps someone can help solve the problem.

**Comment by Laro88** [comment]
I tried to include both paho.mqtt.c libraries when building, using only the async at least allows me to get a lib file.
Should anybody need a cmake windows example from command line:
```
cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\libraries\paho.mqtt.cpp -DPAHO_BUILD_SAMPLES=ON -DPAHO_BUILD_STATIC=ON -DPAHO_WITH_SSL=OFF -DCMAKE_PREFIX_PATH=C:\libraries\paho.mqtt.c -DPAHO_MQTT_C_INCLUDE_DIRS=C:\GitProjects\github\paho.mqtt.c\src -DPAHO_MQTT_C_LIBRARIES=C:\libraries\paho.mqtt.c\src\Debug\paho-mqtt3a-static.lib
cmake --build build/ --target install

**Comment by fpagliughi** [comment]
Thanks! I don't use Windows very often. I'll add some additional information to the README to help with this.
