### ISSUE TITLE
Connection error 6 when connecting to a mosquitto mqtt server

### ISSUE THREAD

**Issue by Laro88** [eclipse/paho.mqtt.cpp#174]
Shell capture:
```
C:\libraries\paho.mqtt.cpp\bin>sync_publish.exe
Initialzing...
[Opening persistence store for 'sync_publish_cpp' at 'localhost:1883']
...OK

Connecting...
MQTT error [6]
[Clearing persistence store.]
[Persistence removing key 'c-0']
[Closing persistence store.]
```
and
```
C:\libraries\paho.mqtt.cpp\bin>data_publish.exe
Connecting to server 'tcp://localhost:1883'...MQTT error [6]
```
Any suggestions.
MQTT.fx works fine.

**Comment by fpagliughi** [comment]
Hmm. I'm assuming that these are the sample apps straight from the repo. These are working fine under Linux. I think I have a laptop running Windows somewhere in a closet. I'll pull it out and have a look. Which version of the Paho C and C++ libraries are you using? Which version of Windows?

**Comment by fpagliughi** [comment]
BTW, I have not tested this against the latest Paho C library in the repository. Just the last two release versions: 1.3.0 and 1.2.1. Try one of those first to see if it fixes the problem (preferably v1.3.0)

**Comment by Laro88** [comment]
I am on windows 10 x64, mosquitto 1.5.4 32 x86 (I am usually testing with mosquitto both 32 and 64 bit.)

Just tried the paho c library 1.3.0 (that is available for download which works fine so at least that version seems ok :-) There does not seem to be a cpp library available for download but I will try to build it against the ones I just verified.

**Comment by Laro88** [comment]
The 1,3,0 source is compiling and samples are ok.
The problem seems to be with the -static.lib (which I used)

Running the build linking the paho-mqtt3a.lib and after+ copying the paho-mqtt3a.dll  works fine.
Running the same linking the paho-mqtt3a-static.dll causes the crash situation.

I have no idea as to why the -static is not building, however it breaks the same way. Normally in win32 I just create static lib files and link these together to create a single executable so I have no clue as to why it does not work.

Here is my build batfile
```
rem NONSTATIC - OK, remember to copy dll
cmake -Bbuild -H. -DCMAKE_CONFIG_TYPES=Debug -DCMAKE_INSTALL_PREFIX=C:\Users\x\Documents\libraries\paho.mqtt.cpp -DPAHO_BUILD_SAMPLES=ON -DPAHO_WITH_SSL=OFF -DPAHO_BUILD_STATIC=ON -DPAHO_MQTT_C_INCLUDE_DIRS=C:\Users\x\Documents\github\paho.mqtt.c\paho.mqtt.c\src -DPAHO_MQTT_C_LIBRARIES=C:/Users/x/Documents/libraries/paho.mqtt.c/src/Debug/paho-mqtt3a.lib

rem STATIC - Breaking
rem cmake -Bbuild -H. -DCMAKE_CONFIG_TYPES=Debug -DCMAKE_INSTALL_PREFIX=C:\Users\x\Documents\libraries\paho.mqtt.cpp -DPAHO_BUILD_SAMPLES=ON -DPAHO_WITH_SSL=OFF -DPAHO_BUILD_STATIC=ON -DPAHO_MQTT_C_INCLUDE_DIRS=C:\Users\x\Documents\github\paho.mqtt.c\paho.mqtt.c\src -DPAHO_MQTT_C_LIBRARIES=C:/Users/x/Documents/libraries/paho.mqtt.c/src/Debug/paho-mqtt3a-static.lib
```

**Comment by fpagliughi** [comment]
Sorry for the delay; I'm having trouble locating a working Windows PC!

But to clarify... You're creating the static C++ library in both cases. When you link to the Paho C DLL, it works? But when you link to the static Paho library, you get the problem?

**Comment by Laro88** [comment]
No problem @fpagliughi I am also not finding enough time for this issue.
Yes, it seems like the -static.lib version of paho.mqtt.c is breaking for some reason. The issue #341 in paho.mqq.c could be a clue to this behavior, but I am quite uncertain.

**Comment by leodario7** [comment]
Hello @Laro88 and @fpagliughi did you find any solutions for this behaviour?. I'm currently facing the same error:

`Connecting to server 'tcp://localhost:1883'...MQTT error [6]: Unknown error code 6`

This occurs when compiling Paho C library as static and linking the _paho-mqtt3a-static.lib_ in Windows 10, using Visual Studio 2017. As @fpagliughi said the when linking against _paho-mqtt3a.lib_ and copying the _.dll_, (.lib+.dll) the samples compiled correctly.

Is there any solution for static libraries?

**Comment by fpagliughi** [comment]
Fixes are being added to the C library. The release isn't out yet, but I will start testing soon to see if these problems are getting worked out.

**Comment by cheryF** [comment]
If you use paho as static lib, manual call the "MQTTAsync_global_init" function to initialization mutex handlers.

MQTTAsync_lock_mutex(NULL); -> error code 6

**Comment by fpagliughi** [comment]
I believe this was fixed long ago. If not, please re-open.
