### ISSUE TITLE
mqtt::make_message type safety

### ISSUE THREAD

**Issue by thoism** [eclipse/paho.mqtt.cpp#175]
Could the qos and retained become enum classes or wrapper classes so that `mqtt::make_message `becomes safer? 

> Item 18: Make interfaces easy to use correctly and hard to use incorrectly.
Effective C++

Thank you

**Comment by fpagliughi** [comment]
The 'retained' flag is logically a boolean, and as there are only the two values of _true_ and _false_ that are both valid, I don't see that would ever change.

The QoS only has three legal values, so it would be safer to make it an enumeration. The original API was based on the Java version for compatibility across languages, and Java used an int. At this point, for the minor increase in safety, there would be a lot of existing code that would get broken! 

Either way, as a breaking change, it would require waiting until the next major version. But we can keep it on the list of things to consider then we do consider updating the API.

**Comment by thoism** [comment]
Thank you for your comments. Even if I agree on the `retained` flag being logically a boolean I still believe that a class enum would make the API clearer and eliminate any misuse.

BTW we are heavily using the paho.mqtt.cpp project and thank you for that.

**Comment by fpagliughi** [comment]
This may be reconsidered on a future major upgrade (i.e. v2.0) but for now, the API is set.
