### ISSUE TITLE
does it exist as ubuntu package

### ISSUE THREAD

**Issue by d01010101** [eclipse/paho.mqtt.cpp#178]
I browsed every ubuntu 18 package which had mqtt mosquitto paho installed everything which looked sensible still no mqtt/async_client.h does the respective package exist in ubuntu?

**Comment by frank-metal** [comment]
No, I don't believe that anyone has made this into a Debian/Ubuntu package. At least not that I've heard about.

**Comment by cayegara** [comment]
Is there any option to run it in Ubuntu ? I have the same issue with the mqtt/async_client.h

**Comment by d01010101** [comment]
I compiled from source, works without problem.

**Comment by fpagliughi** [comment]
Yes. Compile from source. The instructions are in the README. Ubuntu is well tested on a variety of x86 and ARM targets.

**Comment by cayegara** [comment]
I am using ubuntu 12_04. Can't update the version. Readme or other document said it works on v 14 and forward. But does it work in 12 too? 
Ps: Still not compiling the code.

**Comment by fpagliughi** [comment]
Ubuntu 12.04 is several years past End-of-Life, and I don't have it on any of my machines anymore, and am not testing it. That said, I can't think of any particular reason why the library _wouldn't run_ on 12.04 if you have the proper tools to build it. The current version requires CMake 3.5 and probably GCC v4.9 or above.

If you have a particular failure, post it here and we can see if we can figure it out.

**Comment by cayegara** [comment]
Finally I was able to compile from source, and now I dont know how to run a test file to start working on this project. I think that a step by step tutorial would be very interesting to new users like me. 
Thanks for the past answers.

**Comment by fpagliughi** [comment]
This is an un-funded open-source project. Pull requests are always welcome :-)
