### ISSUE TITLE
Avoid capitalizing constants

### ISSUE THREAD

**Issue by freanux** [eclipse/paho.mqtt.cpp#183]
Capitalizing constants is very evil due to conflicts with macros with same names.

https://github.com/eclipse/paho.mqtt.cpp/blob/9d53436f979abbb70821f410b1a5f207b682b072/src/mqtt/async_client.h#L48-L52

Using paho.mqtt.cpp in an own project, which will be built with GNU build system will fail, because the GNU build system injects `VERSION` as a define in the g++ command line. It leads into this:

```
<command-line>:0:9: error: expected unqualified-id before string constant
```

Please change these constants to `Version`, `Version_Str` and `Copyright` or to something similar. But do not use capitalized names.

**Comment by fpagliughi** [comment]
Don't be silly. Constants aren't evil. Macros are evil!  :-)

**Comment by fpagliughi** [comment]
What build system is giving you trouble?  We had been using Autotools and Make for years, but are abandoning them for CMake now.

**Comment by freanux** [comment]
> Don't be silly. Constants aren't evil. Macros are evil! :-)

I do not say constants are evil, but constants in capital letters are though. ;-)

My projects are using GNU build tools. (https://www.gnu.org/software/automake/manual/html_node/GNU-Build-System.html) The autoconf  `AC_INIT` macro appends the `-DVERSION` macro to the g++ command line, which leads to the mentioned conflict. And unfortunately, without the `AC_INIT`, the configure script won't work.

**Comment by freanux** [comment]
To give a specific example: I'm not able to `#include <mqtt/client.h>` in my cpp files with the use of autoconf for my project.

**Comment by fpagliughi** [comment]
Yeah, weird that it's never come up in the years of this project., even in my own use - not necessarily from Autotools, but from some other library header that defined VERSION as a macro. I use capitalization for constants across millions of lines of code, but I have long since learned not to use generic names like VERSION for just this reason.

Unfortunately, these constants are part of the public API and renaming them would be a breaking change, which can't be done until until the next major version, 2.0. That probably won't be on the roadmap for a while.

**Comment by freanux** [comment]
Okay, I see. Currently, for my purpose, I have to patch your source:
```
diff --git a/src/mqtt/async_client.h b/src/mqtt/async_client.h
index 2754690..0b9893f 100644
--- a/src/mqtt/async_client.h
+++ b/src/mqtt/async_client.h
@@ -45,11 +45,11 @@
 namespace mqtt {

 /** The version number for the client library. */
-const uint32_t VERSION = 0x00090000;
+const uint32_t Version = 0x00090000;
 /** The version string for the client library  */
-const string VERSION_STR("Paho MQTT C++ (mqttpp) v. 0.9");
+const string Version_Str("Paho MQTT C++ (mqttpp) v. 0.9");
 /** Copyright notice for the client library */
-const string COPYRIGHT("Copyright (c) 2013-2017 Frank Pagliughi");
+const string Copyright("Copyright (c) 2013-2017 Frank Pagliughi");

 /////////////////////////////////////////////////////////////////////////////

```
It would be nice, if you can provide a build option to offer these constants in camel case representation.

**Comment by fpagliughi** [comment]
As a compromise, you can #define `PAHO_MQTTPP_VERSIONS` before including the header and it will prepend the names with `PAHO_MQTTPP_` which should prevent a name clash.

In a 2.0 version, these would become the names.

**Comment by freanux** [comment]
perfect. thank you.
