### ISSUE TITLE
Errors in connect() on arm

### ISSUE THREAD

**Issue by d01010101** [eclipse/paho.mqtt.cpp#184]
It is a c++ application which may use mqtt. If I crosscompile on armhf (beaglebone), I get
```
what():  MQTT error [-8]
```
directly in cmqtt::async_client.connect(). If I compile natively on armhf, I get 
```
Program received signal SIGBUS, Bus error.
0xb68652d2 in mqtt::connect_options::connect_options(mqtt::connect_options const&) () from /usr/local/lib/libpaho-mqttpp3.so.1
```
instead. This happens in an application which otherwise works on x86_64, and which works on arm, crosscompiled or not, if MQTT is disabled.

I wonder if I can verify what happens, or at least if there are any examples to run, which will tell if the library is correctly compiled.

**Comment by fpagliughi** [comment]
I was never able to recreate this error. I just tried a native build on an RPi2 running the Raspbian from July 2019 (Kernel 4.19.57-v7+).

The library comes with fairly good unit test coverage to indicate that it is working. If you build the Paho C++ library using the CMake option `-D PAHO_BUILD_TESTS=ON`, it will build the unit tests. You need both CppUnit and Catch2 for this.

We're currently switching over from CppUnit to Catch2 for a unit test framework, so unfortunately, at the moment, both sets of test exist and you need to run both for the full set of tests.

First you can run the Catch2 tests:
```
fmp@raspberrypi $  ./test/unit/unit_tests 
===============================================================================
All tests passed (131 assertions in 15 test cases)
```
And then you can run the CppUnit tests:
```
fmp@raspberrypi $ ./test/cppunit/paho-mqttpp-test 
................................................................................................................................................................................................................................

OK (224 tests)
```

Let us know if you resolved this.

**Comment by fpagliughi** [comment]
Closing from inactivity. Feel free to reopen if there's still an issue.
