### ISSUE TITLE
Return by reference persistence interface

### ISSUE THREAD

**Issue by scollon42** [eclipse/paho.mqtt.cpp#186]
Hi!

First I wanted to thank you for you hard work! Use paho.cpp helped me a lot in my work!
I have a question that might become an issue but I wanted to open a discussion about the iclient_persistence interface.
There is this abstract function declared [here](https://github.com/eclipse/paho.mqtt.cpp/blob/9d53436f979abbb70821f410b1a5f207b682b072/src/mqtt/iclient_persistence.h#L105) 
```cpp
	/**
	 * Returns a collection of keys in this persistent data store.
	 * @return A collection of strings representing the keys in the store.
	 */
	virtual const string_collection& keys() const =0;
```
And I was wondering, is there any reason here to enforce a return by reference ?
The only way I found to implement it (except having a member variable in my custom persistence class or creating a global variable) is to declare a local variable static inside my overrided function.
``` cpp
const string_collection& MyPersistedClass::keys() const {
    static string_collection persistedKeys;
    persistedKeys.clear();
    // ...
    return persistedKeys;
}
```
This way it can return a reference to a static variable and it's fine. But maybe returning a simple copy would be better ?
What do you think ? Maybe I'm missing something here :confused: 
Anyway, I'm really interested in external thoughts on this!

**Comment by fpagliughi** [comment]
Agreed. This was probably a mistake. In an initial example (with the pre-1.0 API) the keys were readily available, and it seemed that returning the reference was the efficient way to go. But subsequently, I've hit the same problem: when you don't have the keys available, which is almost always the case now that they're returned in a _string_collection_, then you're forced to maintain a separate, static copy.

Unfortunately, fixing it now would be a breaking API change. That needs to wait until v2.0 which is still a bit off in the distance.

**Comment by scollon42** [comment]
Sure! I understand, thanks for your reply! :+1: We miss some lifetime control in c++ like there is in rust :smile:

**Comment by fpagliughi** [comment]
I'll keep this open with a v2.0 milestone as a reminder.

**Comment by fpagliughi** [comment]
Actually, this seemed too stupid and broken to keep in the API, even if it's a (relatively minor) breaking change. Updated for v1.2
