### ISSUE TITLE
Building Paho.mqtt.cpp using Visual Studio 2013 and cmake

### ISSUE THREAD

**Issue by jopech13** [eclipse/paho.mqtt.cpp#189]
I have been trying for a bit to build the correct mqtt libraries for an existing c++ project which is using Visual Studio 2013 build tools and MDd/MD build configuration on a Windows machine. I managed to build MTd and MT libraries for x32 and x64 bit versions using cmake and Visual Studio 2017 as well as MDd and MD for 64 bit projects using cmake and VS2017. Now that I'm repeating the same steps using Visual Studio 2013 as the generator, it works for the c project, but as soon as I build the generated cpp solution, I get over 340 errors, none of which specifies a linking error or file not found due to incorrect path or library configurations. Is it possible to build the project for this configuration at all? Or is my VS2013 missing required components? 
As far as I could see, there are 8 different error codes repeated over and over again for different files. Some of the errors are listed below. 
Cheers,
Joe

	Error	1	error C2610: 'mqtt::buffer_ref<T>::buffer_ref(mqtt::buffer_ref<T> &&)' : is not a special member function which can be defaulted	c:\paho.mqtt.cpp\src\mqtt\buffer_ref.h	96	1	paho-cpp-objs
	Error	5	error C2144: syntax error : 'int' should be preceded by ';'	c:\paho.mqtt.cpp\src\mqtt\message.h	56	1	paho-cpp-objs
	Error	6	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	c:\paho.mqtt.cpp\src\mqtt\message.h	56	1	paho-cpp-objs
	Error	9	error C2086: 'int mqtt::message::constexpr' : redefinition	c:\paho.mqtt.cpp\src\mqtt\message.h	58	1	paho-cpp-objs
	Error	12	error C2597: illegal reference to non-static member 'mqtt::message::DFLT_QOS'	c:\paho.mqtt.cpp\src\mqtt\message.h	173	1	paho-cpp-objs
	Error	26	error C2440: 'default argument' : cannot convert from 'unknown' to 'int'	c:\paho.mqtt.cpp\src\mqtt\topic.h	66	1	paho-cpp-objs
	Error	181	error C2797: 'mqtt::string_collection::coll_': list initialization inside member initializer list or non-static data member initializer is not implemented	C:\paho.mqtt.cpp\src\string_collection.cpp	32	1	paho-cpp-objs
	Error	239	error C2264: 'mqtt::buffer_ref<char>::buffer_ref' : error in function definition or declaration; function not called	c:\paho.mqtt.cpp\src\mqtt\message.h	222	1	paho-cpp-objs
	Error	343	error MSB3073: The command "setlocal 
					cd C:\paho.mqtt.cpp\build\src  
					if %errorlevel% neq 0 goto :cmEnd   
					C:
					if %errorlevel% neq 0 goto :cmEnd  
					"C:\Program Files\CMake\bin\cmake.exe" -E __create_def C:/paho.mqtt.cpp/build/src/paho-mqttpp3.dir/Debug/exports.def C:/paho.mqtt.cpp/build/src/paho-mqttpp3.dir/Debug//objects.txt  
					if %errorlevel% neq 0 goto :cmEnd
					:cmEnd 
					endlocal & call :cmErrorLevel
					%errorlevel% & goto :cmDone
					:cmErrorLevel 
					exit /b %1 
					:cmDone
					if %errorlevel% neq 0 goto :VCEnd
					:VCEnd" exited with code 1.	 C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	127	5	paho-mqttpp3

**Comment by fpagliughi** [comment]
I can't remember if VS 2013 had good enough C++11 support to compile the Paho C++ library. It may not be possible to use that compiler. I vaguely remember that VS 2015 worked.

**Comment by jopech13** [comment]
Hi, thank you for your fast reply! I agree with you on that one, VS2013 is a bit outdated by now. Time to try and upgrade our project, I was hoping to be spared but no such luck for me. 
Cheers, Joe
