### ISSUE TITLE
Getting Error Code : -11 for paho client library version 3.1.1

### ISSUE THREAD

**Issue by lazy37** [eclipse/paho.mqtt.cpp#190]
When we publish data there is a call to function MQTTAsync_connect(),this function then throws an error code : -11 which is   MQTTASYNC_OPERATION_INCOMPLETE in header file. Message sending fails only for some records .And after throwing error connection breaks between server and client.

**Comment by fpagliughi** [comment]
Are you saying that this happens occasionally/inconsistently?

I just started getting an error in the Paho Rust client in which I don't get a success callback from the underlying C lib on a successful publish. Then later, when I timeout and do something else, I get an Error -11. I wonder if these issues are related. Look at:
https://github.com/eclipse/paho.mqtt.c/issues/657

Either way, turn on the logging for the C lib and re-run your app until you get the error and post the results here.

**Comment by lazy37** [comment]
Thanks for responding . No my issue is different .In my case  msg is not reaching to subscriber . In logs it is showing Bad mqtt packet type 2 . I will append logs for  failed message .

FAILED MESSAGE LOGS :
20190524 122411.464 37 Avissol -> PUBLISH msgid: 8 qos: 1 retained: 1 (0) payload: {"camp_amd": "N", "t
20190524 122411.464 37 Avissol <- PUBACK msgid: 0
20190524 122411.466 37 Avissol <- PUBCOMP msgid:0
20190524 122411.467 Bad MQTT packet, type 2
20190524 122411.467 37 Avissol <- PUBCOMP msgid:0
20190524 122411.467 37 Avissol -> DISCONNECT (0)

SUCCESS MESSAGE LOG :+1: 

20190524 122322.269 37 Avissol -> PUBLISH msgid: 2 qos: 1 retained: 1 (0) payload: {"camp_amd": "N", "t
20190524 122322.274 37 Avissol <- PUBACK msgid: 2

**Comment by lazy37** [comment]
payload for successfull Message : 
payload=> {"type": "DIAL-ENGINE", "phone_number": "5543545", "queue_id": "1", "trunk_name": "1098", "query": "AUTO-DIAL", "unique_id": "5543545", "list_id": "15", "phone_code": "", "camp_amd": "N", "user_name": "", "camp_trunk_dial": "PRIORITY", "account_code": "AD052420191244000002", "trunk_id": "20", "dial_code": "145", "trunk_type": "SIP", "camp_id": "4", "dial_prefix": "", "skill_name": "ENGLISH", "campaign_callerid": "", "dial_timeout": "60", "domain_id": "2", "lastdialphone": "phone1", "camp_recording": "Y"}
payload for Failed Message : 
payload=> {"camp_amd": "N", "phone_number": "645656", "trunk_id": "20", "campaign_callerid": "", "unique_id": "645656", "type": "DIAL-ENGINE", "queue_id": "1", "camp_trunk_dial": "PRIORITY", "account_code": "AD052420191301430002", "query": "AUTO-DIAL", "trunk_type": "SIP", "camp_recording": "Y", "lastdialphone": "phone1", "skill_name": "ENGLISH", "user_name": "", "list_id": "15", "trunk_name": "1098", "dial_code": "145", "phone_code": "", "camp_id": "4", "dial_prefix": "", "dial_timeout": "60", "domain_id": "2"}

I donot know why it is sending mqtt bad client packet for failed payload.

**Comment by fpagliughi** [comment]
Weird. It's claiming that the PUBACK has a different message ID number.

Does this happen consistently at the same point in the program? Or does it occur randomly?

**Comment by lazy37** [comment]
It is happening for this particular record only ,which I showed as failed message.
