### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by maxlein** [eclipse/paho.mqtt.cpp#191]
When monitoring some processes of mine, I recognized a slowly inreasing memory usage over time.   
So after quite some time of debugging, it looks like there is some sort of memory leak in the library.   
More specifically, memory increases only when I subscribe to a topic and messages are incoming.
In the PAHO C lib I dont see this leak.  

I added my test code, so you can try out. 
Let it run for a minute and memory usage should be up.  
 
The dummy_callback_listener does nothing with the message itself, just an empty callback.

`getMemoryUsage` gets its data from ` ifstream stat_stream("/proc/self/stat",ios_base::in);`
  
Hope you can help me out here.  
  
PAHO CPP VERSION "1.0.1"
PAHO C VERSION "1.3.0"  
Ubuntu 18.04

```  
   mqtt::connect_options connectOptions;

   std::unique_ptr<mqtt::async_client>asyncClient = std::make_unique<mqtt::async_client>( mqtt::SERVER_ADDRESS, "MemoryRawClientTests" );
   auto conntok = asyncClient->connect( connectOptions );
   conntok->wait();
   asyncClient->start_consuming();

   dummy_callback_listener callbackListener;
   asyncClient->set_callback(callbackListener);

   dummy_action_listener listener;
   asyncClient->subscribe(mqtt::SERVER_TOPIC, 0, nullptr, listener);

   std::string payload = "SimpleMessageCallbackTestSimpleMessageCallbackTestSimpleMessageCallbackTestSimpleMessageCallbackTestSimpleMessageCallbackTest";
   mqtt::message_ptr message = mqtt::make_message(mqtt::SERVER_TOPIC, payload.c_str(), payload.size());

   while (true)
   {
      asyncClient->publish(message);
      log_info("mem usage: {}", getMemoryUsageString() );
      std::this_thread::sleep_for(10ms);
   }
```

**Comment by fpagliughi** [comment]
The way Linux reports it's memory usage can be tricky due to the lazy way it manages free memory. A better solution would be to run the app through valgrind. That would better indicate if a leak was happening, and where it was.

**Comment by maxlein** [comment]
Yes I will try valgrind also, but as the app also crashed because of using all the available ram on my system, it looks like a leak ...

**Comment by maxlein** [comment]
Added some memleax tests:
2 Processes, one is just publishing, one is receiving.
I think the developers will be faster than me finding the culprit.  

[ReceivingResults.txt](https://github.com/eclipse/paho.mqtt.cpp/files/3219294/ReceivingResults.txt)
[PublishingResults.txt](https://github.com/eclipse/paho.mqtt.cpp/files/3219295/PublishingResults.txt)

**Comment by fpagliughi** [comment]
As reported by Petri Soininen on the paho-dev mailing list:

I'm suspecting that my paho.mqtt.cpp client is not freeing memory of subscribed messages. I modified slightly the sample code paho.mqtt.cpp/src/samples/sync_subscribe.cpp;

First modification: Using qos = 0, should not matter here, perhaps:
    const int QOS = 0;
    ---
    const int QOS = 1;

The second modification: Subscribe in "void connected()" did not work for me, therefore added "cli.subscribe(TOPIC, QOS);" into the main loop after making sure that connection is on.

I'm sending large 1MB messages with 25 Hz. Memory increase used by the process can be seen very easily with this rate. Everything works just fine until all the system memory including swap is used :-)

For reference, paho.mqtt,.c client has been working for days without process memory grow with similar test setup.

System: Ubuntu 16.04 4.15.0, broker tested with RabbitMQ and Emqx, same result. Client paho.mqtt.cpp is 1.0.1 (9d53436).

Any tips for debugging? Do I miss some free() in my client?
See below some traces from valgrind commands as a starter.

BR, Petri

```
$ valgrind --tool=massif ./sync_subscribe # Here is the command for data collection, another client is publishing 1MB messages with 25 Hz
...
$ grep mem_heap_B massif.out.<pid of the previous> # Grepping some suspicious memory usage
mem_heap_B=0
mem_heap_B=9311263
mem_heap_B=15312373
mem_heap_B=22313668
mem_heap_B=32315518
mem_heap_B=38317140
mem_heap_B=45318435
mem_heap_B=51319497
mem_heap_B=62321532
mem_heap_B=73324079
mem_heap_B=81325559
mem_heap_B=91327409
mem_heap_B=98329216
mem_heap_B=108331066
mem_heap_B=114332176  <<----------------- *)
mem_heap_B=120333286

Snapshot from massif.out:

#-----------
snapshot=14
#-----------
time=249949132
mem_heap_B=114332176 <<----------------- *)
mem_heap_extra_B=59496
mem_stacks_B=0
heap_tree=detailed
n2: 114332176 (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
 n2: 112000501 0x523A8DB: void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.26)
  n1: 112000112 0x4ED1221: void __gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::construct<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*&, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*&, unsigned long&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
   n1: 112000112 0x4ED1196: void std::allocator_traits<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::construct<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*&, unsigned long&>(std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*&, unsigned long&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
    n1: 112000112 0x4ED1103: std::_Sp_counted_ptr_inplace<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<char const*&, unsigned long&>(std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
     n1: 112000112 0x4ED0F9A: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&>(std::_Sp_make_shared_tag, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, char const*&, unsigned long&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
      n1: 112000112 0x4ED0E70: std::__shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&>(std::_Sp_make_shared_tag, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, char const*&, unsigned long&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
       n1: 112000112 0x4ED0DFF: std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::shared_ptr<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&>(std::_Sp_make_shared_tag, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, char const*&, unsigned long&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
        n1: 112000112 0x4ED0D0E: std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > std::allocate_shared<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&>(std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, char const*&, unsigned long&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
         n1: 112000112 0x4ED0BB2: std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > std::make_shared<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*&, unsigned long&>(char const*&, unsigned long&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
          n1: 112000112 0x4ED09B3: mqtt::buffer_ref<char>::buffer_ref(char const*, unsigned long) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
           n1: 112000112 0x4ED064D: mqtt::message::set_payload(void const*, unsigned long) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
            n1: 112000112 0x4ED0053: mqtt::message::message(mqtt::buffer_ref<char>, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
             n1: 112000112 0x4EC15FB: void __gnu_cxx::new_allocator<mqtt::message>::construct<mqtt::message, mqtt::buffer_ref<char>, MQTTAsync_message const&>(mqtt::message*, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
              n1: 112000112 0x4EC0663: void std::allocator_traits<std::allocator<mqtt::message> >::construct<mqtt::message, mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::allocator<mqtt::message>&, mqtt::message*, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
               n1: 112000112 0x4EBF497: std::_Sp_counted_ptr_inplace<mqtt::message, std::allocator<mqtt::message>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::allocator<mqtt::message>, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
                n1: 112000112 0x4EBDB3E: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<mqtt::message, std::allocator<mqtt::message>, mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::_Sp_make_shared_tag, mqtt::message*, std::allocator<mqtt::message> const&, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
                 n1: 112000112 0x4EBBD2E: std::__shared_ptr<mqtt::message, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<mqtt::message>, mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::_Sp_make_shared_tag, std::allocator<mqtt::message> const&, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
                  n1: 112000112 0x4EBA749: std::shared_ptr<mqtt::message>::shared_ptr<std::allocator<mqtt::message>, mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::_Sp_make_shared_tag, std::allocator<mqtt::message> const&, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
                   n1: 112000112 0x4EB8DCC: std::shared_ptr<mqtt::message> std::allocate_shared<mqtt::message, std::allocator<mqtt::message>, mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::allocator<mqtt::message> const&, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
                    n1: 112000112 0x4EB71E0: std::shared_ptr<mqtt::message> std::make_shared<mqtt::message, mqtt::buffer_ref<char>, MQTTAsync_message const&>(mqtt::buffer_ref<char>&&, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
                     n1: 112000112 0x4EB5838: mqtt::message::create(mqtt::buffer_ref<char>, MQTTAsync_message const&) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
                      n1: 112000112 0x4EB0F24: mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*) (in /usr/local/lib/libpaho-mqttpp3.so.1.0.1)
                       n1: 112000112 0x5AD1D27: MQTTAsync_deliverMessage (in /usr/local/lib/libpaho-mqtt3as.so.1.3.0)
                        n1: 112000112 0x5AD2028: Protocol_processPublication (in /usr/local/lib/libpaho-mqtt3as.so.1.3.0)
                         n1: 112000112 0x5AD8D23: MQTTProtocol_handlePublishes (in /usr/local/lib/libpaho-mqtt3as.so.1.3.0)
                          n1: 112000112 0x5AD5452: MQTTAsync_cycle (in /usr/local/lib/libpaho-mqtt3as.so.1.3.0)
                           n1: 112000112 0x5AD0064: MQTTAsync_receiveThread (in /usr/local/lib/libpaho-mqtt3as.so.1.3.0)
                            n1: 112000112 0x674D6B8: start_thread (pthread_create.c:333)
                             n0: 112000112 0x57FC41B: clone (clone.S:109)
  n0: 389 in 13 places, all below massif's threshold (1.00%)
 n0: 2331675 in 42 places, all below massif's threshold (1.00%)
```

**Comment by fpagliughi** [comment]
I wonder if something is accumulating shared pointer references and not releasing them.

**Comment by soinipe** [comment]
Produced attached files log1.txt, log-control-c.txt, log3.txt and massif.out.12321 with following commands:
```
$ export G_SLICE=always-malloc
$ export G_DEBUG=gc-friendly
$ valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --show-leak-kinds=all --log-file=log1.txt ./sync_subscribe # Quit gracefully with 'q' from command line
$ valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --show-leak-kinds=all --log-file=log-$ control-c.txt ./sync_subscribe # With Control-C interrupt different trace
$ valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --show-leak-kinds=all --log-file=log3.txt ./sync_subscribe # Quit gracefully with 'q' from command line, different result type
& valgrind --tool=massif ./sync_subscribe # Produced massif.out.12321, tracking heap usage
```
Example client with my modifications is here: https://github.com/soinipe/paho.mqtt.cpp/blob/master/src/samples/sync_subscribe.cpp

Logs:
[logs-20180604.zip](https://github.com/eclipse/paho.mqtt.cpp/files/3251943/logs-20180604.zip)

**Comment by soinipe** [comment]
Just throwing an idea, added some traces to `async_client.cpp`, like this:
```
int async_client::on_message_arrived(void* context, char* topicName, int topicLen,
									 MQTTAsync_message* msg)
{
	if (context) {
		async_client* cli = static_cast<async_client*>(context);
		callback* cb = cli->userCallback_;
		consumer_queue_type& que = cli->que_;

		if (cb || que) {
			fprintf(stderr, "%s: topic=%s, %d bytes\n", __PRETTY_FUNCTION__, topicName, msg->payloadlen);
			size_t len = (topicLen == 0) ? strlen(topicName) : size_t(topicLen);

			string topic(topicName, topicName+len);
			auto m = message::create(std::move(topic), *msg);

			if (cb)
				cb->message_arrived(m);

			if (que)
				que->put(m);

			fprintf(stderr, "%s: m.use_count=%ld, que.cap=%zu .size=%zu\n", __PRETTY_FUNCTION__, m.use_count(), que->capacity(), que->size());
		}
	}

	MQTTAsync_freeMessage(&msg);
	MQTTAsync_free(topicName);

	// TODO: Should the user code determine the return value?
	// The Java version does doesn't seem to...
	return to_int(true);
}
```
For me the `que->put(m);` is just causing the queue save all messages and I could not spot anybody emptying the queue, here is output from the test run:

```
$ valgrind --tool=massif src/samples/sync_subscribe 
==25735== Massif, a heap profiler
==25735== Copyright (C) 2003-2015, and GNU GPL'd, by Nicholas Nethercote
==25735== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==25735== Command: src/samples/sync_subscribe
==25735== 
Connecting to the MQTT server...
Connected: connect onSuccess called

OK
Subscribe done
static int mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*): topic=hello, 1000000 bytes
Received hello: 1000000 bytes
static int mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*): m.use_count=2, que.cap=18446744073709551615 .size=1
static int mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*): topic=hello, 1000000 bytes
Received hello: 1000000 bytes
static int mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*): m.use_count=2, que.cap=18446744073709551615 .size=2
static int mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*): topic=hello, 1000000 bytes
Received hello: 1000000 bytes
static int mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*): m.use_count=2, que.cap=18446744073709551615 .size=3
static int mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*): topic=hello, 1000000 bytes
Received hello: 1000000 bytes
static int mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*): m.use_count=2, que.cap=18446744073709551615 .size=4
static int mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*): topic=hello, 1000000 bytes
Received hello: 1000000 bytes
```
I wonder if client code (sync_subscribe.cpp) is responsible reading the queue?

In very short test there is no significant leak if I just comment out `que->put(m);` but not aware impact of the change, client seems happy to receive messages, though.

**Comment by fpagliughi** [comment]
@soinipe:  Ugh. Yeah. That's just a really bad sample app on my part. The synchronous _Client_  is queueing the messages, but the app is not reading the queue, and is rather hooking in to the callback to get and display messages. So the queue is growing without bounds inside the library!

The was the original way that the synchronous API got messages - through the callbacks - but this is not really synchronous. So the queue was built into the library, and the [sync_consume.cpp](https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/sync_consume.cpp) sample was added. It would have been better to replace the old sample app with the new one, rather than leave them both in there.

The synchronous client is just a convenience wrapper around _AsyncClient_, and I left a lot of the asynchronous functionality available to the wrapper, if desired. Now, it seems like it would be better to make sure the sync version can do everything it needs to do without resorting to callbacks or any other synchronous behaviour.

**Comment by fpagliughi** [comment]
But that doesn't explain why a publisher would be leaking, so this Issue is still open...

**Comment by fpagliughi** [comment]
@soinipe Apologies for bouncing this around, but as this appears to be a separate problem, I created a new Issue for it: #193.

**Comment by soinipe** [comment]
@fpagliughi, cheers, no worries. Reading loud & clear, for me async_subscribe.cpp should have been used as a pattern. Thanks for fast feedback!

**Comment by 4aimar** [comment]
Hi @fpagliughi, I noticed that in this memory leak sample app, there is a piece of code that is asyncClient->start_consuming();  
when start_consuming, all the messages which are published by the publisher will be stored into the internal queue.  
see the code snippets mentioned by @soinipe and the internal queue max capability is std::numeric_limites<size_type>::max()
after start_consuming() there should be consume_message() called, but in this sample, the messages are never consumed. Then the process will eat up all the memory.

**Comment by fpagliughi** [comment]
Yes, that's it!  This is, in fact, all the same problem!

@maxlein, sorry, I did not notice the call to *start_consuming()* in your code sample. As we went through above and in #193, you should not tell the client that you will be consuming messages from the queue if you want to receieve them in a callback. When you call *start_consuming()*, it tells the client to place all incoming messages into a queue for you to retrieve later. If you don't pull from the queue using one of the *consume_message()* methods, it will fill up.

Thanks, @4aimar.

**Comment by fpagliughi** [comment]
Yes, that's it!  This is, in fact, all the same problem!

@maxlein, sorry, I did not notice the call to *start_consuming()* in your code sample. As we went through above and in #193, you should not tell the client that you will be consuming messages from the queue if you want to receieve them in a callback. When you call *start_consuming()*, it tells the client to place all incoming messages into a queue for you to retrieve later. If you don't pull from the queue using one of the *consume_message()* methods, it will fill up.

Thanks, @4aimar.

**Comment by maxlein** [comment]
Thanks for the answer and help! Sorry my fault then. 
Wasn't that clear to me from the name of the function.

**Comment by fpagliughi** [comment]
My fault. It's relatively new functionality, not properly documented, and even one of the sample apps in the repo is incorrect. I'll get it cleaned up, as per #193

**Comment by wb2712** [comment]
> 使用以下命令生成附加文件 log1.txt、log-control-c.txt、log3.txt 和 massif.out.12321：
> 
> ```
> $ export G_SLICE=always-malloc
> $ export G_DEBUG=gc-friendly
> $ valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --show-leak-kinds=all --log-file=log1.txt ./sync_subscribe # Quit gracefully with 'q' from command line
> $ valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --show-leak-kinds=all --log-file=log-$ control-c.txt ./sync_subscribe # With Control-C interrupt different trace
> $ valgrind -v --tool=memcheck --leak-check=full --num-callers=40 --show-leak-kinds=all --log-file=log3.txt ./sync_subscribe # Quit gracefully with 'q' from command line, different result type
> & valgrind --tool=massif ./sync_subscribe # Produced massif.out.12321, tracking heap usage
> ```
> 
> 我修改过的示例客户端在这里：https://github.com/soinipe/paho.mqtt.cpp/blob/master/src/samples/sync_subscribe.cpp
> 
> 还有另一个客户端发布数据——泄漏率与发布和订阅消息的大小成正比。
> 
> 日志： [logs-20180604.zip](https://github.com/eclipse/paho.mqtt.cpp/files/3251943/logs-20180604.zip)

Is this problem solved? I had the same problem and checked with the same tool as you
