### ISSUE TITLE
More details on thread safety

### ISSUE THREAD

**Issue by landersson** [eclipse/paho.mqtt.cpp#200]
I'm trying to debug some code that seem to deadlock when calling publish and subscribe simultaneously from two different threads, using the same mqtt::client class. "publish" seem to hang forever when "subscribe" is being called from another thread while the "publish" call is in progress.

Should it be OK to call publish and subscribe simultaneously from two different threads?

**Comment by fpagliughi** [comment]
That shouldn’t be a problem as long as you’re not invoking either of those from within a callback from the library.

Can you show some code or create a minimal example that exhibits this behavior?

**Comment by landersson** [comment]
After digging into this a bit further, concurrent access doesn't seem to be the problem. That was just my first guess due to the random nature of the error. What happens is that publish occasionally (maybe 1 in 20 times) just times out, and I get a delivery notification with returncode MQTTASYNC_OPERATION_INCOMPLETE.

I'm using the blocking mqtt:client class with the mosquitto broker. Both broker and client are running on my local Linux machine. I will try to recreate the issue in a minimal example.

Anyway, good to know that the mqtt::client class should be able to handle concurrent access.

**Comment by landersson** [comment]
I'll close this and have reopened a more relevant issue as #201.
