### ISSUE TITLE
MQTTASYNC_OPERATION_INCOMPLETE.

### ISSUE THREAD

**Issue by landersson** [eclipse/paho.mqtt.cpp#201]
I'm debugging some code that every now and then times out when trying to publish a message using mqtt::client. The message does seem to arrive at the broker (mosquitto) which sends an ACK, but this ACK is somehow lost, publish times out, and I get a delivery complete callback with return code -11, MQTTASYNC_OPERATION_INCOMPLETE.

Here's a snippet of code that can reproduce the issue for me.

https://gist.github.com/landersson/29d4f2449bef1ab5e98235a2981ec4bc

Every now and then, I'm getting:
```
Connected to MQTT broker: 'connect onSuccess called'
Connect finished
MqttConnection::Transmit, client_id=TEST
MQTT message delivered, msgId:1 returnCode:-11
```
It can take quite a few attempts before the timeout error occurs. Most of the time it works as expected. I'm testing using the latest versions of paho.mqtt.c and paho.mqtt.cpp. This happens both on an ancient Ubuntu 14.04 running in a VM and on my regular x86_64 Ubuntu 19.04.

I'm using mosquitto as a broker on 127.0.0.1:20000.

Could this be related to #190? Was that issue ever resolved?

**Comment by landersson** [comment]
The root cause of this issue seem to be this:

https://github.com/eclipse/paho.mqtt.c/issues/657

**Comment by fpagliughi** [comment]
It appears that this was fixed in the underlying C library.
