### ISSUE TITLE
Failing to Correctly Link W/SSL for Arch Linux (-13 error when running)

### ISSUE THREAD

**Issue by kmiller15211** [eclipse/paho.mqtt.cpp#203]
Hello, 
I can correctly build and link vs MqttCpp, but when I run, I get the -13 error, which seems to indicate an error with my SSL configuration. 

Disclaimer: I'm relatively new to CMake, so I apologize if this is a head slapping mistake on my part. 

I'm trying to build with CMake on ArchLinux, targeting a desktop build (for now, ultimately trying to get it to build for our mobile device). I'm building on a centralized build machine, which means that I have to customize the install paths to ones local to my environment, as I do not have full folder access. 

# Building Paho C

Here's my build command for Paho C: 
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DPAHO_BUILD_SAMPLES=TRUE -DPAHO_WITH_SSL=TRUE -DCMAKE_TOOLCHAIN_FILE=/opt/lifevest/4.9.11-1.0.0/toolchain-x86_64.cmake ..
```
which yields: 
```
-- The C compiler identification is GNU 8.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake version: 3.11.3
-- CMake system name: Linux
-- Timestamp is 2019-07-24T13:02:30Z
-- OpenSSL hints:
-- OpenSSL headers found at /usr/include
-- OpenSSL library found at /lib/libssl.so
-- OpenSSL Crypto library found at /lib/libcrypto.so
-- OpenSSL hints:
-- OpenSSL headers found at /usr/include
```
(I should note our x86 toolchain simply sets the find root path: 
```SET(CMAKE_FIND_ROOT_PATH "$ENV{HOME}/.oelocal/${CMAKE_HOST_SYSTEM_PROCESSOR}"))```

And my make step:  
```
DESTDIR="/home/kmiller/.oelocal/x86_64" make install
```

which builds and then installs both non-"s" versions and "s" versions, here's a snippet: 
```
-- Installing: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3cs.so.1.3.0
-- Installing: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3cs.so.1
-- Installing: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3cs.so
-- Installing: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3as.so.1.3.0
-- Installing: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3as.so.1
-- Installing: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3as.so
```

# Building Paho Cpp
When switching to the cpp library, I use the following cmake command: 
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DPAHO_BUILD_SAMPLES=TRUE -DPAHO_BUILD_TESTS=TRUE -DPAHO_WITH_SSL=TRUE -DCMAKE_TOOLCHAIN_FILE=/opt/lifevest/4.9.11-1.0.0/toolchain-x86_64.cmake ..
```

And, this finds the correct "s" version of Paho c, so everything looks good:
```
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.0h")
-- Found PahoMqttC: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3as.so
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
KCM - building with SSL
```

I also put a little debug into src/CMakeLists.txt to ensure that PAHO_WITH_SSL is set correctly, which it is, as you can see by my "KCM" message that comes out. 

Next, I make with the same command that I used for the C one, simply setting DESTDIR and doing make install. This all looks correct. 

```
...
-- Installing: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqttpp3.so.1.0.1
-- Up-to-date: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqttpp3.so.1
-- Up-to-date: /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqttpp3.so
-- Set runtime path of "/home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqttpp3.so.1.0.1" to ""
...
```

Now, if I ldd this .so, it does show it linking against the "s" version. Still looks good: 
```
$  ldd /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqttpp3.so
        linux-vdso.so.1 (0x00007ffd03375000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007feb22590000)
        libpaho-mqtt3as.so.1 => not found
        libm.so.6 => /usr/lib/libm.so.6 (0x00007feb221fb000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007feb21e3f000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007feb22be3000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007feb21c27000)
```

# My application
I then link Paho into a static library, and then that static library is ultimately linked into my test executable. Both binaries link as such: 

```
target_link_libraries(${LIBRARY_NAME}
                      PUBLIC
                          ...
                      PRIVATE
                          ...
                          PahoMqttCpp::paho-mqttpp3
                      )
```

If I take the ldd of my test executable, it appears to be using the wrong version of the library: 
```
        libpaho-mqttpp3.so.1 => /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqttpp3.so.1 (0x00007f25c1877000)
        libpaho-mqtt3a.so.1 => /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3a.so.1 (0x00007f25c15ad000)
```

I don't see anywhere in Paho where the samples are specifying anything regarding SSL in terms of the library linkage, PAHO_CPP_LIB looks to simply be a static or shared library. How can I make my library use the SSL version of Paho? 

Thank you in advance!

**Comment by kmiller15211** [comment]
I should clarify that my test application ldd line does show a linkage against the "as" version of Paho C further down the line:
```
 zlv5000dev  ~/GitLab/hot-metal2/lifevest-app/cmake-build-debug_host/modules/data-management/test/standalone-iot-xmit-test  feature/iot-connection-cleanup  $  ldd standalone-iot-xmit-test | grep paho
        libpaho-mqttpp3.so.1 => /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqttpp3.so.1 (0x00007f43a3db8000)
        libpaho-mqtt3a.so.1 => /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3a.so.1 (0x00007f43a3aee000)
        libpaho-mqtt3as.so.1 => /home/kmiller/.oelocal/x86_64/usr/lib64/libpaho-mqtt3as.so.1 (0x00007f439fba4000)

```

**Comment by fpagliughi** [comment]
The C library compiles several different versions of sync/async, SSL/non-SSL. The C++ library only creates one library. If you tell it to use SSL, that library uses SSL, and should link against the SSL-version of the C lib ("paho-mqtt3as").

The C++ library doesn't care about SSL; it doesn't directly talk to OpenSSL. It passes all this stuff to the C lib. If you ask for a secure connection, and you're linked to the non-SSL C lib, you get an error -13.

The -13 error means that the call to connect() is going into the non-SSL version of the C library.

So don't worry about certificates or anything like that yet. This is a linker problem. I wonder why your app is linked to both versions of the C lib. That seems to be the problem. If I look at one of the library sample apps, I see:
```
$ ldd src/samples/async_publish | grep paho
	libpaho-mqttpp3.so.1 => /home/fmp/mqtt/paho-mqttpp/build/src/libpaho-mqttpp3.so.1 (0x00007f4faa35e000)
	libpaho-mqtt3as.so.1 => /home/fmp/mqtt/paho.mqtt.c/build/_install/usr/local/lib/libpaho-mqtt3as.so.1 (0x00007f4faa08e000)
```
So I'm linked to the C++ lib and the secure version of the C lib (only).

**Comment by fpagliughi** [comment]
As a weird sanity check, maybe try deleting the non-SSL C libraries off your system, then try rebuilding your app. Would it complain about not finding the lib or just find the right one? Hmm.

**Comment by nkowdley** [comment]
@fpagliughi  I am seeing the same issue -- when running make install, it installs both versions of the PahoMQTT C library.  Is this normal?

**Comment by kmiller15211** [comment]
Thank you for the prompt response! 

When I remove the C libs, it fails with error "Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)"

I also touched the FindPahoMqttC.cmake file to add some debug, it appears to be not correctly getting the PAHO_WITH_SSL parameter. I'm thinking that's my issue, that's not correctly getting from my cmakes down to Paho's build ones. 

```
if(PAHO_WITH_SSL)
    message("KCM - in paho MqttCppTargets -and doing SSL")
    set(_PAHO_MQTT_C_LIB_NAME paho-mqtt3as)
    find_package(OpenSSL REQUIRED)
else()
    message("KCM - in paho MqttCppTargets -NO SSL")
    set(_PAHO_MQTT_C_LIB_NAME paho-mqtt3a)
endif()
```

When I reload my Cmake files, I see that it's taking the non-ssl branch.

**Comment by fpagliughi** [comment]
@nkowdley Yes, I believe it's normal that the C lib builds both versions. I think it always builds the non-SSL version, and if you ask it to build the SSL one, it does that in addition to the other.

But an app using the C++ library should only be linking in one or the other depending on the CMake option `PAHO_WITH_SSL`. It should not be linking in both libraries.

**Comment by kmiller15211** [comment]
OK, this is just a CMake misunderstanding/oddity. I was trying to set PAHO_WITH_SSL from inside my cmake files, (with SET, among others) and it wasn't correctly propagating down into the Paho package, for some reason. 

However, a humble suggestion: The library indicates that SSL is on by default, but then, as client code, you have to do extra work to get the SSL version. Maybe it would be better to reverse the logic in the FindPahoMqttC.cmake file so that it uses the SSL linkage by default, and only if PAHO_WITH_SSL is set to false do you use the non-SSL one.

**Comment by fpagliughi** [comment]
Yeah, I'm a CMake novice as well. Most of the build code was donated by others. 

But I think that in the long run, I'd prefer for users of the C++ library to not have to know or care that there's a C library underneath.

In the Rust library, which is also a wrapper around Paho C,  I use a Git submodule for the C library, automatically compile it into a static lib as part of the Rust build, and link it into the Rust library without the user knowing or caring. It even cross-compiles seamlessly. 

I should figure out how to do that for the C++ library as well.

**Comment by fpagliughi** [comment]
Hey... maybe @vogoltsov already fixed this for us? There are a few CMake PR's from a few weeks back that I need to look at. This one seems to address the issue. Maybe?

Added OpenSSL as a transitive dependency to PahoMqttC::PahoMqttC target #198

**Comment by fpagliughi** [comment]
Assuming this was fixed long ago? If not, feel free to reopen.
