### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by MattiasEppler** [eclipse/paho.mqtt.cpp#207]
You write in README.md

Windows
Alternately, the libraries can be completely built at an MSBuild Command Prompt...
Then build the C++ library:

```
> cd ..\paho.mqtt.cpp
> cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\mqtt\paho-cpp -DPAHO_BUILD_SAMPLES=ON -DPAHO_WITH_SSL=OFF -DCMAKE_PREFIX_PATH=C:\mqtt\paho-c
> cmake --build build/ --target install
```

Should not be paho.mqtt.cpp and C:\mqtt\paho-cpp the same?

**Comment by fpagliughi** [comment]
I'm trying to get access to a Windows machine to start testing the new, upcoming release for MQTT v5. But if you believe you have a correction for this could you submit a Pull Request, even if it's just a little change to the README. Thanks,

**Comment by MarcoGrochowski** [comment]
I do not see an issue here and hence it can be considered closed as it doesn't matter where you install the target, does it @MattiasEppler? 
You can use any path you want for the -DCMAKE_INSTALL_PREFIX. The target will be installed at a default location, e.g. "C:/Program Files(x86)/paho-mqtt-cpp", in case you do not specify it.
Can you please specify your problem?

**Comment by fpagliughi** [comment]
Sorry for the delay. On a second look at the question, I'm not sure I understand what's being asked.

First, in the instructions, I'm assuming that people would want to install the libraries at a different place than the source/working directories, and that the Paho C and C++ libraries would be installed somewhere next to each other. 

Maybe it's a personal preference, but I tend not to put my development libraries under the "Program Files" directory, or anything like that. The space character in the directory name drives me nuts when working from the command line.

So I suggest installing the libraries in a tree like:
```
C:\
    mqtt\
        paho-c\
        paho-cpp\
```
When building, the line:
```
cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\mqtt\paho-cpp -DCMAKE_PREFIX_PATH=C:\mqtt\paho-c
```
says to use the directory `C:\mqtt\paho-c` when looking for the C library during the build, then place the C++ library in `C:\mqtt\paho-cpp` during the install.

I think that's all correct, no?

**Comment by MattiasEppler** [comment]
you change the directory to ".\paho.mqtt.cpp"
but in next line of the build the path is C:\mqtt\paho-cpp

"paho.mqtt.cpp" and "mqtt\paho-cpp", is not the same. But it should, or not?

**Comment by fpagliughi** [comment]
Well, no. I tend to keep my source directories separate from my binary install directories.

The `paho.mqtt.cpp` directory gets the source files from the GitHub repo, and becomes the local workspace. If you're just building the libraries, this can be a temporary directory, since you can build the libraries and then throw away the sources. If you're developing the code, this directory may be in with your documents, somewhere under C:\Users, or something like that.

The `C:\mqtt\paho-cpp` directory is where the library binaries (DLL's) and headers will be installed after they are built.

**Comment by fpagliughi** [comment]
I tested this again today. It is correct. The sources can be wherever you download them, but assuming that you use Git, they will be put into a directory, _paho.mqtt.cpp_, by default. The instructions have you build and install into directories under C:\mqtt.
