### ISSUE TITLE
[Suggestion] error text message in mqtt::exception?

### ISSUE THREAD

**Issue by guilhermeferreira** [eclipse/paho.mqtt.cpp#21]
What do you think about a text message, along with error code, in mqtt::exception?

`void token::on_failure(MQTTAsync_failureData* rsp)`
`{`
    `if (rsp) {`
`tok_ = rsp->token;`
`rc_ = rsp->code;`
`message_ = rsp->message;`
    `}`

`}`

**Comment by fpagliughi** [comment]
Yes, I would like to improve the exception classes, create a better heirarchy of exception types, and add better information.
