### ISSUE TITLE
Mqtt error: ‘client’ is not a member of ‘mqtt’

### ISSUE THREAD

**Issue by SoumenKunduTantra** [eclipse/paho.mqtt.cpp#214]
I am writing code for mqtt. I used below link and written code and compiling the code in Raspberry Pi.
**gcc version 8.1.0 (GCC)**  

https://www.eclipse.org/paho/clients/cpp/#

But I am getting following error 

> mqtt-cpp.cpp: In function ‘int main()’:
> mqtt-cpp.cpp:19:8: error: ‘client’ is not a member of ‘mqtt’
>   mqtt::client cli("tcp://192.168.1.101:1883", "C++ Client Sync");
>         ^~~~~~
> mqtt-cpp.cpp:28:3: error: ‘cli’ was not declared in this scope
>    cli.connect(connOpts);
>    ^~~

**mqtt-cpp.cpp** is my program file.

 **g++ mqtt-cpp.cpp -o mqtt-cpp**  is my compile command in Raspberry Pi.

I also tried following command to compile program. But I am getting the same error given above.

> g++ mqtt-cpp.cpp -o mqtt-cpp  -lpaho-mqtt3c
> g++ mqtt-cpp.cpp -o mqtt-cpp -lmqttpp -L lib -I src -lpthread -std=c++11
> g++ mqtt-cpp.cpp -lmqttpp -L lib -I src -lpthread -std=c++11

Below is the code I wrote:

> #include "mqtt/async_client.h"
> 
> 
> int main()
> {
>      const std::string TOPIC{ "outbox" };
> 	const std::string PAYLOAD1{ "Hello World!!!, from C++" };
> 
> 	const char* PAYLOAD2 = "Hi there!";
> 
> 	// Create a client
> 
> 	mqtt::client cli("tcp://192.168.1.101:1883", "C++ Client Sync");
> 
> 	mqtt::connect_options connOpts;
> 	connOpts.set_keep_alive_interval(20);
> 	connOpts.set_clean_session(true);
> 
> 	try {
> 		// Connect to the client
> 
> 		cli.connect(connOpts);
> 
> 		// Publish using a message pointer.
> 
> 		auto msg = mqtt::make_message(TOPIC, PAYLOAD1);
> 		msg->set_qos(1);
> 
> 		cli.publish(msg);
> 
> 		// Now try with itemized publish.
> 
> 		cli.publish(TOPIC, PAYLOAD2, strlen(PAYLOAD2), 0, false);
> 
> 		// Disconnect
> 
> 		cli.disconnect();
> 	}
> 	catch (const mqtt::exception& exc) {
> 		std::cerr << "Error: " << exc.what() << " ["
> 			<< exc.get_reason_code() << "]" << std::endl;
> 		return 1;
> 	} 
>     return 0;
> }

**Comment by SoumenKunduTantra** [comment]
@fpagliughi Thanks for your reply.
I tried sample code async_client.cpp in Raspberry Pi 3B.

https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/async_client.cpp

g++ async_publish.cpp -o  async_publish -lpaho-mqtt3as -lpaho-mqttpp3 is my compile command in Raspberry Pi.
It got compiled successfully. But when I run the executable file following error occurred.

`./async_publish: error while loading shared libraries: libpaho-mqttpp3.so.1: cannot open shared object file: No such file or directory`

I run the project in **sudo** also, still error continue.

**Comment by SoumenKunduTantra** [comment]
@fpagliughi Thanks for you reply.
I used sample code **async_client.cpp**  from the link given  below.

https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/async_client.cpp

I compiled the code successfully, below is the compile command.

`g++ async_publish.cpp -o async_publish -lpaho-mqttpp3 -lpaho-mqtt3as`

But when I am running it was giving following error.

`./async_publish: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /usr/local/lib/libpaho-mqttpp3.so.1)`

After getting above error  I copied the **libstdc++.so.6** to **/usr/local/lib/** as per one of the online solution.
But after doing this when I run the **async_publish**  it is giving below error.

`./async_publish: symbol lookup error: ./async_publish: undefined symbol: _ZN4mqtt7message13DFLT_RETAINEDE`

**Comment by tgill880** [comment]
Looks like the same problem I had.

Try
```
$ sudo ldconfig
```

**Comment by fpagliughi** [comment]
Actually this problem is a little different than #215, at least initially. But certainly run _ldconfig_, just in case. It won't hurt either way.

The err'r "CXXABI_1.3.11' not found" makes me think that maybe the compiler and the system libraries don't match. Maybe one is much older than the other. You mention GCC v8.1. It that the default compiler for the system? Or did you upgrade to that version?

**Comment by SoumenKunduTantra** [comment]
Thanks @tgill880 for your reply I already followed https://github.com/eclipse/paho.mqtt.cpp/issues/215 and gone through all the steps.

@fpagliughi I build and installed the GCC 8.1 in my Raspberry Pi.
I followed the below link to build the gcc.
https://solarianprogrammer.com/2017/12/07/raspberry-pi-raspbian-compiling-gcc/

**Comment by fpagliughi** [comment]
Is there a reason why you built your own compiler instead of using one of the many versions of the compilers available through the package manager? The latest Raspbian Buster comes with GCC v8.3 standard, and has v4.9, v5, v6, and v7 all available, not to mention clang v5, 6, 7 and 8.

If you're trying to build and deploy your own versions of GCC, that's beyond the help I can give you with installing Paho.

**Comment by SoumenKunduTantra** [comment]
We are using latest STL features for our project available in C++17, so we need GCC 8. But Raspberry Pi Model 3B with Raspbain OS does not have GCC 8 in apt-get. 
So I manually build and installed in my Raspberry Pi.

**Comment by fpagliughi** [comment]
Have another look. I just loaded the latest Raspbian Buster on an RPi 2 over the weekend, and it has GCC 8.3, and several versions of clang that claim full C++17 support. That might help save some time.

As a very simple test, your compiler should be able to build and run a basic thread test app like the following:

```
#include <iostream>
#include <thread>

using namespace std;

void thr_func()
{
    cout << "Hello from the thread!" << endl;
}

int main()
{
    thread thr(thr_func);
    thr.join();
    return 0;
}
```

If you can compile and run that, then you have a pretty good idea that the compiler is properly built and installed.

**Comment by SoumenKunduTantra** [comment]
I created a **test.cpp** file and pasted your above given code.

```
#include <iostream>
#include <thread>

using namespace std;

void thr_func()
{
    cout << "Hello from the thread!" << endl;
}

int main()
{
    thread thr(thr_func);
    thr.join();
    return 0;
}
```

It got compiled successfully. Below is my compile command.
**`g++ -pthread test.cpp -o test`**

And also run without any issue. 
`./test`

Output:
`Hello from the thread!`

**Comment by SoumenKunduTantra** [comment]
Thanks Frank(@fpagliughi) for your kindly support on my issue. I installed Raspbian Buster in my Raspberry 3B+ and tried async_client.cpp in it using GCC8.3. It got successfully compiled and run.
