### ISSUE TITLE
g++ complains with multiple definition of static constexpr in mqtt::message

### ISSUE THREAD

**Issue by ropieur** [eclipse/paho.mqtt.cpp#216]
Hi,

when calling mqtt::make_message overload without qos and retained flag, the linker complains with error messages

libpaho-mqttpp3.a(message.cpp.o):(.rodata+0x24): multiple definition of `mqtt::message::DFLT_QOS'
libexecutables_mqtt_pub_src_main.a(MqttClientTest.cpp.o):(.rodata._ZN4mqtt7message8DFLT_QOSE[_ZN4mqtt7message8DFLT_QOSE]+0x0): first defined here
libpaho-mqttpp3.a(message.cpp.o):(.rodata+0x28): multiple definition of `mqtt::message::DFLT_RETAINED'
libexecutables_mqtt_pub_src_main.a(MqttClientTest.cpp.o):(.rodata._ZN4mqtt7message13DFLT_RETAINEDE[_ZN4mqtt7message13DFLT_RETAINEDE]+0x0): first defined here
collect2: error: ld returned 1 exit status

When calling mqtt::make_message by explicitly specifying qos and retained flag, those errors go away.

Not sure whether there is a library issue or whether I am doing something wrong

FYI, I built the library with g++ 7.4.0 under ubuntu 18.04 and install it locally (no default install) using the following defines
-DPAHO_WITH_SSL=FALSE -DPAHO_BUILD_STATIC=TRUE
-DCMAKE_CXX_FLAGS=-std=c++17 -pedantic-errors
-DCMAKE_PREFIX_PATH=.<local-path-paho-mqtt-c library>
-DCMAKE_INSTALL_PREFIX=<local-path-install directory>

Thank you

**Comment by fpagliughi** [comment]
Hmm. That's my default development system at the moment (actually Mint 19, but essentially the same thing), and I haven't seen any issues. I haven't tried compiling with C++ 17 enabled, though I hope that wouldn't cause an issue.

**Comment by fpagliughi** [comment]
Ah, OK. This had come up in #161 and #162.

Apparently, from C++17 and beyond, `static constexpr` used for a member variable implies that it is `inline`. But this wasn't true prior to 17. 

So, as sent in #162, some conditional compilation in the library around the version is probably the right solution. But, as usual with C++, all the compilers seem to be dealing with this differently!

**Comment by fpagliughi** [comment]
I believe this fixed it: 53d71e7354bc543974b80f4bca668be2beace0c8

If not, pleas re-open the issue.

**Comment by marcusl** [comment]
I'm using 1.2.0 from conan on Ubuntu 20.04 and I am getting this too.

**Comment by mrscarletzhou** [comment]
Same issue on ubuntu 18.04 / gcc 7.8.0.
`
/usr/local/lib/libpaho-mqttpp3.a(message.cpp.o):(.rodata+0x30): multiple definition of `mqtt::message::DFLT_QOS'
/tmp/cc7cGz48.o:(.rodata._ZN4mqtt7message8DFLT_QOSE[_ZN4mqtt7message8DFLT_QOSE]+0x0): first defined here
/usr/local/lib/libpaho-mqttpp3.a(message.cpp.o):(.rodata+0x34): multiple definition of `mqtt::message::DFLT_RETAINED'
/tmp/cc7cGz48.o:(.rodata._ZN4mqtt7message13DFLT_RETAINEDE[_ZN4mqtt7message13DFLT_RETAINEDE]+0x0): first defined here
collect2: error: ld returned 1 exit status
`

**Comment by xkszltl** [comment]
This discussion may be helpful:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=101957

**Comment by KammutierSpule** [comment]
Still got this issue on development branch
