### ISSUE TITLE
The best way to read/write lot's of topics into one program

### ISSUE THREAD

**Issue by KrYpToDeN** [eclipse/paho.mqtt.cpp#217]
Hello.

I need to subscribe and after it i need to publish into lot's of topics.

For example:
I have topics test/0, test/1,...,test/1000.
I need all time read it (subscribe function) and when i got some new info, i should publish this info into another topic. Probably - answ_test/0...answ_test/1000.

Could you tell me, please, the best way to release it?

I know, that i should use asynce version.
Should i add my own threads for every sunbscribe and so on.

I would like to know the best algoritm to do it all.

Thank you.

**Comment by fpagliughi** [comment]
I'm sorry; I'm not sure that I understand the question. But here are a few things that might help.

For a single client, all the incoming messages from all the topics will arrive on a single thread inside the library which will then call your registered _message_arrived_ callback.

You can publish an asynchronous message from the callback, but you _must not block_ the thread, so you can't wait on the token for a response.

The other option, which might actually make even more sense is to us the "consume" functionality. If you use the synchronous `client` or you use the `async_client` and call `start_consuming()` then the client will register its own callback function to handle incoming messages. It will simply place each message into a thread-safe queue, and then you can handle the messages in your own thread. In this case it is only important that, _on average_, you process the messages faster than they arrive. So you can create more threads, if needed to process the messages. 

In general, it's something like:
```
while (true) {
    auto msg = cli.consume_message();
    if (!msg) break;

    // Use msg->get_topic() and msg->get_payload()
    // to process

    cli->publish("some/topic", "some new payload");
}

**Comment by KrYpToDeN** [comment]
> I'm sorry; I'm not sure that I understand the question. But here are a few things that might help.
> 
> For a single client, all the incoming messages from all the topics will arrive on a single thread inside the library which will then call your registered _message_arrived_ callback.
> 
> You can publish an asynchronous message from the callback, but you _must not block_ the thread, so you can't wait on the token for a response.
> 
> The other option, which might actually make even more sense is to us the "consume" functionality. If you use the synchronous `client` or you use the `async_client` and call `start_consuming()` then the client will register its own callback function to handle incoming messages. It will simply place each message into a thread-safe queue, and then you can handle the messages in your own thread. In this case it is only important that, _on average_, you process the messages faster than they arrive. So you can create more threads, if needed to process the messages.
> 
> In general, it's something like:
> 
> ```
> while (true) {
>     auto msg = cli.consume_message();
>     if (!msg) break;
> 
>     // Use msg->get_topic() and msg->get_payload()
>     // to process
> 
>     cli->publish("some/topic", "some new payload");
> }
> ```

Hello, thank you for your answer.
But if i would like to user multiple clients?

Such as, this situation:
There are 1000 users (mobile phones), who publish some data into user's topics (User_1, User2,...,User1000). They can publish it any way (soft, web, and so on).

My work - write a program, which can process user's incoming messages.
So, We have some users and one program on Linux, which should process it. 

Into our program can arrive 1000 different topics from our users.
We should read it in online, do something with messages (probable rewrite to another system topics).
Something such as client-server topic's messanger.

How can i do in this situation?

**Comment by fpagliughi** [comment]
Yes, this is _exactly_ what messaging systems like MQTT were made for.

Each user would publish to a specific topic, like "users/user1", "users/user2", etc.

Your Linux server application could get messages from all the clients with one subscription, using a wildcard:
```
cli.subscribe("users/#", QOS);
```

Then, the little consumer loop I showed you would get _all the messages from all the users_. If you want, you can distinguish which user sent the message by looking at the topic of the incoming message:
```
if (msg->get_topic() == "users/user1") { /* then this came from user1 */ }
```

Any average server should be able to handle a few thousand messages per second, depending on what you need to do to process each message.

Typically, to scale out in a single app you would use something like a thread pool to service the messages, like:
```
while (true) {
    auto msg = cli.consume_message();
    if (!msg) break;
    pool.submit(msg);
}
```
The `msg` variable is a _std::shared_ptr_ so you can send it to different threads. It would be up to you to find or write the thread _pool_ class to manage this.

But if you're just getting a message, making a quick decision on where to re-route it, and then publishing it back out on another topic, you can probably manage that all in one thread, no problem.

My best suggestion would be to compile the library and sample apps and start making small modifications to try some ideas out. You should be able to get a quick prototype working and then gain a better understanding of how it all works.

Look at the samples in:
https://github.com/eclipse/paho.mqtt.cpp/tree/master/src/samples

particularly _sync_consume.cpp_, _async_consume.cpp_, and _async_subscribe.cpp_.

There's also a new sample in the master branch for MQTT v5 that shows a simple chat application (lots of users sending messages to each other). It's called _mqttpp_chat.cpp_.

**Comment by fpagliughi** [comment]
@KrYpToDeN Is this resolved to your satisfaction?

**Comment by fpagliughi** [comment]
No response
