### ISSUE TITLE
Detecting Publish Timeout

### ISSUE THREAD

**Issue by landersson** [eclipse/paho.mqtt.cpp#218]
I'm using the synchronous c++ client class, mqtt/client.h and want to detect when the publish method times out... Looking and the code for the publish methods, they are variants of this:

```
cli_.publish(std::move(top), payload, n, qos, retained)->wait_for(timeout_);
```
where wait_for returns a boolean that is 'false' if the publish times out. However, this boolean is not forwared up by the publish method in the sync client class, which returns void.

Is there any other way to detect if publish timed out?

**Comment by fpagliughi** [comment]
Oof. Yeah. That sounds like a crappy API. It sounds like either:
- The _publish_ should return a bool, with _false_ for timeout, or
- A timeout should throw an exception, like the other errors do.

**Comment by landersson** [comment]
Maybe generating an exception based on mqtt::exception would be the best solution, since a lot of code would already be catching and handling that?

**Comment by landersson** [comment]
Would you be interested in a PR attempting to add an exception when a publish times out?

**Comment by landersson** [comment]
This issue just hit me in a real world use case. It basically means that mqtt::client::publish() can silently fail to deliver a QoS > 0 message, without causing an exception. My code has been designed with the assumption that when using the synchronous client, if publish() doesn't cause an exception, the message has been delivered and a PUBACK successfully received. Have I been wrong to assume this, or can we count the current behavior (i.e sync publish returning w.o exception when timing out) as a bug? If yes, I would count that as a pretty serious, high priority bug.

**Comment by landersson** [comment]
I have implemented a fix by adding:

```
namespace mqtt {
class timeout_exception : public std::runtime_error
}
```
This gets thrown when wait_for() returns false in the various publish() methods. Seems to work well for me.

If would perhaps be better to have mqtt::timeout_exception derive from mqtt::exception by adding another custom ReasonCode, although that would add more special-case code along the lines of what is being done for MQTTPP_V3_CODE.

**Comment by fpagliughi** [comment]
Apologies for the really long delay on this. But it's finally in the new release, v1.2.0. _All_ of the `client` methods should throw a timeout exception when they do timeout. I believe I called it `timeout_error`.

**Comment by landersson** [comment]
Great, thanks!
