### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by cblack-f3** [eclipse/paho.mqtt.cpp#219]
2 issues:
* Add libssl-dev to apt-get install, as mqtt.c build requires
* Current version in instructions for mqtt.c is to checkout v1.2.1, which no longer works with HEAD of mqtt.cpp, update to instructions to checkout 1.3.1 of c, or update cpp build instructions to checkout a specific version that works with c 1.2.1

**Comment by cblack-f3** [comment]
One more: ldconfig at end of cpp build instructions

**Comment by fpagliughi** [comment]
Thanks. Some of this was already in the `develop` branch, but I will put the rest in and merge with master.
