### ISSUE TITLE
Default persistence behavior on crash?

### ISSUE THREAD

**Issue by TrevorMuraro** [eclipse/paho.mqtt.cpp#221]
I've been experimenting with Paho for use in an IoT project, but I've been having trouble figuring out exactly how the default on-disk persistence mechanism recovers in the event of a crash.

I've created a script as follows:

```
//Connect to server

if(client.is_connected())
{
    string msg1 = "{\"val1\": 2}";

    client.publish("topic", msg1.c_str(), msg1.length(), 1, false);
}

while(1){}

return 0;
```

By changing the message and commenting out either the publish or the while loop, I've observed an odd pattern of behavior:

* If I attempt to publish a message without the while loop (meaning the program quits before delivery finishes), the server receives the message and a file "s-1.msg" is created.
    * If I then open a connection and loop without publishing, nothing happens.
    * Alternatively, if I open a connection, publish and loop to allow messages to go through, the new message is received and "s-1.msg" disappears.  However, the on-delivery callback is only called once.
* If multiple publish attempts are made in the same run without allowing them to complete, this creates files "s-1.msg", "s-2.msg", etc., with all messages arriving at the server.  If I later open a connection, publish a single message and loop, "s-1.msg" disappears but the subsequent ones remain, and the on-delivery callback is still only called once.
* If I make one or more initial publish attempts without the while loop, then make no publish attempts but execute the while loop on the next run, then attempt to publish without the while loop on the third run, a file "c-1.msg" is created.  Sometimes, additional attempts will yield files "c-2.msg", etc.  I have never seen Paho clear these files, and these messages do not arrive at the server.

The only thing I can glean from this is that "s-*.msg" refers to a sent message with message ID *, and that these are not persisted over restarts - instead, counting starts at 1 again, and the new messages overwrite the old ones.  However, the use of the filesystem for persistence led me to suspect a crash-recovery mechanism of some sort, so now I'm rather confused.

I've looked around, but I couldn't find a description of the caching and recovery behavior of the default persistence mechanism.  Is there a reference somewhere?

**Comment by TrevorMuraro** [comment]
Alternatively, if there is no crash recovery, what cleanup should I be prepared to do in a worst-case scenario?

**Comment by fpagliughi** [comment]
Sorry I haven't had a chance to look into this. The default persistence is implemented in the underlying Paho C library, and I have never actually used it in a production system, so I'm not intimately familiar with its behavior. You may get a more definitive answer if you post the question on the C site:
https://github.com/eclipse/paho.mqtt.c/issues

**Comment by TrevorMuraro** [comment]
No worries.  Thanks!
