### ISSUE TITLE
 ../libpaho-mqttpp3.so.1.1.0: undefined reference to `Log' while cross compiling

### ISSUE THREAD

**Issue by peguine** [eclipse/paho.mqtt.cpp#223]
i tried compile with g++ and everything is ok.
then i need to compile with arm-linux-gnueabifh-g++ ，but i get this error.
i am sure that the C libraries are cross-compiled correctly because i already run a sample and it works.
here is what i do for c++:
1. tar the source code
2. cd into the dir
3. ` cmake -Bbuild -H. -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE  -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++  -DCMAKE_PREFIX_PATH=/usr/local/lib -DCMAKE_CXX_FLAGS=-'lm -lrt -std=c++0x'`
4. cd build
5. make
then i get the error.

please check the attached file for details 
[error.txt](https://github.com/eclipse/paho.mqtt.cpp/files/3754547/error.txt)

**Comment by peguine** [comment]
if set -DPAHO_BUILD_SAMPLES=FALSE 
there is no error.
but while building a cpp using libpaho-mqttpp3.so ,it also have this error.

i found "Log" in the source code async_client.cpp
```
extern "C" {
	void Log(enum LOG_LEVELS, int, const char *, ...);
}
```

**Comment by fpagliughi** [comment]
It's strange. Someone else just complained about this as well. The `Log` function is in the Paho C library with most of the other MQTT functions that we're wrapping. So why is it complaining about this one function?

What version of the compiler are you using? `arm-linux-gnueabihf-g++ --version`

Also, try it without the flags option, `-DCMAKE_CXX_FLAGS=-'lm -lrt -std=c++0x'`

**Comment by peguine** [comment]
arm-linux-gnueabihf-g++ (crosstool-NG linaro-1.13.1-4.7-2013.03-20130313 - Linaro GCC 2013.03) 4.7.3 20130226 (prerelease)
Copyright (C) 2012 Free Software Foundation, Inc.

omit -DCMAKE_CXX_FLAGS=-'lm -lrt -std=c++0x' doesn't help.
-lrt is for the error occured sometimes "undefined reference to `clock_gettime'"

**Comment by martinpfannemueller** [comment]
I just had the same problem without using a cross compiler. In my case I was using the legacy Makefile provided by the Paho C library instead of CMake which caused the problem. I do not know, what actually has changed because of this, however it works now.

**Comment by fpagliughi** [comment]
@peguine That's a pretty old cross compiler. I was still testing on gcc 4.9 until recently, but even 4.9 was quite a bit newer than 4.7. I have since dropped the tests for the 4.x compilers. I think it should work, but I can't be sure that's not the problem.

Are you required to use that particular compiler? If not, I would suggest downloading a more recent one. Linaro downloads are here:
https://www.linaro.org/downloads/

But @martinpfannemueller brings up a great point. You must sure to be using the correct version of Paho C, which is now v1.3.1
https://github.com/eclipse/paho.mqtt.c/releases/tag/v1.3.1

And you should do the CMake build for PahoC as described in the README for this project:
https://github.com/eclipse/paho.mqtt.cpp/blob/master/README.md

**Comment by fpagliughi** [comment]
Oops, forgot, even newer cross-compilers on the ARM site:
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-a/downloads

**Comment by peguine** [comment]
> @peguine That's a pretty old cross compiler. I was still testing on gcc 4.9 until recently, but even 4.9 was quite a bit newer than 4.7. I have since dropped the tests for the 4.x compilers. I think it should work, but I can't be sure that's not the problem.
> 
> Are you required to use that particular compiler? If not, I would suggest downloading a more recent one. Linaro downloads are here:
> https://www.linaro.org/downloads/
> 
> But @martinpfannemueller brings up a great point. You must sure to be using the correct version of Paho C, which is now v1.3.1
> https://github.com/eclipse/paho.mqtt.c/releases/tag/v1.3.1
> 
> And you should do the CMake build for PahoC as described in the README for this project:
> https://github.com/eclipse/paho.mqtt.cpp/blob/master/README.md

yes,the compiler is too old to have errors like "‘sleep_for’ is not a member of ‘std::this_thread’".

@martinpfannemueller is right. I cmake the C library then "cd build" and "make" instead of "make" directly using the Makefile provided.  this error disappeared.  Although I don't know why.

for c++, the final cmake:
`cmake -Bbuild -H. -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE -DCMAKE_CXX_COMPILER=arm-linux-gnueabihf-g++ -DCMAKE_PREFIX_PATH=/usr/local/lib -DCMAKE_CXX_FLAGS='-lrt -D_GLIBCXX_USE_NANOSLEEP'`


Thanks very much

**Comment by fpagliughi** [comment]
My assumption would be that the Makefile simply doesn't compile the _Log()_ function into to C library. I'll raise an issue in the Paho C repo. If more than one build system is supported, they should produce the same output.

Either way, I'm glad it's fixed.

**Comment by fpagliughi** [comment]
Apparently the Log() function in the Paho C lib was meant to be private to that library and should not have been used. It is being removed from the C++ lib.

See also #211, #235.
