### ISSUE TITLE
thread_queue.h error with C++17

### ISSUE THREAD

**Issue by hank121314** [eclipse/paho.mqtt.cpp#226]
Sorry for opening this issue.
I use vs2017 and v141 build tool to build paho.mqtt.cpp successfully.
but I have some problems when I use C++17 to compile it in thread_queue.h.

It shows:
`
Error | C2737 | 'public: static unsigned int const mqtt::thread_queue<std::shared_ptr<mqtt::message const >,std::deque<std::shared_ptr<mqtt::message const >,std::allocator<std::shared_ptr<mqtt::message const > > > >::MAX_CAPACITY': 'constexpr' object must be initialized | SeasonicPowerService | mqtt\thread_queue.h | 78 |  
`

the error has occurred at line(thread_queue.h:78)
`
	/** The maximum capacity of the queue. */
	static constexpr size_type MAX_CAPACITY = std::numeric_limits<size_type>::max();
`

**Comment by fpagliughi** [comment]
I've heard that it doesn't compile under C++17, though I haven't tried it myself. The proposed solutions so far have not been backward compatible, which they would need to be. I'll add this to the next milestone.

**Comment by hank121314** [comment]
OK!
I'm looking forward to it!
Thank you for your hard work!

**Comment by fpagliughi** [comment]
Let's keep this open until it actually gets fixed!

**Comment by fpagliughi** [comment]
It's weird that all of the C++17 problems revolve around constexpr. Issues were fixed with  #161, #162, and now it seems that the recent versions of GCC and Clang will compile the code in C++17 mode, with `-std=c++17` or `c++1z`.

So it appears that this may just be a Microsoft/MSVC thing, and, unfortunately, I don't have access to a Windows machine at the moment, although hopefully I will soon.

What I don't understand is the error it's giving: `'constexpr' object must be initialized`.
Clearly the object is being assigned a value.

Are there any other Windows programmers that could provide a hint?

**Comment by fpagliughi** [comment]
Is there a way to specify the language target used by MSVC (i.e., C++17 vs C++11)?  Does it compile if it's targeting C++11 with the same MSVS 2017?

**Comment by hank121314** [comment]
Well, I create a brand new VC2017 project, and it can compile successfully with C++17.
I thought this issue might be an MSVC misconfiguration.
I will try to find what I messed up.
Thank you for your help! 😄

**Comment by tod0086** [comment]
Hello Hank, did you managed to find what was wrong? I'm experiencing the same issue and can't get over it. 
Thanks!

**Comment by hank121314** [comment]
Hi @tod0086 
I finally figure it out!
This issue is caused by <windows.h>.
<windows.h> have a max macro definition.
This definition will expand:
```
static constexpr size_type MAX_CAPACITY = std::numeric_limits<size_type>::max();
```
to:
```
static constexpr size_type MAX_CAPACITY = std::numeric_limits<size_type>::(((a) > (b)) ? (a) : (b))
```
So MAX_CAPACITY will not be initialized.

Sorry to bother @fpagliughi .
There are two solutions to resolve this issue.
1. Wrap std::numeric_limits<size_type>::max() with parentheses
```
(std::numeric_limits<size_type>::max)()
``` 
2. add document to tell windows developer to add #define NOMINMAX, before including <windows.h>

**Comment by fpagliughi** [comment]
Oh, Windows. Why do you always let me down?

Ha. Nice, @tod0086. The second sounds like a better idea in that it would help prevent any other unexpected behavior from min/max macros getting in the way.

**Comment by tod0086** [comment]
Thank you @hank121314 I will check this asap!
