### ISSUE TITLE
error [-1]: socket error

### ISSUE THREAD

**Issue by Irindul** [eclipse/paho.mqtt.cpp#228]
I'm trying to build a very simple C++ program to send data over MQTT onto an AWS IoT core endpoint. The endpoint is properly configured, and the SSL certificates are provided by AWS, and were tested to be working. 

I modified the `samples/ssl_publish.cpp` to add the configuration (host, cert files etc..) and I'm ending up with : `error [-1]: socket error`. 

I try to run the code directly on the device (cross-compiled) and I got the error so I decided to make it run first on a simple machine and then cross-compile it, but I'm getting the same error so it must come from my code, or how I build/link the application. 

I've configured and linked paho mqtt C library as explained in the documentation. 

I'm testing the code on Fedora 31 and I'm building it and running it using : 
```bash 
$ cmake -Bbuild -H. -DPAHO_WITH_SSL=ON -DPAHO_BUILD_SAMPLES=TRUE
$ sudo cmake --build build/ --target all
$ ./build/src/samples/ssl_publish
```

Here is a pastebin with the [modified code](https://pastebin.com/MwJhGufh) that I use. 
And here is a pastebin with the [trace](https://pastebin.com/xK0Uz7PA), (with trace level MAXIMUM). 

By looking at the logs, I see that the SSL Handshake was successful, which means the certificates are correctly read and sent. But I don't understand what is causing the socket error. 

What steps am I missing to make this code work ?

**Comment by fpagliughi** [comment]
I had never been able to recreate this until I just tried to use AWS again recently. As AWS is not 100% compliant, if you request a feature in the connect message that is proper for MQTT, but that their broker doesn't support, they drop the connection immediately.  This comes off appearing as a connection failure.

It's so confusing, but unfortunately MQTT v3 gave the server not much option but to simply drop a connection when it detects something wrong with no way to report the error to the client.
