### ISSUE TITLE
Can I use version1.1 for production

### ISSUE THREAD

**Issue by zyfromsh** [eclipse/paho.mqtt.cpp#232]
now version1.1 support mqtt5, that's great
but from https://www.eclipse.org/paho/downloads.php, the offical release is 1.0.0 that only support mqtt3.1.1.
if I use version1.1,there are any potential risks,such as unstable?
sorry  I am very new for using open source

**Comment by fpagliughi** [comment]
Oh, I forgot that Eclipse page existed. I should update it. 

All of the releases of this project are meant to be production ready, including v1.1. But keep in mind that this is a volunteer effort. No one is paid to maintain it. So you must do your own testing and evaluation to determine if the quality suits your requirements.

**Comment by zyfromsh** [comment]
Got it.
really thank you for quick response and you contribution to open source.
