### ISSUE TITLE
Unable to build on MacOS

### ISSUE THREAD

**Issue by borisdering** [eclipse/paho.mqtt.cpp#235]
Unable to build on MacOS. Receiving error after hitting make:

`$ cmake -Bbuild -H. -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE -DPAHO_WITH_SSL=FALSE`
`$ sudo cmake --build build/ --target install`

```
[ 37%] Linking CXX shared library libpaho-mqttpp3.dylib
Undefined symbols for architecture x86_64:
  "_Log", referenced from:
      mqtt::async_client::on_connected(void*, char*) in async_client.cpp.o
      mqtt::async_client::on_connection_lost(void*, char*) in async_client.cpp.o
      mqtt::token::on_success(MQTTAsync_successData*) in token.cpp.o
      mqtt::token::on_success5(MQTTAsync_successData5*) in token.cpp.o
      mqtt::token::on_failure(MQTTAsync_failureData*) in token.cpp.o
      mqtt::token::on_failure5(MQTTAsync_failureData5*) in token.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libpaho-mqttpp3.1.1.0.dylib] Error 1
make[1]: *** [src/CMakeFiles/paho-mqttpp3.dir/all] Error 2
make: *** [all] Error 2
```

Environment: 
* cmake version 3.15.5
* gcc Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0
* MacOS Catalina 10.15

Notes: I also tried to compile with g++ compiler but receiving also issues during build. Maybe I should give @VilleViktor 's solution a try by just changing the name back to /usr/local/lib/libpaho-mqtt3as.so.1 to solve the problem. But not sure if it will fix this issue. 

Does anyone has an idea?

**Comment by fpagliughi** [comment]
What a pain this has been. I thought to use the `Log()` function from the Paho C lib so as to intermix the logs from the C++ and C libraries. But depending on the platform and how it was built, the function is not always there and/or publicly exported.

All I can think is that I need to remove the calls to Log() from the C++ library.

**Comment by borisdering** [comment]
@fpagliughi, I do not quite get your answer. So, the way I do understand is, that I need to remove the "Log" function calls, am I right? I will give it a shot.

**Comment by fpagliughi** [comment]
Yes, it builds and works on Linux when using CMake. On other platforms or with the Makefile build, the symbol is hidden from the linker. Apparently, the Log() function was meant to be private to the C library, so I should not have used it in this one. I am removing calls to it from the C++ lib now.

**Comment by fpagliughi** [comment]
Apparently the Log() function in the Paho C lib was meant to be private to that library and should not have been used. It is being removed from the C++ lib.

See also #211, #223
