### ISSUE TITLE
MQTT error [-1]: TCP/TLS connect failure

### ISSUE THREAD

**Issue by Pan2810** [eclipse/paho.mqtt.cpp#244]
**My system**
   windows 10 x64
   vs2015
   broker i use aws and setting:

mosquitto.conf
```
persistence true
persistence_location /var/lib/mosquitto/

#log_dest file /var/log/mosquitto/mosquitto.log

include_dir /etc/mosquitto/conf.d

# Define BY ANHNP HFVN
#allow_anonymous true
#password_file /etc/mosquitto/pass.txt

#Extra Listeners
port 1883
listener 8883
#ssl settings
cafile /etc/mosquitto/certs/ca.crt
keyfile /etc/mosquitto/certs/server.key
certfile /etc/mosquitto/certs/server.crt
#client certifcate settings
require_certificate true
#tls_version tlsv1.1

```

I have created certificates according to the following instructions:
-    http://www.steves-internet-guide.com/mosquitto-tls/
-    http://www.steves-internet-guide.com/creating-and-using-client-certificates-with-mqtt-and-mosquitto/
Use that certificate and run the command from a client:
mosquitto_pub --cafile ca.crt --cert client.crt --key client.key -d -h xxx.xxx.xxx.xxx -p 8883 -t test -m "here" --tls-version tlsv1.2
 It was successful.

But when i am following the following example: https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/ssl_publish.cpp

There are 2 commands in the program:
   sslopts.set_trust_store(TRUST_STORE); // test-root-ca.crt **(This is broker ca.crt)**
   sslopts.set_key_store(KEY_STORE); // client.pem

I do not know how to create client.pem.
I tried many ways but it always returns an error MQTT error [-1]: TCP/TLS connect failure.

**Comment by saftkran** [comment]
You say that you do not know how to create "client.pem". This is the client certificate, which is created by following the first of  your [links](http://www.steves-internet-guide.com/mosquitto-tls/). Do mind that if you follow that guide to the letter, the output file will have the name client.crt. What the name is is not in itself important, however.

Do also mind that you set the correct common name for the server and client certificates respectively.

**Comment by Pan2810** [comment]
I will try again if successful I will confirm again. Thank you!

**Comment by martinpeniak** [comment]
> I will try again if successful I will confirm again. Thank you!

Did you manage to solve this? I am having similar issue: https://github.com/eclipse/paho.mqtt.cpp/issues/318

Thanks
