### ISSUE TITLE
Published version of crate is too old. 

### ISSUE THREAD

**Issue by lis0x90** [eclipse/paho.mqtt.cpp#248]
Hi,

Why you don't publish your recent versions of this nice library on https://crates.io/crates/paho-mqtt ?

Only 0.6.0 available as crate. So sad

**Comment by fpagliughi** [comment]
There's an issue in the upstream library (Paho C) causing problems on Windows. An initial fix is in, but it hasn't been fully tested or released yet. Once that is done, I will finish testing this version, release it, and then get on to the next version to support async/await.

**Comment by fpagliughi** [comment]
Oh, and I assume you meant to post this on the Paho Rust repo (https://github.com/eclipse/paho.mqtt.rust/issues)

This is the C++ library.

**Comment by fpagliughi** [comment]
Closing as it appears to apply to the wrong repository.

**Comment by lis0x90** [comment]
Yep. Wrong repo. Sorry
