### ISSUE TITLE
subscribe to many topics segfaults on single topic

### ISSUE THREAD

**Issue by tllngr** [eclipse/paho.mqtt.cpp#255]
I assume there is a bug causing a segfault when using subscribe to many topics, where topic and qos argument only contain a single item.

Reproducing:
Unit test _async_client_test::test_subscribe_many_topics_2_args_ will segfault if TOPIC_COLL and GOOD_QOS_COLL only contain a single item, e.g.:

~~~
mqtt::const_string_collection_ptr TOPIC_COLL { mqtt::string_collection::create({ "TOPIC0" }) };
mqtt::iasync_client::qos_collection GOOD_QOS_COLL { 0 };
~~~

Segfault occurs at _src/mqtt/server_response.h_, line 142:
~~~
reasonCodes_.push_back(ReasonCode(rsp->alt.qosList[i]));
~~~

Tested with f3a2a52259b5463ab50eee6d1c033cba18d6e84b (current master)

**Comment by fpagliughi** [comment]
Yes, sorry. This is a known issue. #224 
I will be working on this library in the next week or so, and will surely get this fixed.

**Comment by fpagliughi** [comment]
Oh, and thanks @tllngr. You reminded me to put in a test case for this. In the `develop` branch. It's now passing.

**Comment by tllngr** [comment]
That is good news :+1: . Thank you @fpagliughi for the fix and your help.
