### ISSUE TITLE
MQTT error [-12]: No more messages can be buffered

### ISSUE THREAD

**Issue by Eric-Sunjian** [eclipse/paho.mqtt.cpp#258]

**Comment by Eric-Sunjian** [comment]
what should i do when meet this problem?

**Comment by maxlein** [comment]
Increase the buffer :)  
Or check why your buffer is full in the first place.  
Maybe already sending msgs before being connected to a broker?

**Comment by fpagliughi** [comment]
This means that you are trying to send messages faster than the client can deliver them, or, more likely, as @maxlein mentioned, you are trying to send messages while the client is disconnected from the server.

There is limited support for queuing messages in the client. Several client constructors take a `maxBufferedMessages` parameter, like:

```
async_client(const string& serverURI, const string& clientId,
             int maxBufferedMessages, const string& persistDir);
```

But really you need to make decisions based on your system's throughput, connection capabilities, and the importance and lifetimes of messages to make a proper decision on what to do. Personally, when writing apps, I don't rely too much on the library's ability to buffer messages, but let the application maintain its own backlog, and then try to push those messages out when there's a good connection. That also lets you decide if some messages are stale and can be discarded.

**Comment by Eric-Sunjian** [comment]
Thanks!!!!

**Comment by stan1334** [comment]
if set maxBufferedMessages 100
client send datas 2broker
send data is support sequential timestamp from client cache？
@Eric-Sunjian
