### ISSUE TITLE
Compile with C++14 standard

### ISSUE THREAD

**Issue by CzJakethedog** [eclipse/paho.mqtt.cpp#262]
Dear all,

Currently, I am trying to cmake the mqtt with my libtorch model in c++ code. The libtorch is required c++14. How can I compile it with mqtt here which required c++11?
I hope there is a solution can help me.

Thank you

**Comment by fpagliughi** [comment]
C++11 is the _minimum_ requirement. It compiles with C++14 just fine.

**Comment by CzJakethedog** [comment]
Thanks for the reply.

In my cmakelist.txt,
I added
```
list(APPEND CMAKE_MODULE PATH "path/to/mqtt/cmake")
find_package(PahoMqttC REQUIRED)
```

It could find the libmqtt3a.so but when I used call mqtt function in my cpp code, it shows
`undefined reference to `mqtt::async_client::async_client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mqtt::iclient_persistence*)'`
isn't it related to the compiler?

**Comment by fpagliughi** [comment]
The C++ library is _libpaho-mqttpp3_.
It looks like maybe you forgot the "pp"

**Comment by CzJakethedog** [comment]
Do you have any idea to call the c++ package?
`find_package(PahoMqttCpp REQUIRED) ` is invalid to compile as I tried

**Comment by Marwin34** [comment]
Have you resolved the issue?

**Comment by Chauncy-Guo** [comment]
> Do you have any idea to call the c++ package?
> `find_package(PahoMqttCpp REQUIRED) ` is invalid to compile as I tried

The common cause of this error is forgetting to link both the Paho C and C++ libraries into your application. It needs both libpaho-mqttpp3.so (C++) and libpaho-mqtt3as.so (C).
If you're not using SSL/TLS, you can use libpaho-mqtt3a.so instead of the "...as.so" version.

---by  https://github.com/eclipse/paho.mqtt.cpp/issues/120

fpagliughi tell it
