### ISSUE TITLE
paho.mqtt.c 1.3.2 no longer using -static extension for library naming

### ISSUE THREAD

**Issue by atomcraft-th** [eclipse/paho.mqtt.cpp#264]
The static library for paho.mqtt.c no longer has the -static extension so the static compile doesn't work when built against paho.mqtt.c 1.3.2

eg
cmake -DPAHO_BUILD_STATIC=ON -DPAHO_BUILD_SHARED=OFF -DPAHO_WITH_SSL=OFF -DCMAKE_PREFIX_PATH=/home/pi/dev/build/libraries/install/ -DCMAKE_INSTALL_PREFIX=/home/pi/dev/build/libraries/install/ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/c++ "-GUnix Makefiles" /home/pi/dev/build/libraries/mqtt/src
-- The CXX compiler identification is GNU 8.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPahoMqttC.cmake:30 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:26 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/pi/dev/build/libraries/mqtt/build/CMakeFiles/CMakeOutput.log".

$ ls /home/pi/dev/build/libraries/install/lib/
cmake  libpaho-mqtt3a.a   libpaho-mqtt3a.so.1      libpaho-mqtt3c.a   libpaho-mqtt3c.so.1      pkgconfig  libpaho-mqtt3a.so  libpaho-mqtt3a.so.1.3.2  libpaho-mqtt3c.so  libpaho-mqtt3c.so.1.3.2

**Comment by fpagliughi** [comment]
Yeah, I just saw that. I'll get a fix in for the next service release.

**Comment by bowb** [comment]
I am not seeing this issue when I build with paho-mqtt-cpp v1.1 and paho-mqtt-c v1.3.7 Will someone else verify if this is still an issue?
