### ISSUE TITLE
will_options copy/move assignment doesn't assign will properties

### ISSUE THREAD

**Issue by tllngr** [eclipse/paho.mqtt.cpp#266]
When setting mqtt(v5) _will properties_, they will not appear in the CONNECT packet.

I probably found the cause: At copy/move assignment operators from _will_options.cpp_ the properties are not set. I guess it should be added like this:

~~~.cpp
will_options& will_options::operator=(const will_options& rhs)
{
	if (&rhs != this) {
		opts_ = rhs.opts_;
		set_topic(rhs.topic_);
		set_payload(rhs.payload_);
		set_properties(rhs.props_); //fix by adding this line
	}
	return *this;
}

will_options& will_options::operator=(will_options&& rhs)
{
	if (&rhs != this) {
		opts_ = rhs.opts_;
		set_topic(std::move(rhs.topic_));
		set_payload(std::move(rhs.payload_));
                set_properties(std::move(rhs.props_)); //fix by adding this line
	}
	return *this;
}
~~~

Steps to reproduce:
Modify _main_ function of example _async_subscribe.cpp_ to set will properties, e.g. 
~~~.cpp
int main(int argc, char* argv[])
{
	mqtt::connect_options connOpts;
	connOpts.set_keep_alive_interval(20);
	connOpts.set_clean_session(true);


	/// show will property issue
	connOpts.set_mqtt_version(5);

	mqtt::will_options willOpts;
	willOpts.set_topic("will/topic");
	willOpts.set_payload(std::string("will message"));
	willOpts.set_qos(1);
	mqtt::properties willProps({{mqtt::property::code::WILL_DELAY_INTERVAL, 123}});
	willOpts.set_properties(willProps);
	connOpts.set_will(willOpts);
	///
       // 8<  ----  snip ---- 8<
~~~
Start example and watch CONNECT packet with wireshark. Will Properties are missing in the packet

**Comment by tllngr** [comment]
Same issue appears at connect_options.cpp:

~~~.cpp

connect_options& connect_options::operator=(const connect_options& opt)
{
	opts_ = opt.opts_;

	if (opts_.will)
		set_will(opt.will_);

	if (opts_.ssl)
		set_ssl(opt.ssl_);
        //Add this
        if(opts_.connectProperties) {
        	set_properties(opt.props_);
        }
        //----------
	set_user_name(opt.userName_);
	set_password(opt.password_);

	return *this;
}

~~~

**Comment by fpagliughi** [comment]
Yeah, that definitely looks like a bug. I'm trying to get a release of the Paho Rust library out this week, then I'm going to swing back to this C++ lib and get a service release out. I'll get this in there.

**Comment by tllngr** [comment]
Thank you Frank!
Can you also please have a look at desctruct/freeing of the connect properties and the will properties? I ran the fixed code under valgrind memcheck and it complains that the memory allocated for all the property stuff won't get freed.

**Comment by fpagliughi** [comment]
Yeah, I run some checks with valgrind, but I don't know how good my coverage is with some of the new MQTT v5 features. There's definitely still more to do on that front.

**Comment by tllngr** [comment]
I don't know much about travis. I use jenkins and have an additional build step where I have running my unit tests under valgrind. If the coverage is good enough this may be also a handy solution here?

**Comment by tllngr** [comment]
I did some research and request regarding the memory issue i mentioned at my comment https://github.com/eclipse/paho.mqtt.cpp/issues/266#issuecomment-620023240

I added an issue at paho.c that clarifies what causes the memleak:
https://github.com/eclipse/paho.mqtt.c/issues/914

As things are standing now, I suggest two possible solutions that may be applied to paho.cpp as a fix:

- Paho.cpp does call *::Heap_Init()* (paho.c/Heap.h) internally to ensure paho.c's internal heap manager is initialized properly
or
- Paho.cpp adds documentation on how to build paho.c for usage with paho.cpp and hints cmake option *PAHO_HIGH_PERFORMANCE=ON* at README.md

**Comment by fpagliughi** [comment]
Yeah, if there's an underlying problem with the Paho C library and it gets fixed there, then I will be sure to bump this lib to use the latest fixes. Thanks for pursuing that on the C repo. I'll keep an eye on it.

The PAHO_HIGH_PERFORMANCE flag is brand new in the C lib. It came out after the last C++ release, I believe. It definitely looks like that should be the default way to build with the C++ library, and I will be testing and documenting accordingly.

**Comment by tllngr** [comment]
Hi Frank,
indeed the PAHO_HIGH_PERFORMANCE option was recently added. I agree that it should be the default way of building it for usage with the paho C++. I tested and can confirm that PAHO_HIGH_PERFORMANCE solves the memleak issue here.

**Comment by fpagliughi** [comment]
Great! Yes, it would be good to have some people test it.

**Comment by tllngr** [comment]
I may support testing if that helps

**Comment by fpagliughi** [comment]
Oh, yeah, this was fixed long ago. Closing.
