### ISSUE TITLE
Conan package for arm

### ISSUE THREAD

**Issue by InventoryTech** [eclipse/paho.mqtt.cpp#267]
I was hoping to find a conan package on https://conan.io/center/paho-mqtt-cpp/1.1/ for arm, does this not exist yet?

**Comment by gocarlos** [comment]
cci does not store ARM builds for you, though conan will built it on the fly for you if you add this package as dependency and have set the cross compiler correctly...

though this is not an issue with this repo

**Comment by fpagliughi** [comment]
Yes, we didn't create, and don't maintain the conan packages.
