### ISSUE TITLE
Get binary payload

### ISSUE THREAD

**Issue by tankbiuk** [eclipse/paho.mqtt.cpp#27]
For a project using MQTT I need to get binary payload.
I Make a workaround by introducing two new functions in message class:
`int get_payload_size();`
`void* get_payload_bytes();`

Implemented as follow:
```
int message::get_payload_size()
{
	return msg_.payloadlen;
}

void* message::get_payload_bytes()
{
	return msg_.payload;
}
```
So I can copy the byte array to a std::array<unsigned char> in my application.

What do you think about this implementation? 
Do you foreseen to add a get_payload() function for retrieving binary data?

**Comment by fpagliughi** [comment]
This sounds reasonable. I'll have a look.

**Comment by fpagliughi** [comment]
Actually this is already available through `message::get_payload()`, which returns a std::string. Thus you can use:
`get_payload().size()` to get the number of bytes (returns a `size_t`), and
`get_payload().data()` to get a const pointer to the data (returns a `const char*`)

The only thing I'm considering for the 1.0 release is a (slight) breaking change to use a collection of unsigned bytes (`uint8_t`) for the internal payload. The .data() method would then return a 'const uint8_t*`.  But if I did that, I would likely also add a `get_payload_str()` or similar to help users that are passing around string payloads.
