### ISSUE TITLE
segfault when loading persisted data

### ISSUE THREAD

**Issue by an-ky** [eclipse/paho.mqtt.cpp#270]
We implemented our own persistence facade based on `std::map` for test reasons while we stumbled on a problem related to the way paho.mqtt.cpp interacts with maho.mqtt.c.

When we start the client it tries to load persisted messages and we get a segfault (munmap_chunk(): invalid pointer) inside [MQTTPersistence.c](https://github.com/eclipse/paho.mqtt.c/blob/146d210addda572870ee56accbce6cc7bb5f129b/src/MQTTPersistence.c#L318-L320)

```
			}
			if (msgkeys[i])
				free(msgkeys[i]);
```

were it tries to free the key of the currently processed message.

Following the code upwards to our implementation we found that [MQTTPersistence.c](https://github.com/eclipse/paho.mqtt.c/blob/146d210addda572870ee56accbce6cc7bb5f129b/src/MQTTPersistence.c#L191)

```
	if (c->persistence && (rc = c->persistence->pkeys(c->phandle, &msgkeys, &nkeys)) == 0)
```

calls the persistence facade to acquire all keys. In paho.cpp this is hard-wired to
[iclient_persistence.cpp](https://github.com/eclipse/paho.mqtt.cpp/blob/f3a2a52259b5463ab50eee6d1c033cba18d6e84b/src/iclient_persistence.cpp#L107-L121)

```
int iclient_persistence::persistence_keys(void* handle, char*** keys, int* nkeys)
{
	try {
		if (handle && keys && nkeys) {
			auto& k = static_cast<iclient_persistence*>(handle)->keys();
			size_t n = k.size();
			*nkeys = n;
			*keys = (n == 0) ? nullptr : const_cast<char**>(k.c_arr());
			return MQTTASYNC_SUCCESS;
		}
	}
	catch (...) {}


	return MQTTCLIENT_PERSISTENCE_ERROR;
}
```
which calls the user defined persistence implementation. 

Our implementation of `keys` does something plain as shown below, just copy the strings from the map to a static `string_collection` which is `clear()`ed on every call to `keys()` to return a freshly filled copy of the keys.

```
const mqtt::string_collection& keys() const override
{
        // needed to return const reference :(
	static mqtt::string_collection ks;
	ks.clear();

        for(const auto& k : store_)
        {
            ks.push_back(k.first);
        }

        return ks;
}
```

The way paho.cpp and paho.c interact and how we should place us in-between at this point is not fully clear. The returned string_collection obviously manages the strings. 
Now simply using the contained strings and passing the pointers to them to paho.c will ultimatly result in a double-free scenario as far as we can see, because the buffers containing the keys are always `free()`d by paho.c and either the destructor or clear will be called on the string_collection, too.

I hope you can shed some light on this issue, and how we can correctly implement this method to bypass the `munmap_chunk(): invalid pointer` error - or you can give us a pointer were we were misguided.

Greet 
An Ky

Versions
paho.cpp(1.1)
paho.c(1.3.2) 

self-compiled on arm with gcc-9

**Comment by fpagliughi** [comment]
Thanks for the detailed report!  I'll have a look.

**Comment by fpagliughi** [comment]
Yes. The API was bad. The `keys()` and `get()` calls need to return a copy of the data - not references.

**Comment by fpagliughi** [comment]
The fix is in the `develop` branch with a new example of user-based file persistence with some simple encoding. It's in the `data_publish.cpp` sample.
