### ISSUE TITLE
MQTT is stuck for around 15 minutes

### ISSUE THREAD

**Issue by rellikb** [eclipse/paho.mqtt.cpp#271]
# Issue
MQTT is successfully sending traffic on LTE without issue when the connection is good.
Then briefly we lose LTE connection and MQTT is stuck for almost 15minutes and not publishing any data. No issues with LTE connection after reconnect as we were able to see other traffic flowing. I enabled MQTT client tracing, but during this time there is not logs printed from MQTT. So not sure how to proceed from here to debug this further. Observed similar behavior when we switched from LTE to wired connection. Any idea what could be causing this?

# MQTT client logs snippet:
Timestamps when we stop seeing traffic.
Start time: **2020-05-22T22:30:03.330379453Z**
End time: **2020-05-22T22:46:42.885897717Z**
```
{"log":"20200522 223003.330 4 metrics-test -\u003e PUBLISH qos: 0 retained: 0 (-22)\n","stream":"stdout","time":"2020-05-22T22:30:03.330379453Z"}
{"log":"20200522 224642.885 4 metrics-test -\u003e PINGREQ (-1)\n","stream":"stdout","time":"2020-05-22T22:46:42.885897717Z"}
{"log":"20200522 224642.885 Error sending PINGREQ for client metrics-test on socket 4, disconnecting\n","stream":"stdout","time":"2020-05-22T22:46:42.885916788Z"}
```

# Additional details from logs:
```
{"log":"20200522 223003.327 4 metrics-test -\u003e PUBLISH qos: 0 retained: 0 (0)\n","stream":"stdout","time":"2020-05-22T22:30:03.327403608Z"}
{"log":"20200522 223003.328 4 metrics-test -\u003e PUBLISH qos: 0 retained: 0 (0)\n","stream":"stdout","time":"2020-05-22T22:30:03.328206715Z"}
{"log":"20200522 223003.329 4 metrics-test -\u003e PUBLISH qos: 0 retained: 0 (0)\n","stream":"stdout","time":"2020-05-22T22:30:03.329414104Z"}
{"log":"20200522 223003.330 4 metrics-test -\u003e PUBLISH qos: 0 retained: 0 (-22)\n","stream":"stdout","time":"2020-05-22T22:30:03.330379453Z"}
{"log":"20200522 224642.885 4 metrics-test -\u003e PINGREQ (-1)\n","stream":"stdout","time":"2020-05-22T22:46:42.885897717Z"}
{"log":"20200522 224642.885 Error sending PINGREQ for client metrics-test on socket 4, disconnecting\n","stream":"stdout","time":"2020-05-22T22:46:42.885916788Z"}
{"log":"20200522 224642.885 4 metrics-test -\u003e DISCONNECT (-1)\n","stream":"stdout","time":"2020-05-22T22:46:42.885920216Z"}
{"log":"MQTT error: MQTT error [-11]:  [-11]\n","stream":"stderr","time":"2020-05-22T22:46:42.885946616Z"}
{"log":"MQTT error: MQTT error [-3] [-3]\n","stream":"stderr","time":"2020-05-22T22:46:42.886188409Z"}
{"log":"20200522 224642.886 Connecting to serverURI <IP>:1883 with MQTT version 4\n","stream":"stdout","time":"2020-05-22T22:46:42.886219885Z"}
{"log":"20200522 224643.815 3 <topic> -\u003e CONNECT cleansession: 1 (0)\n","stream":"stdout","time":"2020-05-22T22:46:43.815464091Z"}
{"log":"20200522 224645.174 3 metrics-test \u003c- CONNACK rc: 0\n","stream":"stdout","time":"2020-05-22T22:46:45.174611292Z"}
{"log":"MQTT client: metrics-test topic: test4/test \n","stream":"stdout","time":"2020-05-22T22:46:45.174635045Z"}
```

**Comment by fpagliughi** [comment]
I'm not sure. It seems to detect the disconnect from a failure of the PINGREQ. So apparently it's not seeing the underlying stream close and is relying on the "keep alive" to detect the disruption. (That should be OK, since that's actually one of the main purposes of the keep alive pings). 

Are you using auto reconnects? Or just trying a manual reconnect as soon as you're disconnected?

Or do you wait for a signal from the LTE modem to tell you that it's reconnected, and then try the MQTT connection? (This is the way I usually do it).

**Comment by rellikb** [comment]
Thanks for quick turnaround. First time using MQTT, I might be missing few things.
1. So the disconnect detection happens after 16 minutes. From logs we see PINGREQ being sent after 16 minutes? Is that expected? How frequently are these "keep alive"s sent?
2. Regarding Reconnection - Currently I handle 2 exceptions when I publish on MQTT and if I get MQTTCLIENT_FAILURE (-1) or MQTTCLIENT_DISCONNECTED(-3), I do a manual reconnect. All other exceptions I just log it. So far I have only seen -11 being logged.

I haven't added any logic to wait for signal from modem. But for sure the LTE connection is up during these time as I see other traffic.

Another observation:
I have seen MQTTCLIENT_DISCONNECTED multiple times during these tests and each time it has successfully reconnected. Not sure why in this case it takes a long time to detect the disconnect?
