### ISSUE TITLE
fatal error LNK1181: cannot open input file 'C:\mqtt\paho-c\lib.obj'

### ISSUE THREAD

**Issue by chamarts** [eclipse/paho.mqtt.cpp#273]
trying to build from source got me a linker error. Couldn't find this reference in sources except in vc files. appreciate any help fixing this. looks like vc project got corrupted

**Comment by chamarts** [comment]
ok I think I found the error.... for some reason this is included in the additional Linker->Input -> Additional Dependencies section causing the issue 
C:\mqtt\paho-c\lib

**Comment by morphogencc** [comment]
I tried building the shared libraries and had the same problem.

What's the correct way to fill out `PAHO_MQTT_C_LIBRARIES'?  If I add the path to the lib folder (in my case, `C:\Program Files (x86)\Eclipse Paho C\lib`), then I get the missing .obj error as noted above.

If I add all 4 libs:

`C:/Program Files (x86)/Eclipse Paho C/lib/paho-mqtt3a.lib; C:/Program Files (x86)/Eclipse Paho C/lib/paho-mqtt3as.lib; C:/Program Files (x86)/Eclipse Paho C/lib/paho-mqtt3c.lib; C:/Program Files (x86)/Eclipse Paho C/lib/paho-mqtt3cs.lib`

then I get an error as well.

Do I have to pick just one library / use-case for linking to Paho C?

**Comment by morphogencc** [comment]
Answering my own question: yes, just pick one library.  I linked against just `paho-mqtt3as.lib` and the library compiled just fine.
