### ISSUE TITLE
MQTT error [-8]: Bad structure

### ISSUE THREAD

**Issue by chamarts** [eclipse/paho.mqtt.cpp#274]
running sample program and stuck with this error. not sure if I need to set global options (MQTG ? version ? ssl ?). something is odd. client is ok but it fails on connect

**Comment by MalteSLi** [comment]
Hi @chamarts , did you manage to solve the problem? 'Cause I'm stuck with the exact same error :/

**Comment by fpagliughi** [comment]
I wonder if this is a mismatch between library versions. Which version of the C++ library are you using? What about the Paho C version?

**Comment by fahadusman** [comment]
I also started getting the same error after updating the paho c++ library, fixed it be updating the c library as well, and manually removing the previous libraries and then installing the newly built ones.
