### ISSUE TITLE
MQTT publish exception(Access violation reading location).

### ISSUE THREAD

**Issue by SoumenKunduTantra** [eclipse/paho.mqtt.cpp#276]
When I am publishing message via mqtt::publish(), I am getting below exception.
`Exception thrown at 0x00007FF68471021C in xxxxxxxxxxxxxxxxxxxxx.exe: 0xC0000005: Access violation reading location 0x0000000000000008`

![mqtt_exception](https://user-images.githubusercontent.com/51443098/103059522-5f087700-45cb-11eb-8e11-01b2bfcd9af5.jpg)

Part of code where I am publishing my message : 
 ```
void mqtt_client::transmit_message(void)
{
    try {
        std::string data;
        {
                std::lock_guard<std::mutex> lock{ this->transmit_queue_mutex };
                if (this->transmit_queue.empty())
                        return;
                data = this->transmit_queue.front();
        }
        mqtt::message_ptr msg = mqtt::make_message(this->topic_out, data.data(), data.length(), mqtt_client::qos, false);
        this->transmit_in_progress.store(true);
        this->client->publish(msg);
    }
    catch (const mqtt::exception& ex) 
    {
        std::string stre = std::string("Error in transmitting message. Error : ") + ex.what()
                + std::string(" [ ") + ex.get_reason_code_str() + std::string(" ] ");
        LOGE << stre;
#ifdef _DEBUG
        std::cerr << "Error: " << ex.what() << " ["
            << ex.get_reason_code_str() << "]" << std::endl;
#endif 
    }
    catch (const std::exception& ex) 
    {
        std::string stre = std::string("Error in transmitting message. Error : ") + ex.what();
        LOGE << stre;
#ifdef _DEBUG
        std::cout << stre << std::endl;
#endif 
    }
}
```

This error is occuring in Windows Visual Studio.
I am using same code in one project written using Netbean IDE for linux(Raspberry Pi). mqtt is installed in Raspberry using `apt get` .There it is working without and issue.

OS : Windows 10 Home 
Bit : x64
Visual Studio : Microsoft Visual Studio Community 2017
vcpkg : paho-mqttpp3

**Comment by fpagliughi** [comment]
I never was able to recreate this, but we found and fixed a few memory violations in the C lib which may have caused this. I wonder if it's still a problem in the latest develop version of each of the libraries.

**Comment by SoumenKunduTantra** [comment]
Thank You.
