### ISSUE TITLE
Sending too many message causes client disconnect

### ISSUE THREAD

**Issue by shaila123456789** [eclipse/paho.mqtt.cpp#277]
Hello,

I am writing an application which sends messages continuously in 2 threads, each thread publishes 200 messages and sleeps for 200 microseconds. I am using async client for this.
With this, I get exception "No more messages can be buffered" while publishing the messages. However, when I dig more into this, I can see the reason that, MQTT publisher was already disconnected and the connection_lost callback in my application was not called. 
So my application cannot reconnect to the broker and keep on publishing the messages and get exceptions.

I tried setting auto_reconnect = true, max no of inflight messages = 20000. I made respective changes in the mosquitto.conf file also.

What could be the possible solution for this ?

-thanks,
S

**Comment by fpagliughi** [comment]
How do you know that the connection was disconnected? Is the client telling you (somehow?) or is the broker telling you? If the client is aware that the connection was severed, but didn't fire off the `connection_lost()` callback, that would be a bug. But sometimes it can be slow to figure out that the connection is jammed if the underlying TCP connection still exists but is misbehaving.

It sounds like you're trying to push a really high number of messages through the system.If your overall network can't support the throughput then you'll need to reconsider what's possible. Remember that the underlying protocol only allows for 64k in-flight messages w/ QoS=1 or 2, due to the message ID being 16-bits.

**Comment by shaila123456789** [comment]
Thanks for the reply fpagliughi !

In my application, after publishing around 92K messages, I start getting "No messages can be buffered" exception. I got this exception for all QOS levels. This conveys that the number of in-flight messages are more than 64K (as you told). So, is there any way in which I can increase this buffer size ?

Also, can I find any benchmark result which tells the optimum number of messages to be published every millisecond or second, using async client with different QOS levels?

-thanks,
S

**Comment by fpagliughi** [comment]
Unfortunately, the 64k limit is one of the underlying protocol. It tracks (ACKs) QoS 1 & 2 messages with a message identifier which is only 16-bits. So it runs out of usable identifiers at the 64k limit.

As for the ultimate limit, it depends highly on your system, broker, connection, etc. The only way to know is to test your specific setup in the wild.

MQTT is best suited for remote systems with unreliable connections. If you have a reliable connection and want to blast hundreds of thousands of messages per second or more, you might want to consider a different technology like RabbitMQ or Kafka.

**Comment by shaila123456789** [comment]
Hello fpagliughi, 
I have added the code snippet from my sample application. I figured out that application can publish 1000 messages in 1 second, on MQTT broker. The publisher and broker are running on the same machine.
The setup ran for almost 45 hours without any exception, but after that I got  an exception "No more messages can be buffered" (got this exception only once) and 3 hours after that (almost 48 hours after the application start), the publisher got disconnected from the MQTT broker giving exception in publish function "Exception in publish : MQTT error [-3]: Disconnected".

What can be the possibly be going wrong in below code that publisher got disconnected from the MQTT broker ?

mqtt::async_client publisher; //initialized in main function with MQTT broker URL and the client ID
bool test::connect() //gets called from main function to initiate connection with the MQTT broker
{
        try
	{
		mqtt::connect_options syncConnOpts;
		
		connOpts.set_keep_alive_interval(20);
		connOpts.set_clean_session(true);
		connOpts.set_automatic_reconnect(1, 10);
		connOpts.set_max_inflight(64000);

		publisher.connect(connOpts);
	}
	catch (const std::exception &e)
	{
		std::cout << __func__ << ":" << __LINE__ << " MQTT publisher failed to connect with MQTT broker: exception : " << e.what() << std::endl;
	}
}

bool test::publish(std::string &msg, std::string &topic)
{
		int qos = 1;
		try
		{
			mqtt::message_ptr pubmsg = mqtt::make_message(msg, topic, qos, false);

			publisher.publish(pubmsg, nullptr, listener);
			std::cout << "Published message on MQTT broker successfully" << std::endl;	
		}
		catch (const mqtt::exception &exc)
		{
			std::cout << " Exception in publish : " << exc.what() << std::endl;
			return false;
		}
		return true;
}

**Comment by hwnBEAST** [comment]
I am using almost the same setup and sending 10 msgs per second. I am using a slow broker test.mosquitto.org, after about 1 minute or so, the publisher says all queued messages are delivered successfully, but none are. The publisher also says its connection failed....

**Comment by fpagliughi** [comment]
@shaila123456789 I could never reproduce this to see what might be happening. I was doing tests on a desktop that is always on. The only thing that I did find on my laptop and on an embedded ARM board is that networking components seem to get shut down in some low power modes which causes  a disconnect, and then issues reconnecting. Do you think something like this might have caused your problem?
