### ISSUE TITLE
[Suggestion] create a template class for options

### ISSUE THREAD

**Issue by guilhermeferreira** [eclipse/paho.mqtt.cpp#28]
The classes `connect_options`, `disconnect_options`,` response_options`, `ssl_options` and `will_options` have many things in common. The idea is to create an `options `template class to hold the common code and create specializations for each type.

Something like this:

```
template<typename T>
class options {
private:
    T opts_;

public:
    using ptr_t = std::shared_ptr<options<T>>;
    using const_ptr_t = std::shared_ptr<const options<T>>;
};

using connect_options = mqtt::options<MQTTAsync_connectOptions>;
using disconnect_options = mqtt::options<MQTTAsync_disconnectOptions>;
using response_options = mqtt::options<MQTTAsync_responseOptions>;
using ssl_options = mqtt::options<MQTTAsync_SSLOptions>;
using will_options = mqtt::options<MQTTAsync_willOptions>;
```

There are some problems though. For example, how do we handle the differences accross specializations in:
- The std::string buffers for each class.
- The access methods to attributes. Because each specialization has its own set of access methods.
- Constructor argument list.
- Construction initialization list.

**Comment by fpagliughi** [comment]
This might be useful, but let's hold off until after the 1.0 release.

**Comment by fpagliughi** [comment]
This is a good idea, but I'm starting to think it wouldn't work. After getting into the options classes again and refreshing my memory about them, I see that there is a formula for implementing them, but the details are different for each set of options - sometimes for each field in any one of them!

All of the worries you listed are valid, but there are additional ones. For example. some of the buffered data requires the C field to be set to NULL if the buffer is empty, while others require a valid, yet empty, field.

I think we may be stuck with hand-coding these.
