### ISSUE TITLE
I want to compile in 32bit.

### ISSUE THREAD

**Issue by kihwankim** [eclipse/paho.mqtt.cpp#281]
hello I would like to build this in 32bit, Is there a way to build in ubuntu 32bit???

**Comment by fpagliughi** [comment]
To do a native 32-bit build? Just follow the normal CMake build instructions. Are you have some issue with that?

**Comment by kihwankim** [comment]
actually, I am doing something using paho mqtt, but I have to build paho mqtt client for 32 bit, I don't know how to install paho mqtt .c and cpp in 32 bit, can you tell me the location of the cmakelist.txt, so that I can build in 32bit?
And thank you for your reply!!
