### ISSUE TITLE
C++ Support for Websockets?

### ISSUE THREAD

**Issue by morphogencc** [eclipse/paho.mqtt.cpp#285]
It looks like the underlying Paho-C library now supports websockets (and the README for this project says it does), but I can't find any tutorials, samples, or even code that references how to enable websockets.

Are there any hints as to how to enable it?  A simple example would be really helpful!

**Comment by fpagliughi** [comment]
Pretty much just make your URI "ws://..." (unsecure) or "wss://..." (secure)

Yeah, someone should write some better docs and tutorials!

**Comment by morphogencc** [comment]
Well, that was it! ws:// and port 8080 work like a charm, I'll have to do further tests with certificates for wss.

thanks!
