### ISSUE TITLE
Update the build system.

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.cpp#286]
It's long since time to get the CMake build system updated and modernized. This can go hand-in-hand with a similar update to the Paho C build system, but if not, the C++ lib should try to hide the details. In general:

1. Update to the current "best practices" for Modern CMake
2. As much as possible make the C lib a private dependency of the C++ lib.
  a. Let the C++ build resolve and handle the transient dependencies.
  b. Prefer to link the C lib _into_ the C++ lib
  c. If the C lib is not found, automatically download and build it.
  d. Try to deal with all the possible variants of the C lib.
3. Make sure version numbers are properly exported and handled.

Suggestions, help, and testing across platforms would be greatly appreciated.

**Comment by keysight-daryl** [comment]
would be nice to see a transfer of power over to the guys at conan-center-index for proper conan packaging and as you said a supporting cmake that also works with it.  paho.mqtt.c recently transitioned to the same and it is being well maintained by the conan-center-index folk.  Ideally @fpagliughi to be a contributor and reviewer over there for this package would 'end-to-end' the experience of consuming this project.

**Comment by keysight-daryl** [comment]
perhaps @icraggs has some pointers as he just went through something similar.

**Comment by fpagliughi** [comment]
I literally know nothing about Conan. I, and my customers using this project, use CMake. There are a number of issues with the CMake in this project that need to be cleaned up so that it would be easier for client apps to use, particularly making the inclusion of the underlying C lib easier for those who just use the C++ API. 

If there are things that can also be done to make it easier to include in Conan, that would be fine, so long as they don't interfere in direct CMake usage. Is there a list of best practices for CMake for use with Conan?

**Comment by keysight-daryl** [comment]
I'm no expert either however our company only consumes conan packages so at the end of the day that's what matters most to us.  The guys at the conan-center-index however are quite clever with these presumed best practices so perhaps they might be the best way to help kill 2 birds with one stone per say.  They currently support this project with a conan package so I would recommend just shooting some of those devs who have been active on the cpp package a message.  Here is a recent issue they just resolved with the cpp package in their repo for some context...

https://github.com/conan-io/conan-center-index/issues/3176

**Comment by keysight-daryl** [comment]
actually adopting conan in many ways does a lot of the cleanup work for you that you are thinking is needed.

**Comment by keysight-daryl** [comment]
encouraging @Croydon (https://github.com/Croydon), @uilianries (https://github.com/uilianries), or @danimtb (https://github.com/danimtb) to chime in here incase there is some conan/cmake synergy to be had out of this

**Comment by danimtb** [comment]
Hi all! Thanks a lot for the mention, I think the work of the whole Conan community is helping a lot to improve the build scripts of some libraries and we always try to report the issues to the original repo so everyone benefits from the changes. I see we already got some patches to the CMakeLists files on this repo so those might be a good starting point.

**Comment by geoffrey-vl** [comment]
noticed this was related to https://github.com/eclipse/paho.mqtt.cpp/issues/225
