### ISSUE TITLE
No verbose enough examples, incomplete samples

### ISSUE THREAD

**Issue by hwnBEAST** [eclipse/paho.mqtt.cpp#288]
Examples from src/samples do not explain the usage of this library sufficiently. 

Example1: how to make reliable connection when publishing is not explained (only the subscribe has it).

Example2: it says that persistent memory is needed when implementing QOS 1 or 2 publishing. There is no async example for it. When one from sync publish is used segmentation faults happen when the broker is too slow or when deconstructing the object... Is persistent memory really needed when using sync publisher?

**Comment by fpagliughi** [comment]
Sorry for the slow reply.

First, and most important, if you see a segfault, please submit an issue with details on the error, the output, the platform, etc; and (preferably) info on how to reproduce the problem. Then we can try to get it fixed.

As for the sample apps, different techniques are shown in different samples, but overall, individually, they are meant to be simple to introduce different concepts. For example, the technique to keep a reliable connection is the same for a publisher, subscriber, or an application that is both.

The publishers mostly use the default for persistence which uses the local file system. I suppose that can be explained better in the README.

As for more samples, or better docs for the beginner, if you have ideas, please submit them. Pull Requests are always welcome!
