### ISSUE TITLE
does the v1.1 work with  paho.mqtt.c 1.3.5 ? 

### ISSUE THREAD

**Issue by a4z** [eclipse/paho.mqtt.cpp#291]
I can not find any info

is it recommended to stay with paho.mqtt.c 1.3.1 ?
there have been quite some changes, and I guess fixes and improvements since this version in paho.mqtt.c

**Comment by fpagliughi** [comment]
A new version of the C++ library is coming soon that will work with the latest Paho C. Actually I'm waiting on the next C release 1.3.6 which is due out later this month.

It will have some bug fixes, better MQTT v5 coverage, some better CMake usage (I hope), and be validated against that latest C lib. I will update the milestones shortly.

**Comment by a4z** [comment]
Thank you very much for the info! 
I do not close the issue right now since it might serve as information for others, but if you think it should be closed, please do so  @fpagliughi .

**Comment by a4z** [comment]
now with 1.3.6 released, is there a roadmap when to expect the new release ?
(don't want to stress, its just if you have a date soon I can adjust my wok when to update and adopt)

**Comment by keysight-daryl** [comment]
Hoping for the same

**Comment by keysight-daryl** [comment]
Current conan-center-index community is struggling a bit with packaging for even the previous cpp against the 1.3.5 c library however the 1.3.6 has some fundamental options additions and new callbacks for things like persistence encryption.

**Comment by fpagliughi** [comment]
I'm "hoping" for a release by the end of the month (Oct), but I haven't reviewed the latest update to be sure of that. If there are specific new features in the C lib that you folks want covered, please make tickets for them so I can prioritize. I'll update the milestone later this week when I have a better handle on the schedule.

**Comment by a4z** [comment]
Awesome @fpagliughi , thanks a lot for your effort !

**Comment by keysight-daryl** [comment]
Opened this just to get the topic in the system...

https://github.com/eclipse/paho.mqtt.cpp/issues/296

**Comment by a4z** [comment]
nothing happens, we are meanwhile nearly 3 month later, that's nothing you want to wait for if you plan to use this in production

**Comment by fpagliughi** [comment]
I understand the frustration. But keep in mind that nearly everyone working on Paho these days is an unpaid volunteer. I have never been paid anything to write this library, and I haven't even used the C++ library myself in years. So I spend weeks at a time working on it, and all I get in return is the kindness of strangers.
