### ISSUE TITLE
async_client autoreconnect

### ISSUE THREAD

**Issue by watchmon** [eclipse/paho.mqtt.cpp#292]
I set connect_options.autoreconnect=true, when connect fail ,call async_client.disconnect never finish the autoreconnect, how to fix it

**Comment by fpagliughi** [comment]
The auto-reconnect is meant to restore the connection if it is lost by accident, such as if the server or network go down. In that case, the library will try to restore the connection without your application having to do anything. You can use `set_connection_lost_handler()` and `set_connected_handler()` to register callbacks to be notified when the connection is lost and restored, respectively.

If you call `disconnect()` you are telling the client that you _want_ to disconnect from the server. It will not try to reconnect automatically in that case. You would need to call `reconnect()` later when you do want to reconnect.
