### ISSUE TITLE
Invalid read memory on V1.1

### ISSUE THREAD

**Issue by williamaccuenergy** [eclipse/paho.mqtt.cpp#295]
Hi all,
I built paho-cpp V1.1 in my project. I run my project with valgrind memcheck. I find invalid read memory error. Anyone have ideas? Thanks in advanced.
 
"Qos is configured Qos1."Retained" is no. My application something like:

`pubtok = _pClient->publish(topic.c_str(),postJson.c_str(),postJson.size(),
				_mqttCfg.topic.qos,_mqttCfg.topic.isRetained, nullptr, _listener);

if(NULL == pubtok)
{
	SYSLOG_ERR(LOG_MODULE_MQTT, "token is null!\n");
	return FAILURE;
}`

Valgrind log follows:
`==19042== Thread 27:
==19042== Invalid read of size 8
==19042==    at 0x5DCB39: ListNextElement (LinkedList.c:410)
==19042==    by 0x5E7A95: MQTTAsync_countBufferedMessages (MQTTAsync.c:3456)
==19042==    by 0x5E7BFC: MQTTAsync_send (MQTTAsync.c:3487)
==19042==    by 0x5E7F8C: MQTTAsync_sendMessage (MQTTAsync.c:3560)
==19042==    by 0x601341: mqtt::async_client::publish(std::shared_ptr<mqtt::message const>, void*, mqtt::iaction_listener&) (async_client.cpp:597)
==19042==    by 0x600E7E: mqtt::async_client::publish(mqtt::buffer_ref<char>, void const*, unsigned long, int, bool, void*, mqtt::iaction_listener&) (async_client.cpp:563)
==19042==    by 0x3F8244: MqttClientThread::publishMeter(DevicePostInfo const&) (mqttClientThread.cpp:1073)
==19042==    by 0x3F2ECE: MqttClientThread::handleApplicationTimerEvent() (mqttClientThread.cpp:405)
==19042==    by 0x192B22: AppThreadWithTimer::handleTimerEvent() (appThreadWithTimer.h:278)
==19042==    by 0x193000: AppThreadWithTimer::run() (appThreadWithTimer.h:363)
==19042==    by 0x191DE2: AppThread::runHelper(void*) (appThread.h:125)
==19042==    by 0x4E436DA: start_thread (pthread_create.c:463)
==19042==  Address 0xa4c740c is 12 bytes inside a block of size 40 free'd
==19042==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19042==    by 0x5DBB53: myfree (Heap.c:270)
==19042==    by 0x5DC6F4: ListUnlink (LinkedList.c:226)
==19042==    by 0x5DC756: ListDetach (LinkedList.c:244)
==19042==    by 0x5E0DD3: MQTTAsync_processCommand (MQTTAsync.c:1443)
==19042==    by 0x5E2979: MQTTAsync_sendThread (MQTTAsync.c:1869)
==19042==    by 0x4E436DA: start_thread (pthread_create.c:463)
==19042==    by 0x731BA3E: clone (clone.S:95)
==19042==  Block was alloc'd at
==19042==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19042==    by 0x5DB7AB: mymalloc (Heap.c:189)
==19042==    by 0x5DC368: ListAppend (LinkedList.c:94)
==19042==    by 0x5DFBB3: MQTTAsync_addCommand (MQTTAsync.c:1070)
==19042==    by 0x5E7E3B: MQTTAsync_send (MQTTAsync.c:3529)
==19042==    by 0x5E7F8C: MQTTAsync_sendMessage (MQTTAsync.c:3560)
==19042==    by 0x601341: mqtt::async_client::publish(std::shared_ptr<mqtt::message const>, void*, mqtt::iaction_listener&) (async_client.cpp:597)
==19042==    by 0x600E7E: mqtt::async_client::publish(mqtt::buffer_ref<char>, void const*, unsigned long, int, bool, void*, mqtt::iaction_listener&) (async_client.cpp:563)
==19042==    by 0x3F7BDD: MqttClientThread::publishDI() (mqttClientThread.cpp:992)
==19042==    by 0x3F2E32: MqttClientThread::handleApplicationTimerEvent() (mqttClientThread.cpp:393)
==19042==    by 0x192B22: AppThreadWithTimer::handleTimerEvent() (appThreadWithTimer.h:278)
==19042==    by 0x193000: AppThreadWithTimer::run() (appThreadWithTimer.h:363)
==19042== 

==19042== 1 errors in context 2 of 22:
==19042== Thread 27:
==19042== Invalid read of size 8
==19042==    at 0x5DCB39: ListNextElement (LinkedList.c:410)
==19042==    by 0x5E7A95: MQTTAsync_countBufferedMessages (MQTTAsync.c:3456)
==19042==    by 0x5E7BFC: MQTTAsync_send (MQTTAsync.c:3487)
==19042==    by 0x5E7F8C: MQTTAsync_sendMessage (MQTTAsync.c:3560)
==19042==    by 0x601341: mqtt::async_client::publish(std::shared_ptr<mqtt::message const>, void*, mqtt::iaction_listener&) (async_client.cpp:597)
==19042==    by 0x600E7E: mqtt::async_client::publish(mqtt::buffer_ref<char>, void const*, unsigned long, int, bool, void*, mqtt::iaction_listener&) (async_client.cpp:563)
==19042==    by 0x3F8244: MqttClientThread::publishMeter(DevicePostInfo const&) (mqttClientThread.cpp:1073)
==19042==    by 0x3F2ECE: MqttClientThread::handleApplicationTimerEvent() (mqttClientThread.cpp:405)
==19042==    by 0x192B22: AppThreadWithTimer::handleTimerEvent() (appThreadWithTimer.h:278)
==19042==    by 0x193000: AppThreadWithTimer::run() (appThreadWithTimer.h:363)
==19042==    by 0x191DE2: AppThread::runHelper(void*) (appThread.h:125)
==19042==    by 0x4E436DA: start_thread (pthread_create.c:463)
==19042==  Address 0xa4c740c is 12 bytes inside a block of size 40 free'd
==19042==    at 0x4C30D3B: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19042==    by 0x5DBB53: myfree (Heap.c:270)
==19042==    by 0x5DC6F4: ListUnlink (LinkedList.c:226)
==19042==    by 0x5DC756: ListDetach (LinkedList.c:244)
==19042==    by 0x5E0DD3: MQTTAsync_processCommand (MQTTAsync.c:1443)
==19042==    by 0x5E2979: MQTTAsync_sendThread (MQTTAsync.c:1869)
==19042==    by 0x4E436DA: start_thread (pthread_create.c:463)
==19042==    by 0x731BA3E: clone (clone.S:95)
==19042==  Block was alloc'd at
==19042==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19042==    by 0x5DB7AB: mymalloc (Heap.c:189)
==19042==    by 0x5DC368: ListAppend (LinkedList.c:94)
==19042==    by 0x5DFBB3: MQTTAsync_addCommand (MQTTAsync.c:1070)
==19042==    by 0x5E7E3B: MQTTAsync_send (MQTTAsync.c:3529)
==19042==    by 0x5E7F8C: MQTTAsync_sendMessage (MQTTAsync.c:3560)
==19042==    by 0x601341: mqtt::async_client::publish(std::shared_ptr<mqtt::message const>, void*, mqtt::iaction_listener&) (async_client.cpp:597)
==19042==    by 0x600E7E: mqtt::async_client::publish(mqtt::buffer_ref<char>, void const*, unsigned long, int, bool, void*, mqtt::iaction_listener&) (async_client.cpp:563)
==19042==    by 0x3F7BDD: MqttClientThread::publishDI() (mqttClientThread.cpp:992)
==19042==    by 0x3F2E32: MqttClientThread::handleApplicationTimerEvent() (mqttClientThread.cpp:393)
==19042==    by 0x192B22: AppThreadWithTimer::handleTimerEvent() (appThreadWithTimer.h:278)
==19042==    by 0x193000: AppThreadWithTimer::run() (appThreadWithTimer.h:363)
==19042== `

**Comment by fpagliughi** [comment]
A number of issues have been closed in the C lib in the run up to this next C++ release, and so far this year there have been six or seven updates to the C lib. The new C++ library will require C v1.3.8 or later. I've been running the C++ sample apps with valgrind, and so far it looks good.

I'm going to assume this has all been fixed with the new version, but feel free to reopen this or create a new issue if you find anything in the new versions.
