### ISSUE TITLE
Is it a good idea to have multiple clients in single program when publishing multiple topics?

### ISSUE THREAD

**Issue by phuongtran7** [eclipse/paho.mqtt.cpp#297]
Hi,

I'm so sorry if this is asked already. I couldn't find anything related to publishing.

I'm currently using a single async client and multiple `Topic` objects to publish data. There are around 5 topics, but ultimately it depends on the config at runtime. Each topic is published with different interval, but usually around 100 times per second. Each message is around 1-2000 bytes. The QoS of all message is 0. It currently works rather well with three topics, but I don't know whether this is the right approach in the future where there might be even 10 topics in the config.

So my question would be is it a good idea to create separate client to each of the topic?

On a side note, is there any new on different `message_arrived` callback for each subscribing topic (https://github.com/eclipse/paho.mqtt.cpp/issues/202)?

Thank you so much for your time and help.

**Comment by fpagliughi** [comment]
Yeah that should be fine with a single client.  But, as with any network application there are a lot of variables at play, and the best thing to do is test it out. You should be able to easily mock up a client that generates simulated traffic at the rate you expect, then test it with the board, connection, network, and server that you plan to use.

**Comment by phuongtran7** [comment]
Thank you so much for you reply.

It's great to hear that it should be good with single client. So I don't have to worry about it anymore. But yeah, as you mentioned, I really should test it out to make sure.
