### ISSUE TITLE
CMakeFiles/Makefile2:126: recipe for target 'src/CMakeFiles/paho-cpp-objs.dir/all' failed

### ISSUE THREAD

**Issue by raul-parada** [eclipse/paho.mqtt.cpp#306]
When compiling paho-mqtt-cpp following

```
$ git clone https://github.com/eclipse/paho.mqtt.cpp
$ cd paho.mqtt.cpp
$ cmake -Bbuild -H. -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE
$ sudo cmake --build build/ --target install
$ sudo ldconfig
```

I get:

`rparada@rparada-VirtualBox:~/paho.mqtt.cpp$ sudo cmake --build build/ --target install
[  2%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/async_client.cpp.o
In file included from /home/rparada/paho.mqtt.cpp/src/mqtt/async_client.h:31:0,
                 from /home/rparada/paho.mqtt.cpp/src/async_client.cpp:20:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘void mqtt::create_options::set_send_while_disconnected(bool, bool)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:78:9: error: ‘struct MQTTAsync_createOptions’ has no member named ‘allowDisconnectedSendAtAnyTime’
   opts_.allowDisconnectedSendAtAnyTime = to_int(anyTime);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘bool mqtt::create_options::get_delete_oldest_messages() const’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:113:24: error: ‘const struct MQTTAsync_createOptions’ has no member named ‘deleteOldestMessages’
   return to_bool(opts_.deleteOldestMessages);
                        ^~~~~~~~~~~~~~~~~~~~
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘void mqtt::create_options::set_delete_oldest_messages(bool)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:122:9: error: ‘struct MQTTAsync_createOptions’ has no member named ‘deleteOldestMessages’
   opts_.deleteOldestMessages = to_int(on);
         ^~~~~~~~~~~~~~~~~~~~
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘bool mqtt::create_options::get_restore_messages() const’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:132:24: error: ‘const struct MQTTAsync_createOptions’ has no member named ‘restoreMessages’; did you mean ‘maxBufferedMessages’?
   return to_bool(opts_.restoreMessages);
                        ^~~~~~~~~~~~~~~
                        maxBufferedMessages
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘void mqtt::create_options::set_restore_messages(bool)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:142:9: error: ‘struct MQTTAsync_createOptions’ has no member named ‘restoreMessages’; did you mean ‘maxBufferedMessages’?
   opts_.restoreMessages = to_int(on);
         ^~~~~~~~~~~~~~~
         maxBufferedMessages
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘bool mqtt::create_options::get_persist_qos0() const’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:150:24: error: ‘const struct MQTTAsync_createOptions’ has no member named ‘persistQoS0’
   return to_bool(opts_.persistQoS0);
                        ^~~~~~~~~~~
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘void mqtt::create_options::set_persist_qos0(bool)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:158:9: error: ‘struct MQTTAsync_createOptions’ has no member named ‘persistQoS0’
   opts_.persistQoS0 = to_int(on);
         ^~~~~~~~~~~
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘mqtt::create_options_builder::self& mqtt::create_options_builder::send_while_disconnected(bool, bool)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:196:15: error: ‘struct MQTTAsync_createOptions’ has no member named ‘allowDisconnectedSendAtAnyTime’
   opts_.opts_.allowDisconnectedSendAtAnyTime = to_int(anyTime);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘mqtt::create_options_builder::self& mqtt::create_options_builder::delete_oldest_messages(bool)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:224:15: error: ‘struct MQTTAsync_createOptions’ has no member named ‘deleteOldestMessages’
   opts_.opts_.deleteOldestMessages = to_int(on);
               ^~~~~~~~~~~~~~~~~~~~
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘mqtt::create_options_builder::self& mqtt::create_options_builder::restore_messages(bool)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:236:15: error: ‘struct MQTTAsync_createOptions’ has no member named ‘restoreMessages’; did you mean ‘maxBufferedMessages’?
   opts_.opts_.restoreMessages = to_int(on);
               ^~~~~~~~~~~~~~~
               maxBufferedMessages
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h: In member function ‘mqtt::create_options_builder::self& mqtt::create_options_builder::persist_qos0(bool)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/create_options.h:246:15: error: ‘struct MQTTAsync_createOptions’ has no member named ‘persistQoS0’
   opts_.opts_.persistQoS0 = to_int(on);
               ^~~~~~~~~~~
In file included from /home/rparada/paho.mqtt.cpp/src/mqtt/iasync_client.h:33:0,
                 from /home/rparada/paho.mqtt.cpp/src/mqtt/async_client.h:41,
                 from /home/rparada/paho.mqtt.cpp/src/async_client.cpp:20:
/home/rparada/paho.mqtt.cpp/src/mqtt/connect_options.h: In member function ‘void mqtt::connect_options::set_http_headers(const mqtt::name_value_collection&)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/connect_options.h:458:9: error: ‘struct MQTTAsync_connectOptions’ has no member named ‘httpHeaders’
   opts_.httpHeaders = httpHeaders_.empty() ? nullptr : httpHeaders_.c_arr();
         ^~~~~~~~~~~
/home/rparada/paho.mqtt.cpp/src/mqtt/connect_options.h: In member function ‘void mqtt::connect_options::set_http_headers(mqtt::name_value_collection&&)’:
/home/rparada/paho.mqtt.cpp/src/mqtt/connect_options.h:466:9: error: ‘struct MQTTAsync_connectOptions’ has no member named ‘httpHeaders’
   opts_.httpHeaders = httpHeaders_.empty() ? nullptr : httpHeaders_.c_arr();
         ^~~~~~~~~~~
src/CMakeFiles/paho-cpp-objs.dir/build.make:62: recipe for target 'src/CMakeFiles/paho-cpp-objs.dir/async_client.cpp.o' failed
make[2]: *** [src/CMakeFiles/paho-cpp-objs.dir/async_client.cpp.o] Error 1
CMakeFiles/Makefile2:126: recipe for target 'src/CMakeFiles/paho-cpp-objs.dir/all' failed
make[1]: *** [src/CMakeFiles/paho-cpp-objs.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by SebastianHan93** [comment]
The branches require Paho C v1.3.6
