### ISSUE TITLE
I would like to contribute with a tutorial

### ISSUE THREAD

**Issue by pedrombmachado** [eclipse/paho.mqtt.cpp#308]
Dear Paho MQTT team,
  I would like to contribute with a tutorial for users that are starting with MQTT and C++.
The link is available here https://www.blogger.com/blog/post/edit/1063912112697900240/5160246028692915590.
I would kindly ask for suggestions and recommendations. 
Kind Regards,
Pedro

**Comment by fpagliughi** [comment]
Hi Pedro. Thanks. Is there a way I can see/read the post without having to set up a full account on blogger.com?

**Comment by pedrombmachado** [comment]
HI @fpagliughi 
  Please check if you you can open the following [shared document](https://docs.google.com/document/d/1ty_ndFX3VxAccUCkLl0YWAlxrZeAV65c4boh-2N2mJk/edit?usp=sharing).
