### ISSUE TITLE
Compiling paho.mqtt.cpp results in error

### ISSUE THREAD

**Issue by crisdeodates** [eclipse/paho.mqtt.cpp#312]
I am trying to compile the paho.mqtt.cpp libraries. Though the documentation recommends v1.3.7 or v1.3.8 (which is not yet released) of the base paho.mqtt.c, this [comment](https://github.com/eclipse/paho.mqtt.cpp/issues/225#issuecomment-562559095) recommended mqtt c v1.3.1 & mqtt c++ v1.1

The issue is, whichever combination of versions is used, the "sudo cmake --build build/ --target install" step fails all the time.
Any idea how to fix this? 

Here is the output of the operation:

c@c0:~/MQTT/paho.mqtt.cpp$ sudo cmake --build build/ --target install
Scanning dependencies of target paho-cpp-objs
[  2%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/async_client.cpp.o
[  4%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/client.cpp.o
[  6%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/disconnect_options.cpp.o
[  9%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/iclient_persistence.cpp.o
[ 11%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/message.cpp.o
[ 13%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/properties.cpp.o
[ 16%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/response_options.cpp.o
[ 18%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/ssl_options.cpp.o
[ 20%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/string_collection.cpp.o
[ 23%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/subscribe_options.cpp.o
[ 25%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/token.cpp.o
[ 27%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/topic.cpp.o
[ 30%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/connect_options.cpp.o
[ 32%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/will_options.cpp.o
[ 32%] Built target paho-cpp-objs
Scanning dependencies of target paho-mqttpp3
[ 34%] Linking CXX shared library libpaho-mqttpp3.so
[ 34%] Built target paho-mqttpp3
Scanning dependencies of target paho-mqttpp3-static
[ 37%] Linking CXX static library libpaho-mqttpp3.a
[ 37%] Built target paho-mqttpp3-static
Scanning dependencies of target Doxyfile.cmake.target
[ 39%] Generating API documentation with Doxygen
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...
Searching for files in directory /home/MQTT/paho.mqtt.cpp/src/mqtt
Reading and parsing tag files
Parsing files
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/async_client.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/async_client.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/buffer_ref.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/buffer_ref.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/buffer_view.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/buffer_view.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/callback.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/callback.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/client.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/client.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/connect_options.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/connect_options.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/delivery_token.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/delivery_token.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/disconnect_options.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/disconnect_options.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/exception.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/exception.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/iaction_listener.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/iaction_listener.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/iasync_client.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/iasync_client.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/iclient_persistence.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/iclient_persistence.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/message.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/message.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/properties.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/properties.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/response_options.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/response_options.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/server_response.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/server_response.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/ssl_options.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/ssl_options.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/string_collection.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/string_collection.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/subscribe_options.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/subscribe_options.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/thread_queue.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/thread_queue.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/token.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/token.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/topic.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/topic.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/types.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/types.h...
Preprocessing /home/MQTT/paho.mqtt.cpp/src/mqtt/will_options.h...
Parsing file /home/MQTT/paho.mqtt.cpp/src/mqtt/will_options.h...
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
Associating documentation with classes...
Computing nesting relations for classes...
Building example list...
Searching for enumerations...
Searching for documented typedefs...
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Building interface member list...
Building member list...
Searching for friends...
Searching for documented defines...
Computing class inheritance relations...
Computing class usage relations...
Flushing cached template relations that have become invalid...
Computing class relations...
Add enum values to enums...
Searching for member function documentation...
Creating members for template instances...
Building page list...
Search for main page...
Computing page relations...
Determining the scope of groups...
Sorting lists...
Freeing entry tree
Determining which enums are documented
Computing member relations...
Building full member lists recursively...
Adding members to member groups.
Computing member references...
Inheriting documentation...
Generating disk names...
Adding source references...
Adding xrefitems...
Sorting member lists...
Computing dependencies between directories...
Generating citations page...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Generating style sheet...
Generating search indices...
Generating example documentation...
Generating file sources...
Generating code for file async_client.h...
Generating code for file buffer_ref.h...
Generating code for file buffer_view.h...
Generating code for file callback.h...
Generating code for file client.h...
Generating code for file connect_options.h...
Generating code for file delivery_token.h...
Generating code for file disconnect_options.h...
Generating code for file exception.h...
Generating code for file iaction_listener.h...
Generating code for file iasync_client.h...
Generating code for file iclient_persistence.h...
Generating code for file message.h...
Generating code for file properties.h...
Generating code for file response_options.h...
Generating code for file server_response.h...
Generating code for file ssl_options.h...
Generating code for file string_collection.h...
Generating code for file subscribe_options.h...
Generating code for file thread_queue.h...
Generating code for file token.h...
Generating code for file topic.h...
Generating code for file types.h...
Generating code for file will_options.h...
Generating file documentation...
Generating docs for file async_client.h...
Generating docs for file buffer_ref.h...
Generating docs for file buffer_view.h...
Generating docs for file callback.h...
Generating docs for file client.h...
Generating docs for file connect_options.h...
Generating docs for file delivery_token.h...
Generating docs for file disconnect_options.h...
Generating docs for file exception.h...
Generating docs for file iaction_listener.h...
Generating docs for file iasync_client.h...
Generating docs for file iclient_persistence.h...
Generating docs for file message.h...
Generating docs for file properties.h...
Generating docs for file response_options.h...
Generating docs for file server_response.h...
Generating docs for file ssl_options.h...
Generating docs for file string_collection.h...
Generating docs for file subscribe_options.h...
Generating docs for file thread_queue.h...
Generating docs for file token.h...
Generating docs for file topic.h...
Generating docs for file types.h...
Generating docs for file will_options.h...
Generating page documentation...
Generating group documentation...
Generating class documentation...
Generating namespace index...
Generating docs for namespaceMQTT
Generating docs for compoundMQTT::async_client...
/home/MQTT/paho.mqtt.cpp/src/mqtt/async_client.h:516: warning: The following parameters ofMQTT::async_client::subscribe(const string &topicFilter, int qos, const subscribe_options &opts=subscribe_options()) are not documented:
  parameter 'opts'
/home/MQTT/paho.mqtt.cpp/src/mqtt/async_client.h:533: warning: The following parameters ofMQTT::async_client::subscribe(const string &topicFilter, int qos, void *userContext, iaction_listener &cb, const subscribe_options &opts=subscribe_options()) are not documented:
  parameter 'opts'
/home/MQTT/paho.mqtt.cpp/src/mqtt/async_client.h:547: warning: The following parameters ofMQTT::async_client::subscribe(const_string_collection_ptr topicFilters, const qos_collection &qos, const std::vector< subscribe_options > &opts=std::vector< subscribe_options >()) are not documented:
  parameter 'opts'
/home/MQTT/paho.mqtt.cpp/src/mqtt/async_client.h:564: warning: The following parameters ofMQTT::async_client::subscribe(const_string_collection_ptr topicFilters, const qos_collection &qos, void *userContext, iaction_listener &cb, const std::vector< subscribe_options > &opts=std::vector< subscribe_options >()) are not documented:
  parameter 'opts'
/home/MQTT/paho.mqtt.cpp/src/mqtt/async_client.h:675: warning: argument 'msg' of command @param is not found in the argument list ofMQTT::async_client::try_consume_message_until(const std::chrono::time_point< Clock, Duration > &absTime)
Generating docs for compoundMQTT::buffer_ref...
Generating docs for compoundMQTT::buffer_view...
Generating docs for compoundMQTT::callback...
/home/MQTT/paho.mqtt.cpp/src/mqtt/callback.h:55: warning: argument 'cause' of command @param is not found in the argument list ofMQTT::callback::connected(const string &)
/home/MQTT/paho.mqtt.cpp/src/mqtt/callback.h:63: warning: argument 'cause' of command @param is not found in the argument list ofMQTT::callback::connection_lost(const string &)
/home/MQTT/paho.mqtt.cpp/src/mqtt/callback.h:68: warning: argument 'msg' of command @param is not found in the argument list ofMQTT::callback::message_arrived(const_message_ptr)
/home/MQTT/paho.mqtt.cpp/src/mqtt/callback.h:73: warning: argument 'tok' of command @param is not found in the argument list ofMQTT::callback::delivery_complete(delivery_token_ptr)
Generating docs for compoundMQTT::client...
Generating docs for compoundMQTT::connect_options...
Generating docs for compoundMQTT::connect_response...
Generating docs for compoundMQTT::delivery_response_options...
/home/MQTT/paho.mqtt.cpp/src/mqtt/response_options.h:104: warning: The following parameters ofMQTT::delivery_response_options::delivery_response_options(const delivery_token_ptr &dtok, intMQTTVersion=MQTTVERSION_DEFAULT) are not documented:
  parameter 'mqttVersion'
Generating docs for compoundMQTT::delivery_token...
Generating docs for compoundMQTT::disconnect_options...
Generating docs for compoundMQTT::exception...
/home/MQTT/paho.mqtt.cpp/src/mqtt/exception.h:114: warning: The following parameters ofMQTT::exception::printable_error(int rc, int reasonCode=ReasonCode::SUCCESS, const string &msg=string()) are not documented:
  parameter 'reasonCode'
Generating docs for compoundMQTT::iaction_listener...
Generating docs for compoundMQTT::iasync_client...
Generating docs for compoundMQTT::iclient_persistence...
Generating docs for compoundMQTT::message...
Generating docs for compoundMQTT::missing_response...
Generating docs for compoundMQTT::persistence_exception...
Generating docs for compoundMQTT::properties...
/home/MQTT/paho.mqtt.cpp/src/mqtt/properties.h:262: warning: argument 'An' of command @param is not found in the argument list ofMQTT::properties::properties(std::initializer_list< property > props)
/home/MQTT/paho.mqtt.cpp/src/mqtt/properties.h:265: warning: The following parameters ofMQTT::properties::properties(std::initializer_list< property > props) are not documented:
  parameter 'props'
/home/MQTT/paho.mqtt.cpp/src/mqtt/properties.h:288: warning: argument 'rht' of command @param is not found in the argument list ofMQTT::properties::operator=(properties &&rhs)
/home/MQTT/paho.mqtt.cpp/src/mqtt/properties.h:292: warning: The following parameters ofMQTT::properties::operator=(properties &&rhs) are not documented:
  parameter 'rhs'
Generating docs for compoundMQTT::property...
Generating docs for compoundMQTT::response_options...
/home/MQTT/paho.mqtt.cpp/src/mqtt/response_options.h:57: warning: The following parameters ofMQTT::response_options::response_options(const token_ptr &tok, intMQTTVersion=MQTTVERSION_DEFAULT) are not documented:
  parameter 'mqttVersion'
Generating docs for compoundMQTT::security_exception...
Generating docs for compoundMQTT::server_response...
Generating docs for compoundMQTT::ssl_options...
Generating docs for compoundMQTT::string_collection...
Generating docs for compoundMQTT::subscribe_options...
Generating docs for compoundMQTT::subscribe_response...
Generating docs for compoundMQTT::thread_queue...
Generating docs for compoundMQTT::token...
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:197: warning: The following parameters ofMQTT::token::token(Type typ, iasync_client &cli) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:207: warning: The following parameters ofMQTT::token::token(Type typ, iasync_client &cli, void *userContext, iaction_listener &cb) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:215: warning: The following parameters ofMQTT::token::token(Type typ, iasync_client &cli, const string &topic) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:226: warning: The following parameters ofMQTT::token::token(Type typ, iasync_client &cli, const string &topic, void *userContext, iaction_listener &cb) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:235: warning: The following parameters ofMQTT::token::token(Type typ, iasync_client &cli, const_string_collection_ptr topics) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:245: warning: The following parameters ofMQTT::token::token(Type typ, iasync_client &cli, const_string_collection_ptr topics, void *userContext, iaction_listener &cb) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:252: warning: The following parameters ofMQTT::token::token(Type typ, iasync_client &cli,MQTTAsync_token tok) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:262: warning: The following parameters ofMQTT::token::create(Type typ, iasync_client &cli) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:273: warning: The following parameters ofMQTT::token::create(Type typ, iasync_client &cli, void *userContext, iaction_listener &cb) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:282: warning: The following parameters ofMQTT::token::create(Type typ, iasync_client &cli, const string &topic) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:294: warning: The following parameters ofMQTT::token::create(Type typ, iasync_client &cli, const string &topic, void *userContext, iaction_listener &cb) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:303: warning: The following parameters ofMQTT::token::create(Type typ, iasync_client &cli, const_string_collection_ptr topics) are not documented:
  parameter 'typ'
/home/MQTT/paho.mqtt.cpp/src/mqtt/token.h:315: warning: The following parameters ofMQTT::token::create(Type typ, iasync_client &cli, const_string_collection_ptr topics, void *userContext, iaction_listener &cb) are not documented:
  parameter 'typ'
Generating docs for compoundMQTT::topic...
Generating docs for compoundMQTT::unsubscribe_response...
Generating docs for compoundMQTT::will_options...
Generating graph info page...
Generating directory documentation...
Generating index page...
Generating page index...
Generating module index...
Generating namespace index...
Generating namespace member index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
writing tag file...
lookup cache used 1257/65536 hits=7148 misses=1312
finished...
[ 39%] Built target Doxyfile.cmake.target
Scanning dependencies of target doc
[ 39%] Built target doc
Scanning dependencies of target sync_consume
[ 41%] Building CXX object src/samples/CMakeFiles/sync_consume.dir/sync_consume.cpp.o
[ 44%] Linking CXX executable sync_consume
../libpaho-mqttpp3.so.1.1.0: undefined reference to `Log'
collect2: error: ld returned 1 exit status
src/samples/CMakeFiles/sync_consume.dir/build.make:98: recipe for target 'src/samples/sync_consume' failed
make[2]: *** [src/samples/sync_consume] Error 1
CMakeFiles/Makefile2:350: recipe for target 'src/samples/CMakeFiles/sync_consume.dir/all' failed
make[1]: *** [src/samples/CMakeFiles/sync_consume.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fpagliughi** [comment]
See #211, #233, #235, and all the other issues that reported this same problem.

But your post does remind me that I should clean up some of those Doxygen warnings, too!

To answer your other confusion about versions...

The pre-release for C++ v1.2.0 is sitting in the GitHub `master` branch, and should be out this week. That will require at least C v1.3.7 to compile, but there's a known bug in regard to user-persistence when those two are used together. (If you don't need user persistence C v1.3.7 works fine). So I have been waiting for the C v1.3.8 which should be out any day now...

If you re-examine the README, you may see that I made note of this.

**Comment by fpagliughi** [comment]
The C v1.3.8 was released today, and the C++ version should follow some time today which fixes this. In addition, I may go back and patch the 1.1.0 version (to a 1.1.1) to fix the build issue there also.

If you still see a problem after that, feel free to reopen this issue or create a new one.
