### ISSUE TITLE
Getting Error  error: ‘struct MQTTAsync_createOptions’ has no member named ‘allowDisconnectedSendAtAnyTime’ 

### ISSUE THREAD

**Issue by sdhir93** [eclipse/paho.mqtt.cpp#314]
Followed the latest steps, but getting the error

 error: ‘struct MQTTAsync_createOptions’ has no member named ‘allowDisconnectedSendAtAnyTime’
   90 |   opts_.allowDisconnectedSendAtAnyTime = to_int(anyTime);

**Comment by fpagliughi** [comment]
v1.2 of the C++ library requires v 1.3.8 of the Paho C lib.

**Comment by sdhir93** [comment]
Yes, I used v1.2 of C++ Library and checked out v 1.3.8 of the C version. I can see the struct definition in the MQTTAsync.h file. It is not being "seen" during compilation of C++ Lib

**Comment by sdhir93** [comment]
One of the libraries was getting compiled using a cross compiler and hence the error. Works fine now. Closing, thanks!
