### ISSUE TITLE
raspberry pi samples

### ISSUE THREAD

**Issue by arnold-b** [eclipse/paho.mqtt.cpp#315]
Hello, 
how to get the samples compiled. 

root@Rasp-VPN:~/paho.mqtt.cpp/src/samples# cmake .
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.13)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /root/paho.mqtt.cpp/src/samples
root@Rasp-VPN:~/paho.mqtt.cpp/src/samples#

**Comment by sisco0** [comment]
Have a good day, now you could run `make` in order for to compile under _Raspbian_.

**Comment by arnold-b** [comment]
Hey, thanks but affter make i get this:

[  3%] Linking CXX executable ws_publish
/usr/bin/ld: CMakeFiles/ws_publish.dir/ws_publish.o: in function `main':
ws_publish.cpp:(.text+0x1e8): undefined reference to `mqtt::async_client::async_client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, mqtt::iclient_persistence*)'
/usr/bin/ld: ws_publish.cpp:(.text+0x2f8): undefined reference to `mqtt::connect_options::connect_options(mqtt::connect_options const&)'
/usr/bin/ld: ws_publish.cpp:(.text+0x30c): undefined reference to `mqtt::async_client::connect(mqtt::connect_options)'
/usr/bin/ld: ws_publish.cpp:(.text+0x40c): undefined reference to `mqtt::async_client::publish(std::shared_ptr<mqtt::message const>)'
/usr/bin/ld: ws_publish.cpp:(.text+0x554): undefined reference to `mqtt::async_client::~async_client()'
/usr/bin/ld: ws_publish.cpp:(.text+0x768): undefined reference to `mqtt::async_client::~async_client()'
/usr/bin/ld: CMakeFiles/ws_publish.dir/ws_publish.o: in function `mqtt::exception::error_str[abi:cxx11](int)':
ws_publish.cpp:(.text._ZN4mqtt9exception9error_strB5cxx11Ei[_ZN4mqtt9exception9error_strB5cxx11Ei]+0x18): undefined reference to `MQTTAsync_strerror'
/usr/bin/ld: CMakeFiles/ws_publish.dir/ws_publish.o: in function `mqtt::exception::reason_code_str[abi:cxx11](int)':
ws_publish.cpp:(.text._ZN4mqtt9exception15reason_code_strB5cxx11Ei[_ZN4mqtt9exception15reason_code_strB5cxx11Ei]+0x28): undefined reference to `MQTTReasonCode_toString'
/usr/bin/ld: CMakeFiles/ws_publish.dir/ws_publish.o: in function `mqtt::properties::~properties()':
ws_publish.cpp:(.text._ZN4mqtt10propertiesD2Ev[_ZN4mqtt10propertiesD5Ev]+0x18): undefined reference to `MQTTProperties_free'
/usr/bin/ld: CMakeFiles/ws_publish.dir/ws_publish.o: in function `mqtt::connect_options_builder::connect_options_builder()':
ws_publish.cpp:(.text._ZN4mqtt23connect_options_builderC2Ev[_ZN4mqtt23connect_options_builderC5Ev]+0x18): undefined reference to `mqtt::connect_options::connect_options()'
/usr/bin/ld: CMakeFiles/ws_publish.dir/ws_publish.o: in function `mqtt::connect_options_builder::http_proxy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ws_publish.cpp:(.text._ZN4mqtt23connect_options_builder10http_proxyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN4mqtt23connect_options_builder10http_proxyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x20): undefined reference to `mqtt::connect_options::set_http_proxy(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/ws_publish.dir/ws_publish.o: in function `mqtt::connect_options_builder::finalize()':
ws_publish.cpp:(.text._ZN4mqtt23connect_options_builder8finalizeEv[_ZN4mqtt23connect_options_builder8finalizeEv]+0x20): undefined reference to `mqtt::connect_options::connect_options(mqtt::connect_options const&)'
/usr/bin/ld: CMakeFiles/ws_publish.dir/ws_publish.o: in function `mqtt::async_client::disconnect()':
ws_publish.cpp:(.text._ZN4mqtt12async_client10disconnectEv[_ZN4mqtt12async_client10disconnectEv]+0x2c): undefined reference to `mqtt::disconnect_options::disconnect_options()'
/usr/bin/ld: CMakeFiles/ws_publish.dir/ws_publish.o: in function `void __gnu_cxx::new_allocator<mqtt::message>::construct<mqtt::message, mqtt::buffer_ref<char>, mqtt::buffer_ref<char>, int&, bool&, mqtt::properties const&>(mqtt::message*, mqtt::buffer_ref<char>&&, mqtt::buffer_ref<char>&&, int&, bool&, mqtt::properties const&)':
ws_publish.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN4mqtt7messageEE9constructIS2_JNS1_10buffer_refIcEES6_RiRbRKNS1_10propertiesEEEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorIN4mqtt7messageEE9constructIS2_JNS1_10buffer_refIcEES6_RiRbRKNS1_10propertiesEEEEvPT_DpOT0_]+0xb4): undefined reference to `mqtt::message::message(mqtt::buffer_ref<char>, mqtt::buffer_ref<char>, int, bool, mqtt::properties const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ws_publish.dir/build.make:84: ws_publish] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/ws_publish.dir/all] Fehler 2
make: *** [Makefile:130: all] Fehler 2
root@Rasp-VPN:~/paho.mqtt.cpp/src/samples#

**Comment by sisco0** [comment]
That error tells about the mqtt library not passed to the linker.

**Comment by arnold-b** [comment]
I installed paho after that i tried to test the samples. So i expect everything should work. 
But Thanks 

then i use for this funktion stm or esp development. This at least is working without searching sample errors
