### ISSUE TITLE
async_client: unblock delivery_token::wait_for() during shutdown

### ISSUE THREAD

**Issue by gambels** [eclipse/paho.mqtt.cpp#319]
Hello,

Is it possible to unblock the delivery_token::wait_for(long timeout) before the function has timed out?

I'm using the async_client in my application, which is publishing messages in several threads. To check, if the message has been delivered, the wait_for() function is used.

Now, I want to shutdown the application immediately without waiting for any timeouts.

I would be very pleased to get any hints on whether this is possible.

Best Regards,
Sven

**Comment by icraggs** [comment]
Now also raised in the C client repo too: https://github.com/eclipse/paho.mqtt.c/issues/1057

**Comment by fpagliughi** [comment]
Yes, it would nice to handle this inside the C client. Let's take the discussion over there.

**Comment by gambels** [comment]
Closed issue because also raised in the C client repo...
