### ISSUE TITLE
call clientSockCompare function, cpu 100%

### ISSUE THREAD

**Issue by LD-keep** [eclipse/paho.mqtt.cpp#320]
call clientSockCompare function, cpu 100%

**Comment by fpagliughi** [comment]
I don't know what this means. Can you explain more.

**Comment by icraggs** [comment]
This user has opened an issue for the same situation on the C repo: https://github.com/eclipse/paho.mqtt.c/issues/1044

I suggest we deal with it there.  I've asked for more information.

**Comment by fpagliughi** [comment]
OK
