### ISSUE TITLE
Examples for hooking up a custom TLS stack

### ISSUE THREAD

**Issue by sarenameas** [eclipse/paho.mqtt.cpp#324]
Hello,

At a quick look through it seems we are pushed into using OpenSSL for Linux. I have a custom TLS stack and I want to know if there a way for me to create the connection outside of the library and register some secure socket read and write callback? Could you please link me to some example code?

Thanks,
Sarena

**Comment by fpagliughi** [comment]
The C++ client is just a wrapper around Paho C which handles all of the actual network I/O. So, with the existing implementation, if this feature were to be available, it would be through the C library. Unfortunately, although this request has come up a few times, I don't think there is any way to do this with the C library the way it's currently implemented.

But maybe bring the issue up there to get more info:
https://github.com/eclipse/paho.mqtt.c/issues

**Comment by sarenameas** [comment]
Thanks!
