### ISSUE TITLE
v1.2.0 Using the new SSL error handler callback  cause crash in on_error()

### ISSUE THREAD

**Issue by Pascal-Fremaux** [eclipse/paho.mqtt.cpp#325]
In our client we used the Paho C SSL error handler in our own wrapper (only the cb ptr, not the context) but with 1.2.0 we switched on the official set_err_handler(). But on testing we encountered crashes with the new version.

Our investigations has shown that the C++ ssl_option ptr reported in on_error() was on invalid memory.
Analysis took time, but we finally understand that ssl_option::set_err_handler()/on_error() have one assumption which is not verified by the async_client: of course the ssl_option object memory must live until the on_error is called; so the retrieved context pointer can point on valid memory with a ssl_option object inside.

Problem is in the  async_client::connect() methods: 
The connect_option object (containing the ssl_option object, needed for the pointer validity) is passed by copy, so its scope life ends with the connect() method end. But this memory is used later by the on_error() callback, and it then points on invalid memory (that might be not overwritten, when you are lucky in the bad way).
If you want to pass a context void* to a callback, you must be sure that this memory still contain the data you want when the callback is called.

There are several possible solutions to ensure the ssl_option object is still alive on error completion of the async connect(), I have chosen the simplest for me: copy the connect_options into the async_client class, so it lives more than necessary (from async API connect() to on_error() call).

Here is my quick patch
```
diff --git a/src/async_client.cpp b/src/async_client.cpp
index 174e61ef16f6eddf3276b848022bdee02905b232..d01b627ef258f946047fbf27e616c3bd63230a41 100644
--- a/src/async_client.cpp
+++ b/src/async_client.cpp
@@ -442,9 +442,11 @@ token_ptr async_client::connect()
 
 token_ptr async_client::connect(connect_options opts)
 {
+	// save local version to secure the connect_options pointers
+	connOpts_ = opts;
 	// TODO: We really should get (or update) this value from the response
 	//  	(when the server confirms the requested version)
-	mqttVersion_ = opts.opts_.MQTTVersion;
+	mqttVersion_ = connOpts_.opts_.MQTTVersion;
 
 	// TODO: If connTok_ is non-null, there could be a pending connect
 	// which might complete after creating/assigning a new one. If that
@@ -455,9 +457,9 @@ token_ptr async_client::connect(connect_options opts)
 	connTok_ = token::create(token::Type::CONNECT, *this);
 	add_token(connTok_);
 
-	opts.set_token(connTok_);
+	connOpts_.set_token(connTok_);
 
-	int rc = MQTTAsync_connect(cli_, &opts.opts_);
+	int rc = MQTTAsync_connect(cli_, &connOpts_.opts_);
 
 	if (rc != MQTTASYNC_SUCCESS) {
 		remove_token(connTok_);
@@ -471,17 +473,19 @@ token_ptr async_client::connect(connect_options opts)
 token_ptr async_client::connect(connect_options opts, void* userContext,
 										iaction_listener& cb)
 {
+	// save local version to secure the connect_options pointers
+	connOpts_ = opts;
 	// TODO: We really should get this value from the response (when
 	// 		the server confirms the requested version)
-	mqttVersion_ = opts.opts_.MQTTVersion;
+	mqttVersion_ = connOpts_.opts_.MQTTVersion;
 
 	auto tmpTok = connTok_;
 	connTok_ = token::create(token::Type::CONNECT, *this, userContext, cb);
 	add_token(connTok_);
 
-	opts.set_token(connTok_);
+	connOpts_.set_token(connTok_);
 
-	int rc = MQTTAsync_connect(cli_, &opts.opts_);
+	int rc = MQTTAsync_connect(cli_, &connOpts_.opts_);
 
 	if (rc != MQTTASYNC_SUCCESS) {
 		remove_token(connTok_);
diff --git a/src/mqtt/async_client.h b/src/mqtt/async_client.h
index 63bb80537379a737b3bf4218c13b7d6ce62e3819..24adc7e574d868c460099312ff55f80afcadc0cb 100644
--- a/src/mqtt/async_client.h
+++ b/src/mqtt/async_client.h
@@ -129,6 +129,8 @@ private:
 	std::list<delivery_token_ptr> pendingDeliveryTokens_;
 	/** A queue of messages for consumer API */
 	consumer_queue_type que_;
+	/** connect options saved */
+	connect_options connOpts_;
 
 	/** Callbacks from the C library */
 	static void on_connected(void* context, char* cause);
```

What is strange is that your sample (async_publish) do not crash on SSL errors (I tested it when I wanted to know if it came from our code). (Using some static code checker would probably raise an issue)
I do not know the true reason, it can be pure luck due to simple code (everything alive in the main, short code, nothing taking the memory after...), or some side effect from a compiler optimisation (not a specialist, in your sample might not create the local method copy and use the main object directly).

We do not use the PSK callback, but the problem (and the solution) is the same as it use the same pattern/objects.

**Comment by zorane** [comment]
Any update on this issue?

**Comment by fpagliughi** [comment]
I'll have a look at it. IIRC, the client used to cache the connect options to do manual reconnects, but when the C client added that capability internally, I probably removed the cached options to simplify the wrapper. Maybe that broke something.

I will have a look in a couple of days.

**Comment by zorane** [comment]
Have you had the time to take a look at this?

**Comment by gueldenstone** [comment]
Any news on this one?

**Comment by gueldenstone** [comment]
@Pascal-Fremaux Your Fix seems pretty good for now. I'd like to submit a PR with your changes to push development on this issue. Are you ok with that? (Don't want to take credit for your work, just trying to help :))

**Comment by AdrienMatricon** [comment]
Any news on this issue ? I encountered it recently, using paho.mqtt.cpp 1.2.0 and paho.mqtt.c 1.3.8 on Ubuntu

**Comment by fpagliughi** [comment]
I'm still testing for the release, but not seeing a problem. Anyone should feel free to re-open if they still have a problem related to this.
