### ISSUE TITLE
[ ERROR ] [ ERROR ] MQTT error [-8]: Bad structure

### ISSUE THREAD

**Issue by AndBobsYourUncle** [eclipse/paho.mqtt.cpp#327]
Hello, I have built a project before using this with no issues.

However, now I am getting this error:
```
[ ERROR ] [ ERROR ] MQTT error [-8]: Bad structure
```

When calling this:
```
        std::string address = "tcp://192.168.1.51:1883";
        std::string client = "some-client";

        mqtt::async_client cli(address, client);
```

I have absolutely no idea why this is failing like this. I have followed the instructions _exactly_ as described in the readme for building both paho.mqtt.c and paho.mqtt.cpp.

Any ideas on why this might be happening?

**Comment by AndBobsYourUncle** [comment]
Also, the compiled sample project also fails in the exact same way:

```
$ ./async_publish
Initializing for server 'tcp://localhost:1883'...
terminate called after throwing an instance of 'mqtt::exception'
  what():  MQTT error [-8]: Bad structure
Aborted (core dumped)
```

**Comment by AndBobsYourUncle** [comment]
Something _really_ interesting...

So, I started the VM fresh with Ubuntu 18.04 LTS, and built the two packages (the C and CPP) using the readme, again, just as it says to do.

The sample worked.

However, I went to install some other packages that I need for other various things that will run on this VM, and the sample that was already compiled and had worked just started returning that same `MQTT error [-8]: Bad structure` error.

Seems like there is _some_ sort of dependency that gets installed that changes how it's all linked together? I'm at a loss though.

**Comment by fpagliughi** [comment]
I would be interested to hear what package did this!

Also... are you using the latest releases of both the C and C++ libraries?

**Comment by AndBobsYourUncle** [comment]
These are the precise steps I followed:

```
$ git clone https://github.com/eclipse/paho.mqtt.c.git
$ cd paho.mqtt.c
$ git checkout v1.3.8

$ cmake -Bbuild -H. -DPAHO_ENABLE_TESTING=OFF -DPAHO_BUILD_STATIC=ON \
    -DPAHO_WITH_SSL=ON -DPAHO_HIGH_PERFORMANCE=ON
$ sudo cmake --build build/ --target install
$ sudo ldconfig

$ git clone https://github.com/eclipse/paho.mqtt.cpp
$ cd paho.mqtt.cpp
$ git checkout v1.2.0

$ cmake -Bbuild -H. -DPAHO_WITH_SSL=ON -DPAHO_BUILD_SHARED=ON -DPAHO_BUILD_DOCUMENTATION=FALSE
$ sudo cmake --build build/ --target install
$ sudo ldconfig
```

Also, after CPP sample stopped working and was giving the error, I tried rebuilding it by following the steps again but the sample still gives that error.

Is there any way to figure this out? I'm _assuming_ that it is something to do with the communication between the CPP library and the C library, as that error is something about the eyecatcher or version not matching within the struct.

I tried figuring out what the dependencies were for both these libraries, to see if perhaps a new version of a dependency was installed, but I'm unsure how I'd check this or where to look.

**Comment by AndBobsYourUncle** [comment]
Any help would be greatly appreciated. I'm a programmer as my full-time job, however, cross communication between C and C++ is something that I have no real previous experience in.

**Comment by fpagliughi** [comment]
The C++ library just wraps the C one and provides an API that is (hopefully) easier to use in a C++ app. The C lib does all the heavy lifting. It handles all the network I/O.

The functions in the C library usually take a combination of discrete parameters and pointers to "option" structs. The use of the option structs as parameters allows the library to keep adding new features to the library without breaking the ABI.

Each of these structs starts with a 4-byte char sequence as a sanity check that the struct was properly initialized, followed by an integer version number for the struct. Whenever new variables are added to the struct, the version is incremented so that the library can know which variables to expect in the struct, while maintaining backward compatibility.

For example a call to create a new client looks like this:
```
int MQTTAsync_createWithOptions(MQTTAsync* handle, const char* serverURI, const char* clientId,
    int persistence_type, void* persistence_context, 
    MQTTAsync_createOptions* options);
```

Note the final parameter which is a pointer to an options struct. It currently looks like this:
```
typedef struct
{
	char struct_id[4];
	int struct_version;

	int sendWhileDisconnected;  // From v0
	int maxBufferedMessages;
	int MQTTVersion;         // Added at v1
	int allowDisconnectedSendAtAnyTime;  // Added at v2
	int deleteOldestMessages;
	int restoreMessages;
	int persistQoS0;        // Added at v3
} MQTTAsync_createOptions;
```

The `struct_id` must be set to "MQCO" (no NUL-termination). The `struct_version` must be 0, 1, 2, or 3 to indicate which variables are present in the struct.

If either of these two conditions are not true, the call to `MQTTAsync_createWithOptions()` will fail with error code -8 (bad structure).

The C++ lib simply fills out the struct and passes it to the C lib. This is true of many of the other calls into the library (connect options, SSL options, publish options, subscribe options, etc)

I really can't imaging a lower-level dependency getting in the way, other than something corrupting one library or the other.

**Comment by AndBobsYourUncle** [comment]
Hmm yes, that is what I've gathered so far. And it appears as though the `struct_id` is something that is set in some automatic way. It does not appear that there is any constant with the "MQCO" string in the C++ library, for instance.

If we assume that one or the other library has been corrupted in some way, how might I be able to verify or fix that? For some reason, running through the make steps over again doesn't seem to do much of anything.

**Comment by fpagliughi** [comment]
The C lib has initializer macros, like:
```
#define MQTTAsync_createOptions_initializer  { {'M', 'Q', 'C', 'O'}, 2, 0, 100, MQTTVERSION_DEFAULT, 0, 0, 1, 1}
```
https://github.com/eclipse/paho.mqtt.c/blob/64a5ff3c3b71fe019353aeacaebc66a3cf4f3461/src/MQTTAsync.h#L975

The C++ lib declares a static const in each options class using the latest C initializer for that class:
https://github.com/eclipse/paho.mqtt.cpp/blob/33921c8b68b351828650c36816e7ecf936764379/src/create_options.cpp#L24-L25

And then the constructor(s) use the constant to initialize an internal copy of the C struct:
https://github.com/eclipse/paho.mqtt.cpp/blob/33921c8b68b351828650c36816e7ecf936764379/src/mqtt/create_options.h#L55-L58

**Comment by fpagliughi** [comment]
It's a bit roundabout, but IIRC, the #define can't be used directly by the constructor, but can be used to initialize a const or variable.

**Comment by AndBobsYourUncle** [comment]
Awesome, thank you for this additional context.

I have tried inserting a `printf` into the `createWithOptions` method into the C code right before it returns with the `BAD_STRUCTURE` error, recompiled and installed it...

But then running the C++ sample did not show any additional output. Could it be that my recompiled version is somehow not replacing the shared library somehow?

**Comment by fpagliughi** [comment]
Hmmm. Maybe look at the `ldd` output of your app to see which version of the shared libraries that the loader is finding:

```
$ ldd build/src/samples/async_publish
	linux-vdso.so.1 (0x00007fff8e1f6000)
	libpaho-mqttpp3.so.1 => /home/fmp/mqtt/paho-mqttpp/build/src/libpaho-mqttpp3.so.1 (0x00007f40772a3000)
	libpaho-mqtt3as.so.1 => /home/fmp/mqtt/paho.mqtt.c/build/_install/usr/local/lib/libpaho-mqtt3as.so.1 (0x00007f407726f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f407706b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4077050000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f407702d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4076e3b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f40773df000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f4076da6000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f4076ad0000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4076981000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f407697b000)
```
The C lib, `libpaho-mqtt3as.so.1` and C++ lib `libpaho-mqttpp3.so.1` should be there if you're linking to the shared libs. But are they pointing to the correct versions?  For example, my dev environment, as shown above, uses local copies in my home directory. But you're installing the libraries so find them in /usr/local/lib?

**Comment by AndBobsYourUncle** [comment]
```
~/paho.mqtt.cpp/build/src/samples$ ldd ./async_publish
	linux-vdso.so.1 (0x00007ffea91df000)
	libpaho-mqttpp3.so.1 => /home/nicholas/paho.mqtt.cpp/build/src/libpaho-mqttpp3.so.1 (0x00007fba27640000)
	libpaho-mqtt3as.so.1 => /usr/local/lib/libpaho-mqtt3as.so.1 (0x00007fba2740f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fba27086000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fba26e6e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fba26c4f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fba2685e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fba27b63000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007fba265d1000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007fba26106000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fba25d68000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fba25b64000)
```

Looks like the `libpaho-mqtt3as.so.1` library is in `/usr/local/lib`. Any way that I can remove it? Is it actually possible just to delete them? Also, if I rebuild the C library, is it just a build option to make it install into the folder within the repo like yours?

**Comment by AndBobsYourUncle** [comment]
I also do not get a `build/` folder at all when building the C library. Maybe that's how it is supposed to work, but not sure.

**Comment by fpagliughi** [comment]
It put the C lib into `/usr/local` because your CMake command (as you showed above) told it to install:
```
$ sudo cmake --build build/ --target install
```
If you don't want to install, remove the `--target install` part there. 

I can't remember if the C lib supports `sudo make uninstall`, but if not, you can just manually delete all the files, if you want.

And you should have a `build/` folder in the C lib, because you CMake command, above, says to create one:
```
$ cmake -Bbuild -H. -DPAHO_ENABLE_TESTING=OFF -DPAHO_BUILD_STATIC=ON \
    -DPAHO_WITH_SSL=ON -DPAHO_HIGH_PERFORMANCE=ON
```

The `-B` option says to use `build/` as the build directory (create it if if doesn't exist).
And it must have been there, because the next command says to compile the contents of the `build/` directory:
```
$ sudo cmake --build build/ --target install
```
 
But I feel your pain with this... I still can't get a decent handle on CMake.

**Comment by AndBobsYourUncle** [comment]
Oh wow, I ran `sudo make uninstall` in the C project, and then followed the steps to build both the C project and C++ project over again...

Now it magically works and I don't get the `Bad Structure` error running the sample.

Thank you so much for your help and explanations. I'm guessing that _something_ had somehow corrupted the C library, and then rebuilding it without the `make uninstall` wasn't overwriting the library that was already there? Who knows, but it works now. 😄

**Comment by AndBobsYourUncle** [comment]
Also, for reference, after doing the `make uninstall` and rebuilding a few times, a ran into the issue _again_. This time, when I ran `ldd` on one of the C++ samples, it gave me this:

```
~/paho.mqtt.cpp$ ldd ./build/src/samples/async_publish
	linux-vdso.so.1 (0x00007fff2c9fd000)
	libpaho-mqttpp3.so.1 => /home/nicholas/paho.mqtt.cpp/build/src/libpaho-mqttpp3.so.1 (0x00007f305bd27000)
	libpaho-mqtt3as.so.1 => /opt/intel/openvino_2021/data_processing/gstreamer/lib/libpaho-mqtt3as.so.1 (0x00007f305ba67000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f305b6de000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f305b4c6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f305b2a7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f305aeb6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f305c24a000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f305ac29000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f305a75e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f305a3c0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f305a1bc000)
```

So, to anyone else running into this issue in the future... if you are building OpenVINO stuff, then it might be building some hidden version of the C pahomqtt library in some tucked-away folder that is getting picked up by `ldd`.

**Comment by fpagliughi** [comment]
Glad you found it.
