### ISSUE TITLE
What version of the MQTT C lib is required?

### ISSUE THREAD

**Issue by Stokestack** [eclipse/paho.mqtt.cpp#328]
I'm having a hard time getting CMake to find my Paho C lib. Looking at the top-level CMakeLists.txt file for the CPP lib here:

`set(PAHO_MQTT_C paho-mqtt3a)`

As you probably know:

> The Paho C client comprises four variant libraries, shared or static:
> 
> paho-mqtt3a - asynchronous (MQTTAsync)
> paho-mqtt3as - asynchronous with SSL (MQTTAsync)
> paho-mqtt3c - "classic" / synchronous (MQTTClient)
> paho-mqtt3cs - "classic" / synchronous with SSL (MQTTClient)

I can see that the CPP wrapper assumes you're building the async lib. But I'm building the synchronous one, paho-mqtt3c. Is this wrapper compatible with that lib?

That's a separate issue from CMake not finding the lib. I've verified that both the "a" and "c" versions exist in a sibling directory under a parent project that incorporates both the C library and this wrapper (in Qt 5).

Thanks!

**Comment by fpagliughi** [comment]
The C++ library wraps the Async C library exclusively. Either `paho-mqtt3as` if you want SSL, or `paho-mqtt3a` if you don't.

It is not aware of the synchronous C lib at all. The C++ lib does offer a synchronous `client` class, but this just sits atop the async C/C++ code and manages the blocking and waiting.

**Comment by Stokestack** [comment]
Thanks, Frank! I should've closed this because I did suss that out pretty quickly. I got the C lib and this one building in a simple test project in Qt with much CMake finagling and cursing. The samples won't build because they can't find header files, but I haven't really looked into it. They weren't supposed to be building anyway.
