### ISSUE TITLE
arm compile get error

### ISSUE THREAD

**Issue by POOOOOOOON** [eclipse/paho.mqtt.cpp#332]
cmake：
-- The CXX compiler identification is GNU 4.8.3
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/arm/arm-2014.05/bin/arm-none-linux-gnueabi-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/local/arm/openssl/lib/libcrypto.so (found version "1.1.0l")  
-- Found PahoMqttC: /usr/local/arm/paho.mqtt.c/lib/libpaho-mqtt3c.so.1.3.7  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Configuring done
-- Generating done

make：
In file included from /home/poon/tools/paho.mqtt.cpp-1.0.1/src/client.cpp:20:0:
/home/poon/tools/paho.mqtt.cpp-1.0.1/src/mqtt/client.h: In member function 'virtual void mqtt::client::connected(const string&)':
/home/poon/tools/paho.mqtt.cpp-1.0.1/src/mqtt/client.h:71:76: error: invalid use of incomplete type 'class std::future<void>'
   std::async(std::launch::async, &callback::connected, userCallback_, cause);
                                                                            ^
In file included from /home/poon/tools/paho.mqtt.cpp-1.0.1/src/mqtt/client.h:28:0,
                 from /home/poon/tools/paho.mqtt.cpp-1.0.1/src/client.cpp:20:
/usr/local/arm/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/future:113:11: error: declaration of 'class std::future<void>'
     class future;
           ^

**Comment by YipuL** [comment]
同样的问题，你解决了吗？

**Comment by fpagliughi** [comment]
That release is a few years old. Can you try the latest v1.2.0?

**Comment by YipuL** [comment]
> That release is a few years old. Can you try the latest v1.2.0?

I'm using the latest release but still got this error.

**Comment by POOOOOOOON** [comment]
> same error. Did you fix it ?

not fix

**Comment by juked** [comment]
I am having the same issue. I think it has to be something related to a 32-bit build.

`In file included from /home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/client.cpp:20:0:
/home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/mqtt/client.h: In member function 'virtual void mqtt::client::connected(const string&)':
/home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/mqtt/client.h:71:76: error: invalid use of incomplete type 'class std::future<void>'
   std::async(std::launch::async, &callback::connected, userCallback_, cause);
                                                                            ^
In file included from /home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/mqtt/client.h:28:0,
                 from /home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/client.cpp:20:
/home/ubuntu/MSD6586/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/future:113:11: error: declaration of 'class std::future<void>'
     class future;
           ^
In file included from /home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/client.cpp:20:0:
/home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/mqtt/client.h: In member function 'virtual void mqtt::client::connection_lost(const string&)':
/home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/mqtt/client.h:75:56: error: invalid use of incomplete type 'class std::future<void>'
        &callback::connection_lost, userCallback_, cause);
                                                        ^
In file included from /home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/mqtt/client.h:28:0,
                 from /home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/client.cpp:20:
/home/ubuntu/MSD6586/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/future:113:11: error: declaration of 'class std::future<void>'
     class future;
           ^
In file included from /home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/client.cpp:20:0:
/home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/mqtt/client.h: In member function 'virtual void mqtt::client::delivery_complete(mqtt::delivery_token_ptr)':
/home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/mqtt/client.h:81:82: error: invalid use of incomplete type 'class std::future<void>'
   std::async(std::launch::async, &callback::delivery_complete, userCallback_, tok);
                                                                                  ^
In file included from /home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/mqtt/client.h:28:0,
                 from /home/ubuntu/dt_linux/MSD6586/3rdParty/paho-mqtt-cpp/src/paho_cpp_project/src/client.cpp:20:
/home/ubuntu/MSD6586/arm-2014.05/arm-none-linux-gnueabi/include/c++/4.8.3/future:113:11: error: declaration of 'class std::future<void>'
     class future;`

**Comment by finalfinalfinal** [comment]
> > same error. Did you fix it ?
> 
> not fix

any input on this issue? Seems to be related to an arm compilation using this toolchain:

https://sourcery.mentor.com/GNUToolchain/package12813/public/arm-none-linux-gnueabi/arm-2014.05-29-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2

**Comment by finalfinalfinal** [comment]
> That release is a few years old. Can you try the latest v1.2.0?

This issue seems to be related to an arm compilation using the toolchain below. Any assistance would be appreciated

https://sourcery.mentor.com/GNUToolchain/package12813/public/arm-none-linux-gnueabi/arm-2014.05-29-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2

**Comment by finalfinalfinal** [comment]
The toolchain has ATOMIC_INT_LOCK_FREE = 1 which disables the use of async which is why the errors occur above. ARMV7 4.8.3 toolchain for some reason has this set to 1 although it supports async. Is there a work around for this @fpagliughi that you could think of? 

#if (__cplusplus >= 201103L) && (ATOMIC_INT_LOCK_FREE > 1)

**Comment by fpagliughi** [comment]
Actually now I do kind of remember this!

I started the project nearly a decade ago when GCC 4.8 first came out and used it as the main compiler for the first release. The native compilers worked fine on both x86 and ARM, but several cross-compilers didn't work with regard to basic threading. I still have this little test app in my personal test suite from then:
```
#include <iostream>
#include <thread>

using namespace std;

void thr_func()
{
  cout << "Hello from the thread!" << endl;
}

int main()
{
  thread thr(thr_func);
  thr.join();
  return 0;
}
```
This failed on several cross-compilers targeting ARM boards. I can't remember if the codesourcery compiler was bad.

Anyway, I think my solution at the time was to regenerate my own cross-compiler using [crosstools-NG](https://crosstool-ng.github.io/), or something like that. I haven't done that in years, and I don't think I'd recommend it these days since the ones ARM distributes now seem to work well.

Unfortunately, the only real requirement for this library is a fully conformant C++11 compiler; and it seems like the one you have doesn't work. So you will likely need to do one of the following:
- Build your own compiler from sources.
- Try to find a different pre-built one that works
- Build natively on your target board or a compatible one. (I keep an NVidia Jetson-TK1 as a relatively fast ARMv7 build server).
- Upgrade to a newer compiler. I don't remember seeing this problem after the 4.x line.

**Comment by fpagliughi** [comment]
If you can't update the compiler, something else to consider...

The `std::async` call is only used by the synchronous `client` class as a helper. If you're not using it (if you're using `async_client` directly), try to remove `client.h` and `client.cpp` from the build. Remove them from the CMake files and see if you can build without them. 

If you _can_ get it to build, then see if it **runs** with the compiler/library bugs. If id does work, mybe we can consider a build flag to leave `client` out of the build? Maybe. But I don't know how much work I would want to do to work around an 8 year old buggy compiler.

**Comment by ravoshsamari** [comment]
@fpagliughi thanks foe the tip. removing those two files from the build and from the Makefile seems to have done the trick.
