### ISSUE TITLE
publish seems blocked when reconnect success

### ISSUE THREAD

**Issue by mailliw2010** [eclipse/paho.mqtt.cpp#334]
hey, bro:i meet problems here:
codes:

**---->>> mqtt client initialize:**

```
mqtt_client::initialize(){

    this->set_callback(*cb.get());
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));  // wait for 1s to connect
    conn_opt =  mqtt::connect_options(_user, _pass);
    conn_opt.set_keep_alive_interval(keepalive_time);  // heart beat
    conn_opt.set_clean_session(true);    // when reconnect , need to subscribe again
    conn_opt.set_connect_timeout(20);    // default is 20s


    try {
            LOG(INFO) << this->name << " Connecting to the MQTT server...";
        
              connect(conn_opt);    // but this config can not callback the err connect state
        }

        catch (const mqtt::persistence_exception& exc) {   // this exception first!
            LOG(ERROR) << "ERROR: Persistence error:";
            LOG(ERROR) << exc.get_reason_code();

            return -1;
        }
        catch (const mqtt::exception& exc) {
            LOG(ERROR) << "ERROR: Unable to connect to MQTT server:";
            LOG(ERROR) << exc.what();
            LOG(INFO) << "Try backup conn:";

            return -1;
        }
}
```		

**---->>> mqtt client loop thread:**

```
thread(){
for (;;) {
        std::this_thread::sleep_for(std::chrono::seconds(5));
        mqtt_client->publishMesg(Topic, Info);
}
```

**---->>> mqtt client publish:**

```
publishMesg(...){

    if(mqtt_client->is_connected()){
        if(mqtt_client->publish(pubmsg)->wait_for(TIMEOUT) == false){   
            LOG(INFO) << "publish timeout!";
            return ;
        }
        LOG(INFO) << "Publishing -Topic:" << TotalTopic;
    }
}
```

**---->>> mqtt client callback:**

```
void callback::reconnect()
{
   std::this_thread::sleep_for(std::chrono::milliseconds(2500));
   LOG(INFO) << "Reconnecting to server...";
       try {
           cli_.connect(connOpts_, nullptr, *this);
       }
       catch (const mqtt::exception& exc) {
           std::cerr << "Error: " << exc.what() << std::endl;
           exit(1);
       }
}
```
**---->>> situation:**

when i ifconfig eth0 down on mqtt client machine for a while, the client will print 
"publish timeout " 
"publish timeout " 
"publish timeout " 
...
for a keepalive*1.5 time, then client will try to connect 
"Reconnecting to server..."
"Reconnecting to server..."
"Reconnecting to server..."
....
if retry for setting-try-times failure, exit process; this situation is normal.
if retry times are less then setting-try-times, i recover the network by "ifconfig eth0 up".
client will connect and subscribe my topic.
however, the loop thread is dead! i can not see any pubmsg.
yet the client is alive , can receive the subscribe topic. it is just block in the loop thread

```
thread(){
    for (;;) {
        std::this_thread::sleep_for(std::chrono::seconds(5));
        mqtt_client->publishMesg(Topic, Info);    // seems to block in publish->wait_for(), i guess
}
```

thanks so much!

**Comment by fpagliughi** [comment]
It seems like you're making a blocking call to the library from a callback (i.e. calling the synchronous `connect()` from the reconnect callback).

You can't make blocking calls from within callbacks. You can reconnect in a callback using the asynchronous client. But you can't call any `wait()` functions on the async client in the callback.
