### ISSUE TITLE
pub_speed_test sample fails with DFLT_PAYLOAD_SIZE bigger than 1 KB

### ISSUE THREAD

**Issue by oakBarrelMimic** [eclipse/paho.mqtt.cpp#339]
Hello, 
I copied a sample https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/pub_speed_test.cpp and only changed the message size from 1KB to 32 KB (updated the DFLT_PAYLOAD_SIZE variable from 1024 to 32 * 1024).
For messages of size 1KB everything works fine, 
but every time when I start it for 32KB, the client disconnects after a few seconds before it could finish sending all the messages to the broker.

File [client.log](https://github.com/eclipse/paho.mqtt.cpp/files/6405065/client.log) contains logs from the client

I used conan packet (version 1.2.0) to install this library: https://conan.io/center/paho-mqtt-cpp
I am running it on Windows 10
Compiler version: MSVC 19.28.29914.0

**Comment by fpagliughi** [comment]
This seems to be working in the latest versions (1.3.2 & 1.4.0), so it was likely fixed along the way.
