### ISSUE TITLE
Warnings when compiling for C++20

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.cpp#340]
When compiling for C++20, there are still a few warnings. With clang++ v11:

```
In file included from src/client.cpp:20:
src/mqtt/client.h:71:3: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
                std::async(std::launch::async, &callback::connected, userCallback_, cause);
                ^~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/mqtt/client.h:74:3: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
                std::async(std::launch::async,
                ^~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~
src/mqtt/client.h:81:3: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
                std::async(std::launch::async, &callback::delivery_complete, userCallback_, tok);
                ^~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings generated.
```

**Comment by Pascal-Fremaux** [comment]
In fact, the C++20 warning is welcome, as it is a critical pitfall not to get the return of std::asynch and manage correctly the std::future (I falled into myself when starting to use it).
Here it has the side effect that the method that call the task (include your "std::async(std::launch::async" call) is blocked until the task completion, as it will generate a hidden local temporary std::future object, and that object destructor will block the method return until the async task is completed (see definition of std::future destructor and std::async).
=> The std::future destructor (of the implicit temporary local instance) do a wait()
Which is generally not what people expect with async tasks (or they do an explicit wait()).
So you cannot do real parallelism as you in fact proceed to an invisible future.wait() in your caller method.

One correct handling is to have your future stored in an object with a life scope longer than the task execution time, so its blocking will not impact the calling method (but of course will prevent the destruction of that object containing the std::future until the task completion).

Example:
class A{
std::future<T> myFuture;
public:
void myMethodThatLaunchATaskAndDoNotWantToBeBlockedUntilTaskCompletion() {
       myFuture = std::async(std::launch::async, SomeTask);
      // Here the method return will not be blocked as the future lives outside of the method.
}
}

Be careful also of the other side effects of std::future, like reusing the same future on several tasks (causing the tasks to be executed sequentially).

**Comment by dberlin** [comment]
This is the sync client and not the async client, so the behavior that is happening is correct - it should block.
Because these are all marked nodiscard, the proper fix is to add .wait() on the end of them explicitly.
