### ISSUE TITLE
Variable overlap

### ISSUE THREAD

**Issue by gugolple** [eclipse/paho.mqtt.cpp#344]
Hello, first to put everybody in context, I am trying to build an autotools project with this library, and while doing a simple check to produce an error if the library is missing I found out that in mqtt/async_client.h there is a definition of VERSION, precisely in line 64 ("const uint32_t VERSION = 0x01020000;"). This VERSION then collides with the '#define VERISION "current_version"' that is defined automatically by the autotools in the check.
Below I provide my current check that fails, as you may see, here it is not defined version because it is automatically inserted when it creates the conftest.cpp because it is trailing from the config.h.in that has version. Trying a few things did not provide any good results, like removing VERSION from the config.h.in. I found out that it overlaps when compiling the example async_client with "#define VERSION" before the "#include <mqtt/async_client.h>", it does not collide if it is defined after the mqtt include.
Could it be possible to rename that variable? or is there another solution for checking the existence of mqtt/async_client.h?
I am really grateful for your time,
Gugolple.
<pre>
AC_LINK_IFELSE(    
        [AC_LANG_PROGRAM(    
                [    
                        [#include &#60;string&#62;]
                        [#include &#60;thread&#62;]
                        [#include &#60;mqtt/async_client.h&#62;]
                ],
                [
                        [mqtt::async_client cli(std::string("localhost:1234"),std::string("prueba"));]
                ]
        )],
        [HAVE_MQTT=1],
        [AC_MSG_FAILURE([PAHO MQTT C++ is not installed.])]
)
</pre>
Update, if I #undef VERSION before the #include <mqtt/async_client.h> it works, but I don't feel like it is a valid solution, that's why I kept this issue opened.

**Comment by fpagliughi** [comment]
This was a known issue. See #183

Now you can define a macro `PAHO_MQTTPP_VERSIONS` for the build and it will use Paho-specific constant names, like `PAHO_MQTTPP_VERSION` instead of the generic `VERSION`.

https://github.com/eclipse/paho.mqtt.cpp/blob/2ff3d155dcd10564f1816675789284b4efd79eb7/src/mqtt/async_client.h#L55-L69

**Comment by gugolple** [comment]
Oh, so sorry for not looking into old issues. May I ask of the reason for having this distinction instead of having the other way by default and not having this problem at all?
