### ISSUE TITLE
paho.mqtt.cpp - version with SSL / TLS support?

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse/paho.mqtt.cpp#351]
Hi

Where can i get it? Currently we use the non-secure version on: https://github.com/eclipse/paho.mqtt.cpp.git

But now we need the version that supports SSL / TLS...

Thank you for your feedbacks...

With kind regards, Jan

**Comment by jayjupdhig** [comment]
What do i need to to to reach my goal? AND: What is correctly for ´DPAHO_WITH_SSL´ ?

´-DPAHO_WITH_SSL=ON´

OR

´-DPAHO_WITH_SSL=TRUE´

???


Thank you for your feedbacks...

**Comment by jayjupdhig** [comment]
![pahossl](https://user-images.githubusercontent.com/42765391/126327741-39c1b643-43db-4e3b-a100-a94a01d521f4.jpg)


"Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)"

That's no really true - they were built before... but since i changed to SSL / TLS, i get that (and other) messages - as shown in the image.

**Comment by jayjupdhig** [comment]
Now

```
rm -rf /tmp/compile__PAHO_MQTT_CPP.sh.tmp;
root@build-raspi:~/deployment# rm -rf /tmp/*.sh.tmp && ./compile__paho_mqtt_cpp.sh
+ '[' -f /tmp/compile__PAHO_MQTT_CPP.sh.tmp ']'
+ touch /tmp/compile__PAHO_MQTT_CPP.sh.tmp
+ cd /root/deployment/Temp/PAHO_MQTT_CPP
+ LIB=/usr/lib/arm-linux-gnueabihf
+ INC=/usr/include/arm-linux-gnueabihf/openssl
+ PAHO_MQTT_C=/root/deployment/Temp/PAHO_MQTT_C/MQTTClient.c
+ eatmydata -- cmake -Bbuild -H. -DPAHO_WITH_SSL=ON -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_MQTT_C_LIBRARIES=/root/deployment/Temp/PAHO_MQTT_C/MQTTClient.c -DOPENSSL_LIB_SEARCH_PATH=/usr/lib/arm-linux-gnueabihf -DOPENSSL_INC_SEARCH_PATH=/usr/include/arm-linux-gnueabihf/openssl
-- Configuring done
-- Generating done
-- Build files have been written to: /root/deployment/Temp/PAHO_MQTT_CPP/build
+ cmake --build build/ --target install
[ 93%] Built target paho-cpp-objs
make[2]: *** Keine Regel vorhanden, um das Ziel „/root/deployment/Temp/PAHO_MQTT_C/MQTTClient.c“,
  benötigt von „src/libpaho-mqttpp3.so.1.2.0“, zu erstellen.  Schluss.
make[1]: *** [CMakeFiles/Makefile2:164: src/CMakeFiles/paho-mqttpp3.dir/all] Fehler 2
make: *** [Makefile:152: all] Fehler 2
```

**Comment by jayjupdhig** [comment]
Why that?!

**Comment by jayjupdhig** [comment]
OH - mea culpa. Path was wrong, i forgot the ´src´ dir: PAHO_MQTT_C=/root/deployment/Temp/PAHO_MQTT_C/src/MQTTClient.c

**Comment by jayjupdhig** [comment]
but now i get that:

´´´
+ '[' -f /tmp/compile__PAHO_MQTT_CPP.sh.tmp ']'
+ touch /tmp/compile__PAHO_MQTT_CPP.sh.tmp
+ cd /root/deployment/Temp/PAHO_MQTT_CPP
+ LIB=/usr/lib/arm-linux-gnueabihf
+ INC=/usr/include/arm-linux-gnueabihf/openssl
+ PAHO_MQTT_C=/root/deployment/Temp/PAHO_MQTT_C/src/MQTTClient.c
+ eatmydata -- cmake -Bbuild -H. -DPAHO_WITH_SSL=ON -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_MQTT_C_LIBRARIES=/root/deployment/Temp/PAHO_MQTT_C/src/MQTTClient.c -DOPENSSL_LIB_SEARCH_PATH=/usr/lib/arm-linux-gnueabihf -DOPENSSL_INC_SEARCH_PATH=/usr/include/arm-linux-gnueabihf/openssl
-- Configuring done
-- Generating done
-- Build files have been written to: /root/deployment/Temp/PAHO_MQTT_CPP/build
+ cmake --build build/ --target install
[ 93%] Built target paho-cpp-objs
[100%] Linking CXX shared library libpaho-mqttpp3.so
/root/deployment/Temp/PAHO_MQTT_C/src/MQTTClient.c:81:10: fatal error: VersionInfo.h: Datei oder Verzeichnis nicht gefunden
 #include "VersionInfo.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/paho-mqttpp3.dir/build.make:102: src/libpaho-mqttpp3.so.1.2.0] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:164: src/CMakeFiles/paho-mqttpp3.dir/all] Fehler 2
make: *** [Makefile:152: all] Fehler 2
root@build-raspi:~/deployment#
´´´

**Comment by jayjupdhig** [comment]
The file ´VersionInfo.h´ does not exist:

´´´
root@build-raspi:~/deployment# ls /root/deployment/Temp/PAHO_MQTT_C/src/VersionInfo.h
ls: Zugriff auf '/root/deployment/Temp/PAHO_MQTT_C/src/VersionInfo.h' nicht möglich: Datei oder Verzeichnis nicht gefunden
´´´

**Comment by jayjupdhig** [comment]
Why the exesntion is .h.in an not only .h?

```
root@build-raspi:~/deployment# ls /root/deployment/Temp/PAHO_MQTT_C/src/ | grep -i versioninfo
VersionInfo.h.in
```

**Comment by jayjupdhig** [comment]
???

**Comment by jayjupdhig** [comment]
-> https://github.com/eclipse/paho.mqtt.cpp/issues/352

**Comment by fpagliughi** [comment]
As described in the README, you first need to build and install the Paho C library, and _then_ build the C++ library:
https://github.com/eclipse/paho.mqtt.cpp/#building-the-paho-c-library

**Comment by lmapii** [comment]
I stumbled upon the same problem, it may help to include `-DPAHO_WITH_SSL=ON` also in the readme section "Building the Paho C++ Library" since it is directly located under the instructions for building the C library (which uses the `SSL` feature). Since I did not read the full document I initially did not know about this flag in the C++ library.
