### ISSUE TITLE
Why the version info header file is called "VersionInfo.h.in" and NOT "VersionInfo.h" ??

### ISSUE THREAD

**Issue by jayjupdhig** [eclipse/paho.mqtt.cpp#352]
Why the version info header file is called "VersionInfo.h.in" and NOT "VersionInfo.h" ??

**Comment by jayjupdhig** [comment]
???

**Comment by jayjupdhig** [comment]
-> https://github.com/eclipse/paho.mqtt.cpp/issues/351

**Comment by fpagliughi** [comment]
Typically a file named something like "VersionInfo.h.in" implies that it's an input template for the build system to update.  So if we look at it:

```
$ cat VersionInfo.h.in 
#ifndef VERSIONINFO_H
#define VERSIONINFO_H

#define BUILD_TIMESTAMP "@BUILD_TIMESTAMP@"
#define CLIENT_VERSION  "@CLIENT_VERSION@"

#endif /* VERSIONINFO_H */
```

The values in `@xxx@` will be updated when the build is run, and might produce something like this into a file named "VersionInfo.h":

```
$ cat VersionInfo.h 
#ifndef VERSIONINFO_H
#define VERSIONINFO_H

#define BUILD_TIMESTAMP "2021-07-26T18:47:05Z"
#define CLIENT_VERSION  "1.3.9"

#endif /* VERSIONINFO_H */
```

So, the include file "versionInfo.h" is created from the template during the build.

Note, too, that this is from the Paho C library, and not in this C++ library, so I have no control over it. If you want more information, perhaps raise an issue in that project:
https://github.com/eclipse/paho.mqtt.c/issues
