### ISSUE TITLE
Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)

### ISSUE THREAD

**Issue by SUP3RH0MI3** [eclipse/paho.mqtt.cpp#359]
I followed the steps in Readme.md and tried to do it on Windows with the MSBuild Command Prompt. Repositorys are in C:\MQTT\paho.mqtt.c-master\ and C:\MQTT\paho.mqtt.cpp-master\. I followed the steps in Readme.md and when I tried to cmake the c++ version with the following command:

> cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\mqtt\paho-cpp -DPAHO_BUILD_SAMPLES=ON -DPAHO_WITH_SSL=OFF -DCMAKE_PREFIX_PATH=C:\mqtt\paho-c

I get this Error Message:

> CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)

> Call Stack (most recent call first):
> C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPahoMqttC.cmake:33 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:26 (find_package)

I have no clue how to fix that and I hope somebody can help me.

**Comment by yuvarajvelumani** [comment]
C:\MQTT\paho.mqtt.c-master != C:\mqtt\paho-c

**Comment by SUP3RH0MI3** [comment]
Thank you for you answer, but I found out that I dont need to do it anymore. I close this issue.
