### ISSUE TITLE
It is useless to set SESSION_EXPIRY_INTERVAL by properties method of connect_options_builder

### ISSUE THREAD

**Issue by jianweihao** [eclipse/paho.mqtt.cpp#362]
paho.mqtt.cpp version : 1.2.0

I think that the connectProperties pointer of opts_ is set in the set_properties function of connect_options, and the builder will have a copy structure in the finalize function, causing the variable pointed to by the connectProperties pointer to become invalid.

![issue](https://user-images.githubusercontent.com/23733835/131458869-2f8935fa-af02-4722-9d69-1bb443340374.png)
![issue2](https://user-images.githubusercontent.com/23733835/131458878-9240fb5b-5e4e-4ad0-9345-c895cc0a5e2e.png)

**Comment by avivruham** [comment]
You are so right!!!!
I could not use persistent session with v5 when I used the builder.
WA is to use `connection_options.set_properties(connectProperties);`

Glad you found it!

**Comment by fpagliughi** [comment]
Yes! Apologies for the slow response on this, I was out last summer and still trying to catch up. 

I just confirmed this errant behavior and am working on a fix.

**Comment by fpagliughi** [comment]
Several commits and a PR were added that should fix this. I will very this specific case before the upcoming release.

**Comment by fpagliughi** [comment]
Added several new unit tests to make sure it's working, and then verified it with WireShark that the value from the builder is making it onto the wire.  Added a new `async_consume_v5` sample app.
