### ISSUE TITLE
Clean disconnect

### ISSUE THREAD

**Issue by nandlab** [eclipse/paho.mqtt.cpp#369]
I am working on the project [mqtt_node_paho_demo](https://gitlab.com/NANDLAB/mqtt_node_paho_demo).
I am writing a mqtt client class, which can asynchronously listen for mqtt messages and system signals using [boost asio](https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio.html). All asynchronous paho mqtt callbacks post an event to the asio io context, and are later handled in the io context (like an event loop). This ensures that none of my handlers are called at the same time.
The program should exit if either a mqtt kill message or system signal like a keyboard interrupt is received. Now, I am not really sure how to cleanly disconnect from the mqtt broker and disable all the callbacks.
These are the relevant class methods:
```cpp
void mqtt_node_paho::on_failure(const mqtt::token &token) {
    boost::asio::post(ioc, boost::bind(&mqtt_node_paho::on_failure_ioc, this));
}

void mqtt_node_paho::on_failure_ioc() {
    if (!exiting) {
        std::cout << "mqtt_node_paho: Connection attempt failed!" << std::endl;
    }
}

void mqtt_node_paho::on_success(const mqtt::token &token) {
    boost::asio::post(ioc, boost::bind(&mqtt_node_paho::on_success_ioc, this));
}

void mqtt_node_paho::on_success_ioc() {
    if (!exiting) {
        std::cout << "mqtt_node_paho: Connection success" << std::endl;
    }
}

void mqtt_node_paho::message_arrived(mqtt::const_message_ptr msg) {
    boost::asio::post(ioc, boost::bind(&mqtt_node_paho::interpret_message, this, msg));
}

bool mqtt_node_paho::interpret_message(mqtt::const_message_ptr msg) {
    if (!exiting) {
        std::cout << "mqtt_node_paho: Message arrived: " << msg->get_topic() << " " << msg->to_string() << std::endl;
        if (msg->get_topic() == full_topic_signal && msg->to_string() == signal_kill) {
            std::cout << "mqtt_node_paho: This is a kill message, exiting ..." << std::endl;
            clean_exit();
            return true;
        }
    }
    return false;
}

void mqtt_node_paho::clean_exit() {
    exiting = true;
    system_signals.cancel();
    try {
        std::cout << "mqtt_node_paho: Publishing offline status ..." << std::endl;
        mqtt_client.publish(full_topic_status, status_disconn_clean, 0, true)->wait();
        std::cout << "mqtt_node_paho: Offline status published" << std::endl;
        std::cout << "mqtt_node_paho: Disconnecting from broker ..." << std::endl;
        mqtt_client.disconnect()->wait();
        std::cout << "mqtt_node_paho: Disconnected" << std::endl;
    }
    catch (const mqtt::exception &e) {
        if (e.get_return_code() == MQTTASYNC_DISCONNECTED) {
            std::cout << "mqtt_node_paho: Already disconnected" << std::endl;
        }
        else {
            throw e;
        }
    }
    mqtt_client.disable_callbacks();
}

void mqtt_node_paho::system_signal_handler(const boost::system::error_code &ec, int signal) {
    if (!ec && !exiting) {
        std::cout << "mqtt_node_paho: Signal " << signal << " received." << std::endl;
        clean_exit();
    }
}

void mqtt_node_paho::start() {
    exiting = false;
    mqtt_client.set_callback(*this);
    system_signals.async_wait(boost::bind(&mqtt_node_paho::system_signal_handler, this, _1, _2));
    mqtt::connect_options opts;
    opts.set_will(mqtt::message(full_topic_status, status_disconn_abnorm, 0, true));
    connect_token = mqtt_client.connect(std::move(opts), nullptr, *this);
}

```
Sometimes, if I send a kill signal very fast, when `connect()` did not complete yet, `disconnect()` throws a `mqtt::exception` with the return code `MQTTASYNC_FAILURE`. Should I also catch it and interpret it as already disconnected?
Does `mqtt_client.disable_callbacks()` disable both the main callbacks and the connect callbacks `on_failure()` and `on_success()`?
Is there something else I have to consider to prevent race conditions?

**Comment by Pascal-Fremaux** [comment]
Simple, you cannot call disconnect() when already disconnected, or worst if you client has been cleaned.
Let assume you use the asynclient (seems so).
Paho CPP calls the Paho C MQTTAsync_disconnect that calls its internal MQTTAsync_disconnect1
https://github.com/eclipse/paho.mqtt.c/blob/3b7ae6348bc917d42c04efa962e4868c09bbde9f/src/MQTTAsyncUtils.c

You will find the error uploaded in CPP by an exception. In your case (MQTTASYNC_FAILURE) the Paho C client handle seems to have been already dismantled by the Paho CPP async client (which might also be dead, I have no idea how you manage it).

**Comment by NANDLAB** [comment]
> You will find the error uploaded in CPP by an exception. In your case (MQTTASYNC_FAILURE) the Paho C client handle seems to have been already dismantled by the Paho CPP async client (which might also be dead, I have no idea how you manage it).

I created the async client normally and called `connect()`. So the Paho C client handle should be initialized. What else can cause `MQTTASYNC_FAILURE` when I call `disconnect()`?

**Comment by fpagliughi** [comment]
BTW, to throw on a late response...

The C++ library throws an exception if `disconnect()` is called on a client that is not currently connected. That derives from the underlying C library that returns a FAILURE to indicate that the requested action (performing a disconnect) did not happen. I would categorize it as a "soft" error, more of a status than anything that needs to be handled.

As such, I acknowledge that throwing the exception is a bit harsh for this scenario, and people have complained about it, but it is consistent with other error reporting. I might reconsider this in a future version.
