### ISSUE TITLE
Unsuccessful compiling a program after installing load Paho C 

### ISSUE THREAD

**Issue by OldSurferDude** [eclipse/paho.mqtt.cpp#382]
Yes, I don't know what I'm doing but would like to know what I'm doing.  Whatever it is I have done, it was on a Raspberry Pi 3B+

I followed the instructions on the [code page](https://github.com/eclipse/paho.mqtt.cpp) to install Eclipse Paho MQTT C++ Client Library.  I put the steps below even though they are on the code page.

There were no instructions after this.  I tried several things to no avail.  **cmake CMakeLists.txt** made directories for all the examples.  From this I gleaned the compile command **/usr/bin/c++ data_publish.cpp -o data_publish**, but that resulted in a number of errors

What do I need to do to compile the sample program?

OSD

### Compiling Errors:
/usr/bin/ld: /tmp/ccPbNUIV.o: in function `main':
data_publish.cpp:(.text+0x164): undefined reference to `mqtt::async_client::async_client(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, mqtt::iclient_persistence*)'
/usr/bin/ld: data_publish.cpp:(.text+0x324): undefined reference to `mqtt::connect_options::connect_options(mqtt::connect_options const&)'
/usr/bin/ld: data_publish.cpp:(.text+0x33c): undefined reference to `mqtt::async_client::connect(mqtt::connect_options)'
/usr/bin/ld: data_publish.cpp:(.text+0x580): undefined reference to `mqtt::topic::publish(mqtt::buffer_ref<char>)'
/usr/bin/ld: data_publish.cpp:(.text+0x80c): undefined reference to `mqtt::async_client::~async_client()'
/usr/bin/ld: data_publish.cpp:(.text+0x890): undefined reference to `mqtt::async_client::~async_client()'
/usr/bin/ld: /tmp/ccPbNUIV.o: in function `mqtt::exception::error_str[abi:cxx11](int)':
data_publish.cpp:(.text._ZN4mqtt9exception9error_strB5cxx11Ei[_ZN4mqtt9exception9error_strB5cxx11Ei]+0x18): undefined reference to `MQTTAsync_strerror'
/usr/bin/ld: /tmp/ccPbNUIV.o: in function `mqtt::exception::reason_code_str[abi:cxx11](int)':
data_publish.cpp:(.text._ZN4mqtt9exception15reason_code_strB5cxx11Ei[_ZN4mqtt9exception15reason_code_strB5cxx11Ei]+0x28): undefined reference to `MQTTReasonCode_toString'
/usr/bin/ld: /tmp/ccPbNUIV.o: in function `mqtt::properties::~properties()':
data_publish.cpp:(.text._ZN4mqtt10propertiesD2Ev[_ZN4mqtt10propertiesD5Ev]+0x18): undefined reference to `MQTTProperties_free'
/usr/bin/ld: /tmp/ccPbNUIV.o: in function `mqtt::connect_options_builder::connect_options_builder()':
data_publish.cpp:(.text._ZN4mqtt23connect_options_builderC2Ev[_ZN4mqtt23connect_options_builderC5Ev]+0x18): undefined reference to `mqtt::connect_options::connect_options()'
/usr/bin/ld: /tmp/ccPbNUIV.o: in function `mqtt::connect_options_builder::finalize()':
data_publish.cpp:(.text._ZN4mqtt23connect_options_builder8finalizeEv[_ZN4mqtt23connect_options_builder8finalizeEv]+0x20): undefined reference to `mqtt::connect_options::connect_options(mqtt::connect_options const&)'
/usr/bin/ld: /tmp/ccPbNUIV.o: in function `encoded_file_persistence::keys() const':
data_publish.cpp:(.text._ZNK24encoded_file_persistence4keysEv[_ZNK24encoded_file_persistence4keysEv]+0x10c): undefined reference to `mqtt::string_collection::push_back(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status

### Installation
The SSL/TLS security is required by other software
**sudo apt-get install libssl-dev** 
Get basic C compiler, etc
**sudo apt-get install build-essential gcc make cmake cmake-gui cmake-curses-gui**
Also requires
**sudo apt-get install doxygen graphviz**
Getting Paho C libraries
**git clone https://github.com/eclipse/paho.mqtt.c.git
cd paho.mqtt.c
git checkout v1.3.8
cmake -Bbuild -H. -DPAHO_ENABLE_TESTING=OFF -DPAHO_BUILD_STATIC=ON -DPAHO_WITH_SSL=ON -DPAHO_HIGH_PERFORMANCE=ON
sudo cmake --build build/ --target install
sudo apt-get install build-essential gcc make cmake cmake-gui cmake-curses-gui
sudo ldconfig**

Getting Paho C++ libraries
**git clone https://github.com/eclipse/paho.mqtt.cpp**
**cd paho.mqtt.cpp**

**cmake -Bbuild -H. -DPAHO_BUILD_STATIC=ON -DPAHO_BUILD_DOCUMENTATION=TRUE -DPAHO_BUILD_SAMPLES=TRUE**

**sudo cmake --build build/ --target install**
**sudo ldconfig**

**Comment by fpagliughi** [comment]
The build system has been significantly upgraded in the last release.
