### ISSUE TITLE
Segmentation fault at the moment I publish a message

### ISSUE THREAD

**Issue by juamarCas** [eclipse/paho.mqtt.cpp#387]
Hi everyone!

I was able to connect my device to my MQTT broker, but, everytime i send a message to a topic I receive a segmentation fault. The first try i attemp to send a message was succesfull. 
I have a method to connect to my broker and send a message to a topic, and it sent the message without any problem, this is the piece of code I used:

```C++
void MQTTClient::Connect(const std::string& Client_ID){
    m_conOpt->set_keep_alive_interval(20);
    m_conOpt->set_clean_session(true);
    user_callback cb;

    m_persist = new sample_mem_persistence();

    m_client = new mqtt::client(m_url, Client_ID);
    
    m_client->set_callback(cb);

    try{
        m_client->connect(*m_conOpt);
        mqtt::message msg("testtopic", "Hello from PI!", 0, false);
        m_client->publish(msg);
    }catch(const mqtt::exception& exc){
        std::cout<<exc<<std::endl;
    }
}
```

Now, i want to have the publish action in another method, so i did the following:

```C++
void MQTTClient::Connect(const std::string& Client_ID){
    m_conOpt->set_keep_alive_interval(20);
    m_conOpt->set_clean_session(true);
    user_callback cb;

    m_persist = new sample_mem_persistence();

    m_client = new mqtt::client(m_url, Client_ID);
    
    m_client->set_callback(cb);

    try{
        m_client->connect(*m_conOpt);
    }catch(const mqtt::exception& exc){
        std::cout<<exc<<std::endl;
    }
}

void MQTTClient::PublishToTopic(const std::string& message, const std::string& topic){
    try{
        mqtt::message msg(topic, message, 0, false);
        m_client->publish(msg);
    }catch(const mqtt::exception& exc){
        std::cout<<exc<<std::endl;
    }
}

```
Anytime i run the code it causes a segmentation fault anytime i want to publish the message in _m\_client->publish(msg)_ line. 
Any help would be greate.

Thanks a lot!

**Comment by lucapalano** [comment]
Replace the following line:
`m_client->connect(*m_conOpt);`
with this one:
`m_client->connect(*m_conOpt)->wait();`

**Comment by fpagliughi** [comment]
@lucapalano is right; you should wait for the first connection to complete before trying to publish a message.

But it shouldn't segfault! I'll look into that.

**Comment by fpagliughi** [comment]
Good point, you're using the synchronous  `client`. In that case, you don't need to wait().
I'll test it out. But make sure nothing in the code it setting `m_client` back to NULL.

**Comment by fpagliughi** [comment]
I'm not able to reproduce it with any of the sample apps or unit tests...

But I think I just spotted it!
It's probably your `user_callback`.

You're giving the library (client) a callback object that lives in the stack of the `MQTTClient::Connect()` call. That object goes out of scope when your connect function returns. 

Then, when you call publish, the client tries to call the `delivery_complete()` member function in the callback object that you told it to use, but it doesn't exist anymore, and *boom*. Segfault.

Anyway, that's my guess.

**Comment by fpagliughi** [comment]
Also... You appear to be creating a persistence object, but not giving it to the client.

You can get rid of it if you don't need persistence. Or give it to the client constructor if you do want to use it.

**Comment by juamarCas** [comment]
@fpagliughi you were right! I wassent locating my user callback in the heap as the other variables! Thanks a lot.
