### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by avivruham** [eclipse/paho.mqtt.cpp#389]
Is it possible to add some documentation regarding thread safety?
Is the API thread safe?
Should I use synchronization mechanisms when subscribing/unsubscribing from multiple threads (for example)? Are the underlying data structures protected?

Best Regards,
Aviv

**Comment by fpagliughi** [comment]
Yes, the library can always use more documentation!

But to quickly answer your questions:

- The clients are thread-safe. You can publish/subscribe/etc from multiple threads simultaneously. There are internal mutexes to protect multi-threaded access.
- You should not make a blocking call from with a callback from the library (anything registered with `set_callback()`, `set_message_callback()`, etc). Callbacks are invoked from the one internal thread that is processing incoming packets from the network. So if you make a blocking call that expects an ACK, you will deadlock.
- The various data and options structs (like `connect_options`) are simple data structs. They are not thread protected.

**Comment by avivruham** [comment]
Thank you Frank for the quick response! I think that this is critical information for the users :)
Regarding the deadlock scenario:
Does it also includes calling variations of `token::wait()` / `token::get_connect_response()` `token::get_subscribe_response()` from `iaction_listener::on_success()` / `iaction_listener::on_failure()`?

**Comment by acidtonic** [comment]
Can I expect the connect_options struct to be not modified by the internal library after connect returns?

I have a lock for connect_options which is available for other threads (const) to see how the connection was made. I'm curious on the server thread if locking around connect() is all I need to do.

**Comment by fpagliughi** [comment]
@acidtonic , apologies, I didn't see you follow-on question. If you look at the closely header you will notice that the client takes the connect options parameter by value:
```
	token_ptr connect(connect_options options) override;
	token_ptr connect(connect_options options, void* userContext,
					  iaction_listener& cb) override;
```

The client caches a copy of the connect options, so the object you use to call the function is _never_ modified.

**Comment by fpagliughi** [comment]
Copy-pasted my blurb from above into the README with a few additions.
