### ISSUE TITLE
mqtt::create_options method typo

### ISSUE THREAD

**Issue by Ronakrit-Wongsuchai** [eclipse/paho.mqtt.cpp#392]
I believe there is a typo in [this line](https://github.com/eclipse/paho.mqtt.cpp/blob/2ff3d155dcd10564f1816675789284b4efd79eb7/src/mqtt/create_options.h#L115) it should be `set_mqtt_version()`

**Comment by fpagliughi** [comment]
Apologies, I missed this issue, but someone else mentioned it in #428, and it has been fixed.
