### ISSUE TITLE
disconnect_options does not support MQTT v5 properties correctly

### ISSUE THREAD

**Issue by marlonjames** [eclipse/paho.mqtt.cpp#394]
`disconnect_options` uses the non-v5 initializer:
https://github.com/eclipse/paho.mqtt.cpp/blob/990bea092a382bd9635e5e9d5e3da3f29da4e773/src/disconnect_options.cpp#L11

That initiliazer sets `MQTTAsync_disconnectOptions.struct_version` to 0:

https://github.com/eclipse/paho.mqtt.c/blob/556cd568345e47b70da603edc92f11ff94a6161f/src/MQTTAsync.h#L1452-L1453
```c
#define MQTTAsync_disconnectOptions_initializer { {'M', 'Q', 'T', 'D'}, 0, 0, NULL, NULL, NULL,\
	MQTTProperties_initializer, MQTTREASONCODE_SUCCESS, NULL, NULL }
```

When doing a disconnect with reason code and properties, `struct_version` must be 1 or greater or they are ignored:

https://github.com/eclipse/paho.mqtt.c/blob/556cd568345e47b70da603edc92f11ff94a6161f/src/MQTTAsyncUtils.c#L2579-L2583
```c
		if (m->c->MQTTVersion >= MQTTVERSION_5 && options->struct_version >= 1)
		{
			dis->command.properties = MQTTProperties_copy(&options->properties);
			dis->command.details.dis.reasonCode = options->reasonCode;
		}
```

`disconnect_options.opts_` is private and can't be accessed directly.

https://github.com/eclipse/paho.mqtt.cpp/blob/990bea092a382bd9635e5e9d5e3da3f29da4e773/src/mqtt/disconnect_options.h#L45

---
`disconnect_options` should support MQTT v5.

There is a v5 initializer available:

https://github.com/eclipse/paho.mqtt.c/blob/556cd568345e47b70da603edc92f11ff94a6161f/src/MQTTAsync.h#L1455-L1456
```c
#define MQTTAsync_disconnectOptions_initializer5 { {'M', 'Q', 'T', 'D'}, 1, 0, NULL, NULL, NULL,\
	MQTTProperties_initializer, MQTTREASONCODE_SUCCESS, NULL, NULL }
```

**Comment by fpagliughi** [comment]
Thanks! I have a tag for this kinda thing. I figured it would come up.

I'll have a look.

**Comment by fpagliughi** [comment]
Finally fixing this...

Sadly I have a constructor `disconnect_options(int timeout)`, so I can't use an `int mqttVersion` parameter to set the version the same way the connect options do it. 

Rather, we'll need a static initializer, used like:
```
auto opts = disconnect_options::v5();
```

I already put in matching initializers for the connect options.
