### ISSUE TITLE
Naming conventions of c++! All namespaces classes, methods are lowercase

### ISSUE THREAD

**Issue by jensweller** [eclipse/paho.mqtt.cpp#40]
Why not use the naming conventions of cpp. namespaces, classes, methods should written with Upper Camel Case.

**Comment by fpagliughi** [comment]
Apologies if the naming convention does not match the one used by your organization. Unfortunately, C++ has never had a specific convention for the language, and if there were one definitive convention, I would have to argue that it is the convention of the standard library that comes with the language.

The C++ standard library uses namespaces like:
`
std, std::chrono, std::literals::string_literals
`

And the standard library uses class names like:
`
vector, basic_string, ios_base, shared_ptr
`

So I would argue that we _are_ using the standard naming convention for C++.
