### ISSUE TITLE
exception after retrying a failed PUBLISH

### ISSUE THREAD

**Issue by bradleysmith** [eclipse/paho.mqtt.cpp#400]
Using paho mqtt.cpp v1.1 and mqtt.c v 1.31

I have a system up an running solid as a rock for between 1.5 and 6 days.
After receiving some data I pubish a small message to say that a database has been updated. The callback sequence looks like this:

**on_success()**
followed by
**delivery_complete()**

At the point of failure a somewhat unusual (I think) sequence of events occurs:

**on_failure()**

So we retry, using the token supplied in the failure callback. This time we get:

**delivery_complete()**
followed by
**on_failure()**

at which point my on_failure() handler will attempt to publish again and I get:

**delivery_complete()**

followed by a crash.

I appreciate that this is going to be nigh on impossible to reproduce. I am looking into the library code myself to see if I can see anything but perhaps someone has seen something similar? or that could be attributed to the same area of code?

Additional:

My mosquitto logs indicate (I think) that the first publish was successful:

1656342021: Received PUBLISH from 9545dfca-5e52-4bf9-8f85-3ead61c577c3 (d0, q2, r0, m5353, 'x/y/z/update', ... (292 bytes))
1656342021: Sending PUBREC to 9545dfca-5e52-4bf9-8f85-3ead61c577c3 (m5353, rc0)
1656342021: Received PUBREL from 9545dfca-5e52-4bf9-8f85-3ead61c577c3 (Mid: 5353)
1656342021: Sending PUBLISH to mqtt-explorer-f64f3f3f (d0, q0, r0, m0, 'x/y/z/update', ... (292 bytes))
1656342021: Sending PUBCOMP to 9545dfca-5e52-4bf9-8f85-3ead61c577c3 (m5353)

**Comment by fpagliughi** [comment]
I know this is an older issue with an older library version, but was the problem ever resolved?

I'm curious what you mean saying you try to re-publish using the same token. Can you share a code snippet if what was attempted.

**Comment by fpagliughi** [comment]
I'll close this as I believe the issue was resolved with a fix to double-callbacks in the upstream C library a while back. Feel free to re-open if there is any other problem.
