### ISSUE TITLE
I am trying to Build Paho CPP on windows and am getting this following error. How to solve this? My paho build is succesfully generated and createad a folder called mqtt/paho-c 

### ISSUE THREAD

**Issue by b-madhukar** [eclipse/paho.mqtt.cpp#404]
C:\Users\kmit\Desktop\paho.mqtt.cpp-master (1)\paho.mqtt.cpp-master>cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\mqtt\paho-cpp -DPAHO_BUILD_SAMPLES=ON -DPAHO_WITH_SSL=OFF -DCMAKE_PREFIX_PATH=C:\mqtt\paho-c
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PahoMqttC (missing: PAHO_MQTT_C_LIBRARIES)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPahoMqttC.cmake:33 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:26 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/kmit/Desktop/paho.mqtt.cpp-master (1)/paho.mqtt.cpp-master/build/CMakeFiles/CMakeOutput.log".

**Comment by maisunmonowar** [comment]
Try adding c_libraries path. Try this:
cmake -Bbuild -H. -DCMAKE_INSTALL_PREFIX=C:\mqtt\paho-cpp -DPAHO_BUILD_SAMPLES=ON -DPAHO_WITH_SSL=OFF -DCMAKE_PREFIX_PATH=C:\mqtt\paho-c -DPAHO_MQTT_C_LIBRARIES="C:\mqtt\paho-c\lib\paho-mqtt3a.lib"

**Comment by fpagliughi** [comment]
Most of these build issues have been fixed in v1.4.0 and later.
