### ISSUE TITLE
Without network connection, is_ connected() still returns true

### ISSUE THREAD

**Issue by xdy6248625** [eclipse/paho.mqtt.cpp#405]
In the main process of my project, I run a thread to detect whether the connection is disconnected. The approximate code is as follows:

```cpp
//main process
std::shared_ptr<mqtt::client> myClient;
monitor();
//...
void monitor() {
  monitor_thread = std::make_shared<std::thread>([this]() {
    if(!myClient->is_connected()) {
      LOG_INFO << "client disconnect";
      my_client->PubReconnect();
      sleep(1);
    }
    sleep(1); 
    }
  );
}
```

If myclient.is_ If connected() returns false, run Pubreconnect() to reconnect. During a test, I found that in the case of network disconnection, myClient.is_ connected()  still return true. I manually disconnected the network for several times during the operation and found that this unstable situation did occur.
In addition, my reconnection function code is as follows:

```cpp
bool PubReconnect() {
    while(!myClient->is_connected()) {
        try{
            myClient->connect(_connopts);
            sleep(1);
        } catch(const mqtt::exception&e) {
            LOG_ERROR << "publish reconnect fail for: " << e.what();
            sleep(1);
        }
    }
    LOG_INFO << "publish reconnect success";
    return true;
}
```

I don't know whether this problem is caused by the thread calling the function in a short time. I sincerely ask for your help, Thanks!

**Comment by fpagliughi** [comment]
I'm still not sure if there's a race condition of some sort in the C library's setting of the "is connected" boolean flag. I will continue to look into that.

But the more proper way to be alerted to the connection state is by monitoring events emitted by the client to tell you definitively that the connection was lost. It will even make the distinction between being accidentally lost (on_connection_lost) vs a reported disconnect by the server which sent a DISCONNECT packet (on_disconnect). With MQTT v5 connections, the DISCONNECT packet will even include a reason code and optional properties giving information about why your client was disconnected.

If you use automatic reconnects with the library, you can also get re-connection (on_connected) events to know when the library was able to re-establish the connection.

With the current version (<= v1.4.0) the way to do this is to register callbacks for the event(s) you want. The upcoming v1.5 library will also let you receive these through the consumer queue, serialized in with the incoming message stream.
