### ISSUE TITLE
When ConnectLost is invoked

### ISSUE THREAD

**Issue by 2751466366** [eclipse/paho.mqtt.cpp#415]
Hello, I use this library to set the heartbeat interval to 2 minutes. Why is the ConnectLost callback activated quickly when the network is unavailable? Sometimes it takes more than 2 minutes to activate.

**Comment by fpagliughi** [comment]
The connection lost condition is reported as soon as it is detected.

This can be really quick on wired networks - like if you pull the network cable out of your board/computer. But sometimes the network stack can get into a bad state, particularly on wireless networks, where the application thinks the connection is open, but no traffic is flowing through. Or maybe the server is hung with the port still open, but not responding. Things like that. That's where the keep alive heartbeat comes in. It's a last resort to insure that the full connection is working when there isn't any other traffic.

But the keep alive interval is how often the client should _send_ a PINGREQ. The broker is required to wait 1.5x before giving up and shutting the connection (3min, in your case). For the client, the spec is kinda vague, saying it should wait a "reasonable amount of time" for a response to its ping.

The MQTT v5 spec [3.1.2.10](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Keep_Alive_1):
> If the Keep Alive value is non-zero and the Server does not receive an MQTT Control Packet from the Client within one and a half times the Keep Alive time period, it MUST close the Network Connection to the Client as if the network had failed [MQTT-3.1.2-22].
>
 >If a Client does not receive a PINGRESP packet within a reasonable amount of time after it has sent a PINGREQ, it SHOULD close the Network Connection to the Server.
>
> A Keep Alive value of 0 has the effect of turning off the Keep Alive mechanism. If Keep Alive is 0 the Client is not obliged to send MQTT Control Packets on any particular schedule.

**Comment by fpagliughi** [comment]
I assume this answered the question? If not feel free to re-open the issue with any follow-up.

**Comment by 2751466366** [comment]
Thank you very much
