### ISSUE TITLE
Automatic subscription in async subscribe client

### ISSUE THREAD

**Issue by IMoyii** [eclipse/paho.mqtt.cpp#420]
Following the example of an asynchronous subscriber like "src/samples/async_subscribe.cpp", when I make the connection it automatically subscribes to the topic "#", so it receives all the messages that arrive at the broker.

Any way around this?

Regards.

**Comment by fpagliughi** [comment]
The code does not appear to be subscribing to '#'. It seems to only be subscribing to the topic "hello" with QoS = 1:
```
const std::string TOPIC("hello");
const int QOS = 1;

// ...

    cli_.subscribe(TOPIC, QOS, nullptr, subListener_);
```

But... it _is_ using a persistent session: `set_clean_session(false);` 
with the client ID:  `"paho_cpp_async_subcribe";`

Are you using a public broker? If so, perhaps someone used that same client ID to subscribe to '#' some time in the past, and you are picking up their session? A persistent session will remember past subscriptions.

And if you're using a private broker, the same thing might have happened from a previous test session?

**Comment by fpagliughi** [comment]
As a sanity check, maybe try running with a different client ID and see if the behavior changes. Try to come up with an ID that is totally random to avoid a conflict.

**Comment by IMoyii** [comment]
Thank you very much for your help.

The two solutions have worked for me, since I had previously subscribed to the "#" topic. So having ```set_clean_session(false);``` kept me subscribed, changing it to ```true``` fixes it.

In turn, if it were to try another ID client, it would make a new connection from 0.
