### ISSUE TITLE
Connection Lost Callback is not triggered

### ISSUE THREAD

**Issue by RAJKgu** [eclipse/paho.mqtt.cpp#421]
I am trying to test how the MQTT async client behaves in different scenarios. I started testing with my custom implementation. What I am doing once the client is connected to the server after a few seconds I disconnect my computer's wifi, this should need to call the`connection_lost` after the keepalive interval passed, I have used a 6-second keepalive interval in my code. So, I need to verify is something wrong with my code implementation. So I tested with a sample provided [here](https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/async_subscribe.cpp) at a 6-second keepalive interval. It also doesn't call the `connection_lost` callback.

Following is the broker configuration I am using for testing
```
broker:
  host: "broker.hivemq.com"
  port: 1883
```
I am not able to spot the actual problem, dropping my wifi connection should ideally need to invoke the function after the keepalive interval right?

**Comment by fpagliughi** [comment]
Yeah, losing the connection should cause the `conntction_lost` callback to fire. With wireless connections it sometimes isn't immediately noticed by the network stack, but the keepalive ping should definitely fail and notice the disconnection.

Did you figure this out?
