### ISSUE TITLE
paho-mqtt-cpp conan recipe is broken

### ISSUE THREAD

**Issue by tripleslash** [eclipse/paho.mqtt.cpp#424]
Output from conan install:

```
*********************************************************
Recipe 'paho-mqtt-cpp/1.2.0' seems broken.
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check it is updated to 2.0
*********************************************************
```

**Comment by fpagliughi** [comment]
Apologies for the slow response. We didn't create the conan build for the project. I actually have no idea who did!  And I still haven't ever tried conan, so would have no idea how to help, unless someone tells me something I can/should do with the CMake files here to make it easier for conan to support it.
