### ISSUE TITLE
sync_consume_v5.cpp bizarre behavior on Google Cloud's VM 

### ISSUE THREAD

**Issue by kedardimble** [eclipse/paho.mqtt.cpp#435]
I am currently working on 3 separate VM's on GCP. My broker is one VM, another one is publishing 200 msgs/sec to a topic, and the third is running sync_consume_v5.cpp. I am keeping all three of them on separate VMs to prevent them fighting with eachother for resources. To be frank, I have customized the original sync_consume_v5 code, but the logic is still the same. Endpoint is different and SSL was added.

When I run sync_consume_v5 on my Windows or Linux PC, it runs just fine. It sees and consumes all the 200 messages. However, when I run the same code on GCP's VM, it only consumes 32 messages every 30 seconds. I am decent with coding, but terrible at OS's and more so at VM's. 

Am I missing something? Is the code not supposed to be run on VM's? I can provide my code if needed (but did not feel necessary to include it since I am working with sample code).   Thank you.

**Comment by fpagliughi** [comment]
I'm sorry, I have no idea. I've never used a VM on GCP. But honestly, if something works fine on native hardware, but doesn't on a VM, I would initially suspect the VM.

**Comment by kedardimble** [comment]
Thanks Frank. I was able to fix it. Kind of hacky, but here is what I did.

1. I took the executable that was built on my Linux laptop and ran that on the VM. VM performance terrible again. 
2. I ran the same logic in Python using the appropriate Paho library. That code worked as expected on Linux and VM's. So obviously the VM was not throttling.
3. So finally, I copied the whole library on my Linux laptop (in /usr/local/lib) and replaced the same files on the VM with them.
4. Problem solved. My C++ code works beautifully on the VM now.

Makes me wonder if the library was built differently on the VM that it was on the laptop. I have no idea, but I am sure that both the times I followed the procedure as mentioned in the readme on paho.mqtt.cpp. The only difference, now that I am looking at the history, was that on the laptop I checked out v1.3.12 of paho.mqtt.c, while on the VM I checked out 1.4.

I thought someone might benefit from it, so I included a little too much of detail in this post.

Finally, thank you, Frank, Ian Craggs, and everyone else involved in the development of these libraries. Without all of your work, a lot of us would not have been able to do what we do with MQTT.

**Comment by fpagliughi** [comment]
Ah, interesting. To my knowledge 1.4 is a development branch of the Paho C library - still a work in progress; not released code. I haven't tested the C++ or Rust wrappers using it yet.

So with this new information, I would guess it's a problem in the 1.4 library, or some breaking change in it from 1.3.x which the C++ code is not properly handling.

So, yes, definitely run your code with the 1.3.12 C library.

**Comment by fpagliughi** [comment]
I'm going to close this. Feel free to re-open if anything new comes up.
