### ISSUE TITLE
Inaccurate publishing data results

### ISSUE THREAD

**Issue by Z-J-X** [eclipse/paho.mqtt.cpp#436]
When using the Mosquito service, the 'acl_file' file was configured to restrict publishing permissions. When using the 'paho. mqtt.cpp async' client to publish data using unauthorized 'topic', the return value and callback object 'iaction_listener' all displayed success.
When using the MQTT client tool MQTTX, the prompt "Error: Publish error: Not authorized" will appear.

```
[root@localhost config]#cat aclfile
topic read 123
topic write 123
```
async publish topic is 456

**Comment by fpagliughi** [comment]
Did it actually successfully publish the message (even though it was not supposed to be able to do so)?
Or did it fail, but claim that it succeeded?

**Comment by fpagliughi** [comment]
Closing on inactivity. Please feel free to re-open if there's additional information.
