### ISSUE TITLE
The sync_subscribe.cpp sample app leaks memory

### ISSUE THREAD

**Issue by wb2712** [eclipse/paho.mqtt.cpp#438]
![image](https://github.com/eclipse/paho.mqtt.cpp/assets/112671903/08db1588-657d-4502-a840-0a40e2a44fe8)
https://github.com/eclipse/paho.mqtt.cpp/issues/193
https://github.com/eclipse/paho.mqtt.cpp/issues/191

**Comment by wb2712** [comment]
n2: 149996269 0x4E5CC49: void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30)
  n1: 149996039 0x9CB8B4: void __gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::construct<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*&, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*&, unsigned long&) ()
   n1: 149996039 0x9CB6D8: void std::allocator_traits<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::construct<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*&, unsigned long&>(std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, char const*&, unsigned long&) ()
    n1: 149996039 0x9CB5D2: std::_Sp_counted_ptr_inplace<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<char const*&, unsigned long&>(std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&) ()
     n1: 149996039 0x9CB25C: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*&, std::_Sp_alloc_shared_tag<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char const*&, unsigned long&) ()
      n1: 149996039 0x9CAFC9: std::__shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char const*&, unsigned long&) ()
       n1: 149996039 0x9CAC44: std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::shared_ptr<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&>(std::_Sp_alloc_shared_tag<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char const*&, unsigned long&) ()
        n1: 149996039 0x9CA5E8: std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > std::allocate_shared<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char const*&, unsigned long&>(std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, char const*&, unsigned long&) ()
         n1: 149996039 0x9C9E19: std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > std::make_shared<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*&, unsigned long&>(char const*&, unsigned long&) ()
          n1: 149996039 0x9C96E8: mqtt::buffer_ref<char>::buffer_ref(char const*, unsigned long) ()
           n1: 149996039 0x9CE6D2: mqtt::message::set_payload(void const*, unsigned long) ()
            n1: 149996039 0x9CDEB5: mqtt::message::message(mqtt::buffer_ref<char>, MQTTAsync_message const&) ()
             n1: 149996039 0x9C5D9A: void __gnu_cxx::new_allocator<mqtt::message>::construct<mqtt::message, mqtt::buffer_ref<char>, MQTTAsync_message const&>(mqtt::message*, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) ()
              n1: 149996039 0x9C4A1A: void std::allocator_traits<std::allocator<mqtt::message> >::construct<mqtt::message, mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::allocator<mqtt::message>&, mqtt::message*, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) ()
               n1: 149996039 0x9C3450: std::_Sp_counted_ptr_inplace<mqtt::message, std::allocator<mqtt::message>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::allocator<mqtt::message>, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) ()
                n1: 149996039 0x9C135C: std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<mqtt::message, std::allocator<mqtt::message>, mqtt::buffer_ref<char>, MQTTAsync_message const&>(mqtt::message*&, std::_Sp_alloc_shared_tag<std::allocator<mqtt::message> >, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) ()
                 n1: 149996039 0x9BEEE3: std::__shared_ptr<mqtt::message, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<mqtt::message>, mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::_Sp_alloc_shared_tag<std::allocator<mqtt::message> >, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) ()
                  n1: 149996039 0x9BD1E0: std::shared_ptr<mqtt::message>::shared_ptr<std::allocator<mqtt::message>, mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::_Sp_alloc_shared_tag<std::allocator<mqtt::message> >, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) ()
                   n1: 149996039 0x9BAFB9: std::shared_ptr<mqtt::message> std::allocate_shared<mqtt::message, std::allocator<mqtt::message>, mqtt::buffer_ref<char>, MQTTAsync_message const&>(std::allocator<mqtt::message> const&, mqtt::buffer_ref<char>&&, MQTTAsync_message const&) ()
                    n1: 149996039 0x9B8AEB: std::shared_ptr<mqtt::message> std::make_shared<mqtt::message, mqtt::buffer_ref<char>, MQTTAsync_message const&>(mqtt::buffer_ref<char>&&, MQTTAsync_message const&) ()
                     n1: 149996039 0x9B6A9B: mqtt::message::create(mqtt::buffer_ref<char>, MQTTAsync_message const&) ()
                      n1: 149996039 0x9B0E8F: mqtt::async_client::on_message_arrived(void*, char*, int, MQTTAsync_message*) ()
                       n1: 149996039 0x4F4B55E: MQTTAsync_deliverMessage (in /usr/local/lib/libpaho-mqtt3as.so.1.3.12)
                        n1: 149996039 0x4F4B8A0: Protocol_processPublication (in /usr/local/lib/libpaho-mqtt3as.so.1.3.12)
                         n1: 149996039 0x4F5086B: MQTTProtocol_handlePublishes (in /usr/local/lib/libpaho-mqtt3as.so.1.3.12)
                          n1: 149996039 0x4F4CD41: MQTTAsync_cycle (in /usr/local/lib/libpaho-mqtt3as.so.1.3.12)
                           n1: 149996039 0x4F49ABC: MQTTAsync_receiveThread (in /usr/local/lib/libpaho-mqtt3as.so.1.3.12)
                            n1: 149996039 0x5188B42: start_thread (pthread_create.c:442)
                             n0: 149996039 0x5219BB3: clone (clone.S:100)

**Comment by fpagliughi** [comment]
What app did you test? Platform. Library versions?
I will try to reproduce.

**Comment by wb2712** [comment]
[async_subscribe.cpp.txt](https://github.com/eclipse/paho.mqtt.cpp/files/11595203/async_subscribe.cpp.txt)
It should be the reason for locking during callback
Does not cause implicit leaks when not locked

**Comment by wb2712** [comment]
![image](https://github.com/eclipse/paho.mqtt.cpp/assets/112671903/8116aad7-d82b-4f90-9c27-6718cec73d41)

ubuntu 22.04

**Comment by wb2712** [comment]
> What app did you test? Platform. Library versions? I will try to reproduce.

+1

**Comment by wb2712** [comment]
> What app did you test? Platform. Library versions? I will try to reproduce.

hi, is there any clue to the problem?
Adding a lock in the callback function will lead to memory growth. Is it a problem with my use?

**Comment by fpagliughi** [comment]
So the example app isn't leaking, but you added some code and now it appears to be leaking?

Looking at it, I wonder that maybe there isn't _exactly_ a leak, but rather memory is accumulating _inside_ the queue that you added. To my knowledge, in most implementations, `queue::pop()` doesn't doesn't destruct the value in the queue. Rather, it just moves an internal pointer past it. So the whole message is just sitting in the queue until sometime later that the queue pops off all of an internal block (maybe 512 messages) and then the internal block is reclaimed and everything in it is destructed.

Anyway, that's my guess.

Two other things I will note:
1. There is a thread-safe, locking, queue in the library which you can use. It has an internal mutex with a std::queue() to do just what you're doing a little more easily. **But** it has a `get()` function which specifically _moves_ the value out of the queue each time so that is does not leave a potentially huge block of memory in the queue indefinitely.
    https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/mqtt/thread_queue.h

2. The `message_arrived()` gets a smart pointer to the message. It would be _significantly_ more efficient to send that pointer to another thread than make a full, deep, copy of the the message and send that through the queue. That actually creates several copies... the temporary variable, which then gets _copied_ into the queue, and then potentially, later, copied out of the queue.

**Comment by wb2712** [comment]
> So the example app isn't leaking, but you added some code and now it appears to be leaking?
> 
> Looking at it, I wonder that maybe there isn't _exactly_ a leak, but rather memory is accumulating _inside_ the queue that you added. To my knowledge, in most implementations, `queue::pop()` doesn't doesn't destruct the value in the queue. Rather, it just moves an internal pointer past it. So the whole message is just sitting in the queue until sometime later that the queue pops off all of an internal block (maybe 512 messages) and then the internal block is reclaimed and everything in it is destructed.
> 
> Anyway, that's my guess.
> 
> Two other things I will note:
> 
> 1. There is a thread-safe, locking, queue in the library which you can use. It has an internal mutex with a std::queue() to do just what you're doing a little more easily. **But** it has a `get()` function which specifically _moves_ the value out of the queue each time so that is does not leave a potentially huge block of memory in the queue indefinitely.
>    https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/mqtt/thread_queue.h
> 2. The `message_arrived()` gets a smart pointer to the message. It would be _significantly_ more efficient to send that pointer to another thread than make a full, deep, copy of the the message and send that through the queue. That actually creates several copies... the temporary variable, which then gets _copied_ into the queue, and then potentially, later, copied out of the queue.

thread_queue.h still increases memory after use, get(), essentially the same as the method I use
The scenario I use is to hand over the received information to another thread for processing. In this multi-threaded scenario, to operate the same object, a lock must be used.
If receiving and processing are both in the same thread, there is no problem

**Comment by wb2712** [comment]
The problem is easy to reproduce, I just added a cross-thread processing and lock

**Comment by wb2712** [comment]
Are you sure it's GUB? Or is there something wrong with the way I'm using it?

**Comment by fpagliughi** [comment]
Wait… isn’t your main() thread blocked in the call to `cin.get()`?

If so, then the callback is filling the queue, but nothing is emptying it? The main thread is waiting for a key press and _not_ emptying the queue.

**Comment by wb2712** [comment]
Yes, my problem, because the QT environment executes fine, unnoticed. The program starts directly in the background, and the main thread will be blocked in std::tolower(std::cin.get()), resulting in undeleted
