### ISSUE TITLE
mqtt::async_client client giving access violation when I use ssl in the url

### ISSUE THREAD

**Issue by karthick-raj-ctct** [eclipse/paho.mqtt.cpp#441]
I am trying to create a secure connection with the latest paho cpp library getting access violation int the constructor mqtt::async_client, when I use the protocol as ssl in the server url. kindly provide some inputs to solve this. I used windows os and CMakeGUI to build the source, except this every thing works fine for me. OpenSSL version I used here is 3.2.0

**Comment by fpagliughi** [comment]
Have you tried or looked at the SSL example program?
https://github.com/eclipse/paho.mqtt.cpp/blob/master/src/samples/ssl_publish.cpp

Are you adding an `ssl_options` object to the connect options?

**Comment by karthick-raj-ctct** [comment]
yes, I am just running the sample program with my broker url in a secured manner.

**Comment by karthick-raj-ctct** [comment]
I think some discrepancy in the openssl library which I am using but not sure, help would be appreciated thanks.

**Comment by karthick-raj-ctct** [comment]
I have found this issue the library reference as well as actual exe was wrong. Thank you.
