### ISSUE TITLE
Call to async_client::disconnect()->wait() produces exception if client is already in disconnected state

### ISSUE THREAD

**Issue by Alexk12** [eclipse/paho.mqtt.cpp#443]
Call to async_client::disconnect()->wait() produces exception if client is already in disconnected state (for example, if connection is lost).

To Reproduce:

    1. Create async_client. Connect and subscribe.
    2. Make conditions for client to lost connection (callback receives lost connection call).
    3. Call client.disconnect()->wait()

Expected behavior:
Client should not produce an exception and just return if it is already in disconnected state.

Environment:

    OS: Windows
    Version: paho.mqtt.c 1.3.12 + paho.mqtt.cpp 1.2.0

**Comment by fpagliughi** [comment]
I'm not sure this would be considered a bug so much as a difference of opinion!

You probably want to know that your disconnect failed. There are a number of scenarios where an app wouldn't be aware that the connection was lost - like a simple publisher that didn't register any callbacks. In several circumstances the only way they would know that the connection was lost would be during an attempted clean disconnect.

The successful disconnect generally tells you:
- Your published messages were sent (unless you specified a disconnect timeout, then maybe not)
- The broker received your disconnect message, and the reason (v5)
- The broker knows you went away nicely and disposed your LWT message without firing it off

Does that make sense?
