### ISSUE TITLE
Windows TCP/TLS connect failure

### ISSUE THREAD

**Issue by Gitxiaozhu-oss** [eclipse/paho.mqtt.cpp#446]
Windows vs2019
    client_.set_callback(cb_);

    mqtt::connect_options connOpts;
    connOpts.set_clean_session(true);
    connOpts.set_user_name(USERNAME);
    connOpts.set_password(PASSWORD);
    connOpts.set_keep_alive_interval(600);

    mqtt::ssl_options sslOpts;
    sslOpts.set_ssl_version(MQTT_SSL_VERSION_TLS_1_2);
    sslOpts.set_verify(false);
    connOpts.set_ssl(sslOpts);
    
    try 
    {
        mqtt::token_ptr conntok = client_.connect(connOpts);
        conntok->wait();

        mqtt::token_ptr subtok = client_.subscribe(topic_.toStdString(), QOS, nullptr, cb_);
        subtok->wait();
    }
    catch (const mqtt::exception& exc) {
        qDebug() << "-----------------" << endl;
        qDebug()<< exc.what();
        qDebug()<<"connect faile";
    }

**Comment by Gitxiaozhu-oss** [comment]
Linux Ubuntu Normal use，Windows  TCP/TLS connect failure

**Comment by fpagliughi** [comment]
I updated the title so it's easier to understand. The original one is here. I'm getting a Windows machine set up to test this before the next release.

```
MQTT error [-1]: TCP/TLS connect failure
[mqtt server log]2023-07-20T01:03:31: New client connected from 162.129.123.167:57959 as 3300000001 (p2, c1, k600, u'test1'). 2023-07-20T01:03:34: OpenSSL Error[0]: error:0A000126:SSL routines::unexpected eof while reading 2023-07-20T01:03:34: Client 3300000001 closed its connection
```

**Comment by fpagliughi** [comment]
I could never reproduce this, and think maybe it was an issue with the incorrect URI for the server? 
Similar to #234.

If there's any more info, please feel free to re-open.
