### ISSUE TITLE
Win10+cmake+mingw+mqtt-1.2.0 error: 'mutex' is not a member of 'std'

### ISSUE THREAD

**Issue by Gitxiaozhu-oss** [eclipse/paho.mqtt.cpp#447]
admin@DESKTOP-D29TBDD MINGW64 ~/Desktop/windows-paho c-c++/build-c++-gcc
$ mingw32-make.exe
[  6%] Building CXX object src/CMakeFiles/paho-cpp-objs.dir/async_client.cpp.obj
In file included from C:\Users\admin\Desktop\windows-paho c-c++\paho.mqtt.cpp-master\src\mqtt/async_client.h:30,
                 from C:\Users\admin\Desktop\windows-paho c-c++\paho.mqtt.cpp-master\src\async_client.cpp:20:
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:73:37: error: 'mutex' is not a member of 'std'
  using guard = std::lock_guard<std::mutex>;
                                     ^~~~~
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:73:37: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:40:1:
+#include <mutex>
 #include <chrono>
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:73:37:
  using guard = std::lock_guard<std::mutex>;
                                     ^~~~~
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:73:37: error: 'mutex' is not a member of 'std'
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:73:37: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:73:42: error: template argument 1 is invalid
  using guard = std::lock_guard<std::mutex>;
                                          ^
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:75:44: error: 'mutex' is not a member of 'std'
  using unique_lock = std::unique_lock<std::mutex>;
                                            ^~~~~
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:75:44: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:75:44: error: 'mutex' is not a member of 'std'
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:75:44: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:75:49: error: template argument 1 is invalid
  using unique_lock = std::unique_lock<std::mutex>;
                                                 ^
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:78:15: error: 'mutex' in namespace 'std' does not name a type
  mutable std::mutex lock_;
               ^~~~~
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:78:10: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
  mutable std::mutex lock_;
          ^~~
C:/Users/admin/Desktop/WINDOW~1/PAHOMQ~1.CPP/src/mqtt/token.h:80:15: error: 'condition_variable' in namespace 'std' does not name a type
  mutable std::condition_variable cond_;

**Comment by fpagliughi** [comment]
I have no idea what this might be, but certainly this project requires a conforming C++-11 compiler. `mutex`, `condition_variable` and all those types are part of the standard C++11 library.
