### ISSUE TITLE
Can't create more than 64 client connections

### ISSUE THREAD

**Issue by AlfonsoSanz** [eclipse/paho.mqtt.cpp#449]
Clients after 64 connections return an MQTT error:
After creating 100 clients, if I try to connect them one by one to the broker, clients from 64 to 99 will give a Connect error [-1] on client.connect()->wait().

```
mqtt::connect_options connect_options = mqtt::connect_options();
std::vector<mqtt::async_client*> clients;
for (int i = 0; i < 100; i++) {
    clients.push_back(new mqtt::async_client("localhost", "cpp-mqtt-" + std::to_string(i)));
    clients[i]->start_consuming();
    try {
        clients[i]->connect(connect_options)->wait();
    } catch (const mqtt::exception& exc) {
        std::cerr << "\n  " << exc << std::endl;
        return 1;
    }
    clients[i]->subscribe("test-" + std::to_string(i), 0)->wait();
    std::cout << "Connected " + std::to_string(i) << std::endl;
}
```

I can not find any option or solution to increase the amount of possible connections.

**Comment by fpagliughi** [comment]
OK... I have to ask... What use case are you looking at where you need to be simultaneously connected to more than 64 different MQTT brokers?!?  :-)

Honestly curious.

The thinking when these libraries were created was that you would probably need one connection for a typical device; two for a bridge application; maybe a few more for something esoteric.  So the thought was never for a large number of connections.

But actually, this was question was discussed recently, in another GitHub issue, but I can't find it at the moment. It was either in this library, the Paho C lib, or the Rust one. This library and Rust both wrap the C lib. That's where the limit is likely getting hit, in the C lib. Or in the OS. 

What platform are you using?

**Comment by AlfonsoSanz** [comment]
I am not connecting to more than 64 brokers, I am connecting more than 64 different clients to the same broker.
The application is kind of complex, in summary it is for monitorization and control of simulated IoT devices and real physical models. For example, each simulated device needs to have a client_id and connection to the broker as a real device has, and also the interfaces that connect real/simulated devices require a connection to receive the real data and send instructions.
Basically, I have a separated thread for each device and all of them have an async_client. But apparently, I cannot connect them all. I may need to do a single client and use callbacks to each thread to redirect the messages, but it will require a rework and it is not a “digital twin” of a real device connection.
I am using Windows, I could try on Linux, but I doubt there would be any difference, also the Python MQTT Paho library was able to connect 100 clients without problems, which I do not know if it also uses the C library.
Any solution or help would be appreciated.

**Comment by fpagliughi** [comment]
Oh, and the Python library is not based on the C lib. So its implementation is totally different and not based on using `select()` or `(WSA)poll()` to wait on any/all incoming connections., and thus not beholden to this specific limit. _But_ quickly googling around indicates it would hit some OS limit. Not sure what that is, though.

**Comment by AlfonsoSanz** [comment]
Interesting! If it is platform related it might not be a problem since, even if this program is intended to run in a Windows Server for now, we are moving all our projects to Linux/Docker.
So I will try to run some tests in Linux with the library, and if it solves it, try to accelerate the migration to Linux.
Thanks for the suggestion @fpagliughi, I will comment on the results as soon as I run some test.

**Comment by fpagliughi** [comment]
Sorry I don't know. I'm not much of a Windows programmer myself.

Did you set FDSET_SIZE in a rebuild of the Paho C library? It sounds like that might just be step 1 to get this to work. From that same page above:

> It must be emphasized that defining FD_SETSIZE as a particular value has no effect on the actual number of sockets provided by a Windows Sockets service provider. This value only affects the FD_XXX macros used by the select and WSAPoll functions.

Unfortunately I don't even have a Windows machine to test this out at the moment.

But if you pursue the Windows idea and find a solution, please do update this issue. I will leave it open, then update the docs/README appropriately to help out the next person. Either way, let me know.

**Comment by fpagliughi** [comment]
@AlfonsoSanz Any resolution to this?

**Comment by AlfonsoSanz** [comment]
Sorry @fpagliughi no solution on my part, the project was migrated to Linux where this limitation does not appear.
Tried defining FDSET_SIZE and a couple of other quick solutions found on search without fixing it, but I did not spend much time trying to be honest.

**Comment by fpagliughi** [comment]
OK. Thanks for reporting it and keeping up with it as long as you did!
I'm going to say this is a platform issue beyond my control and close the issue. Please feel free to re-open if you discover anything new.
