### ISSUE TITLE
SSL/TLS

### ISSUE THREAD

**Issue by Woeker** [eclipse/paho.mqtt.cpp#452]
terminate called after throwing an instance of 'mqtt::exception'
  what():  MQTT error [-14]: Invalid protocol scheme
已放弃 (核心已转储)

**Comment by fpagliughi** [comment]
In order to use either of the secure protocols (`ssl://` or `wss://`) you must use versions of the Paho C and C++ libraries that were both built with OpenSSL support, using the `PAHO_WITH_SSL=TRUE` CMake flag for both libraries.

**Comment by lizziemac** [comment]
If compiling with the `PAHO_WITH_MQTT_C`, will the flag propagate to the C library automatically?

**Comment by fpagliughi** [comment]
@lizziemac Yes. `PAHO_WITH_MQTT_C` compiles the C library as a CMake subdirectory (via git submodule) which makes all the variables available to the subdirectory scope.

So all the build variables that have the same name are shared when you use it, like `PAHO_BUILD_SHARED`, `PAHO_BUILD_STATIC`, `PAHO_BUILD_SAMPLES`, etc.

Note that `PAHO_WITH_MQTT_C` is new, and still somewhat experimental. I am working to harden it for the next v1.4 release, including changes to the Paho C build to work better when included as a subdirectory. Pleas open an issue for any problem you have with it.

**Comment by lizziemac** [comment]
Noted, thank you!

As a precaution, I did build and install the C/C++ libraries separately with the `PAHO_WITH_SSL=TRUE` (and also tried `ON`), but I'm still seeing the same error as OP. I've tried providing the protocol as `ssl://` and `mqtts://`, like so:
```cpp
  std::string protocol = this->config->tls_enabled ? "ssl://" : "mqtt://";
  std::string server_uri =
      protocol + this->config->host + ":" + std::to_string(this->config->port);
    
  // Create the MQTT client
  mqtt::create_options create_opts(MQTTVERSION_5);
  this->client =
      std::make_shared<mqtt::async_client>(server_uri, CAMERA_ID, create_opts);
  LOGI("MQTT Version: %d", this->client->mqtt_version());
  
  //some other setup code
  
    if (this->config->tls_enabled) {
    auto ssl_builder = mqtt::ssl_options_builder();
    if (!this->config->ca_cert_file.empty()) {
      ssl_builder.trust_store(this->config->ca_cert_file);
    }
    if (!this->config->client_cert_file.empty() &&
        !this->config->client_key_file.empty()) {
      ssl_builder.key_store(this->config->client_cert_file)
          .private_key(this->config->client_key_file);
    }
    auto ssl = ssl_builder.finalize();
    opts_builder.ssl(std::move(ssl));
  }
```

is there anything I'm missing in the setup?

Thanks again for the help!

**Comment by fpagliughi** [comment]
Oh, yeah... make sure you link with the "s" version of the C library, like `libpaho-mqtt3as.so`.

When you build the C lib with SSL turned on, it still builds the non-SSL libraries, like `libpaho-mqtt3a.so` (not the lack of "s"), but it _also_ builds the SSL versions. You need to link to the correct one.

And, of course, make sure you build the C++ library using `PAHO_WITH_SSL=TRUE`. 

The C++ build will only create one library, but with the options you request, like whether to use SSL. That option for the C++ library mostly just tells it to link with the secure ("s") version of the C lib. The C++ library doesn't directly call SSL functions; or any network functions. It just calls into the C lib for that.

**Comment by lizziemac** [comment]
That worked, thanks so much!!

**Comment by fpagliughi** [comment]
Looks like this is good? If not, feel free to re-open.
