### ISSUE TITLE
How to maximize throughput while publishing

### ISSUE THREAD

**Issue by mvccogo** [eclipse/paho.mqtt.cpp#454]
Greetings, 

I'm trying to squeeze the most I can from the async client. I'm trying to embed it into an application that should publish entities' information in 30Hz, for around 2k entities. This demands about 60k messages being sent to the broker per second. I've thought about some alternatives and decided to go with a thread pool that shares the workload between publishing threads.

In this case, however, a few questions arised: 

1. If a thread's only function is to publish a given msg, should we call `publish()` or `publish()->wait()`?
 It is my understanding that, in this case, we do want to block that thread from finishing its execution (and thus being available to the pool) if the underlying client has not finished publishing the message yet. 
 
 2. Are there any meaningful performance gains from using one MQTT async client vs a std::vector of mqtt::async_client? 
 
 3. Are there any meaningful differences between a locking thread pool versus a lockfree concurrent queue? (such as [atomic_queue](https://github.com/max0x7ba/atomic_queue/) or [moodycamel's concurrentqueue](https://github.com/cameron314/concurrentqueue)  )
I guess this is mostly related to thread contention, but unsure how it relates to MQTT async client instances.

I did not find any examples for a multithread publisher app that uses a threadpool and/or a lockfree queue, so hopefully someone will chime in.

Thanks.

**Comment by fpagliughi** [comment]
The biggest thing to consider is what Quality of Service (QoS) you need for these messages. Is it OK to lose a few? (Then use QoS=0). Is it OK for the receiver to get duplicates if there are network issues? (Then use Qos=1). If no to both, then use QoS =2.

The higher the QoS, then, generally, the lower the throughput.

If you use QoS=0, then it doesn't matter too much if you `->wait()` for the publish to complete. The wait will finish as soon as the message is queued for transmission in the client. That's all. So it "competes" almost immediately.

For QoS=1, the `->wait()` will block the caller until the transaction completes - when the ack packet is returned from the server. So this is a delay of a full round-rip to the server.

For QoS=2, it's two full round trips to the server to complete the transaction.

So, if you want to move messages as fast as possible, don't `->wait()`. At least not in the publisher thread. You can always throw the returned tokens to another thread to wait for completion - and act accordingly on an error (re-try; report it to the user, etc).

**Comment by mvccogo** [comment]
QoS 0 is indeed being used - these are frame data that are sent continuously so missing one frame is not a big issue. 

Other than the wait() question itself, is there any benchmark on how these other factors come into play? (Multiple AsyncClients, lockless queue, etc). Knowing a "theoretical upper limit" could help me check if my implementation is too slow. 

Thanks for the input!

**Comment by fpagliughi** [comment]
OK. For QoS=0, even though it doesn't block for long, you can omit the `->wait()`. 

For a "theoretical upper limit", there are too many factors to just throw out a number, but a good indicator might be how much of the available network bandwidth is the client able to fill by itself. And if you can fill it from the client, do you have a server/broker that can keep up - especially given traffic from other publishers/subscribers.

Another thing to consider is messages/sec vs total bytes/sec. You can often scale up throughput by aggregating data into larger message payloads. That's not always possible, but when it is, it can help a lot.

Unfortunately, this client implementation isn't optimized for pure speed, so I would assume a single client is only filling a fraction of the available network bandwidth. In that case, you could probably increase throughput by running several clients in parallel, in different threads.

**Comment by mvccogo** [comment]
Thank you for the time! Valuable insights to think of during my development.
