### ISSUE TITLE
paho.mqtt.cpp  looks for PahoMqttC, but the package named   - eclipse-paho-mqtt-c.

### ISSUE THREAD

**Issue by shabelson** [eclipse/paho.mqtt.cpp#459]
Hi All
I am trying to build the repo. but keeps getting  - __package not found__ - error. 
checking the src/CMakeLists  -  it searches for __PahoMqttC__ 
BUT
The paho.Mqtt.C lib in the submodule is named  __eclipse-paho-mqtt-c__ and targets names are different. 

What am I missing?

**Comment by fpagliughi** [comment]
Yes the CMake build for this C++ library was created _before_ the Paho C project switched to CMake. So we have our own CMake _find_ for the C lib in [cmake/FindPahoMqttC.cmake](https://github.com/eclipse/paho.mqtt.cpp/blob/master/cmake/FindPahoMqttC.cmake), in which we used the target `PahoMqttC`.

This needs to be fixed at some point to avoid the confusion. There's already a ticket for that:
https://github.com/eclipse/paho.mqtt.cpp/issues/416

**Comment by fpagliughi** [comment]
Closing this. Track through #416
