### ISSUE TITLE
Building paho.mqtt.cpp: cmake doesn't pick up my c++ compiler correctly. 

### ISSUE THREAD

**Issue by AirborneLizard** [eclipse/paho.mqtt.cpp#463]
I'm trying to build paho.mqtt.cpp in a docker container and cmake doesn't pick up my c++ compiler correctly:

CMake Error at src/CMakeLists.txt:94 (target_compile_options):
Error evaluating generator expression:
$<CXX_COMPILER_ID:MSVC,Clang>
$<CXX_COMPILER_ID> expression requires one or zero parameters.

The container is based on Ubuntu 18.04 and it doesn't have MSVC.

paho.mqtt.c builds just fine. 

I've tried setting the CXX environment variables and that didn't help.

Also tried the cmake option -DCMAKE_CXX_COMPILER=clang++ and that didn't help either.

The relevant lines from my Dockerfile are:

# paho_mqtt_c
RUN git clone --no-checkout https://github.com/eclipse/paho.mqtt.c.git /usr/src/paho_mqtt_c && \
    cd /usr/src/paho_mqtt_c && \
    git checkout tags/v1.3.13 && \
    mkdir /usr/src/paho_mqtt_c/build && \
    cd /usr/src/paho_mqtt_c/build && \
    cmake /usr/src/paho_mqtt_c && \
    make && \
    make install

# paho_mqtt_cpp
RUN git clone --no-checkout https://github.com/eclipse/paho.mqtt.cpp.git /usr/src/paho_mqtt_cpp && \
    cd /usr/src/paho_mqtt_cpp && \
    git checkout tags/v1.3.1 && \
    mkdir /usr/src/paho_mqtt_cpp/build && \
    cd /usr/src/paho_mqtt_cpp/build && \
    cmake /usr/src/paho_mqtt_cpp -DCMAKE_CXX_COMPILER=clang++ -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=FALSE && -DPAHO_MQTT_C_PATH=/usr/src/paho_mqtt_c .\
    make && \
    make install && \
    rm -rf /usr/src/paho_mqtt_cpp && \
    rm -rf /usr/src/paho_mqtt_c

**Comment by AirborneLizard** [comment]
Thanks.

I'm using cmake version 3.10.2 which is the one that's in the Ubuntu 18.04 package store.

**Comment by fpagliughi** [comment]
OK. That confirms it. But no worries, I'll get it fixed. The build claims to work back to CMake v3.5, and I will make sure that remains true for this version of the library.

In the meantime, if you want to patch and build on your system, in `src/CMakeLists.txt`, at around line 97, there's a line:
```
  $<$<NOT:$<CXX_COMPILER_ID:MSVC,Clang>>:-Wall -Wextra>
```

Change it to:
```
$<$<NOT:$<OR:$<CXX_COMPILER_ID:MSVC>,$<CXX_COMPILER_ID:Clang>>>:-Wall -Wextra -Wpedantic>
```
