### ISSUE TITLE
Add getter for the connect_options object (connOpts_) in async_client

### ISSUE THREAD

**Issue by gary-metalle-rvl** [eclipse/paho.mqtt.cpp#473]
It would be nice to have a const (read-only) getter for the connOpts_ member variable so as to be able to determine what the connection settings are for a broker connection.

I've mentioned async_client but I'm guessing this is just as valid for other flavoured clients that have this member too.

**Comment by fpagliughi** [comment]
To be thread-safe it has to return a full copy. But it's in there.
