### ISSUE TITLE
error in install_paho_mqtt_c.sh in the installation process of the latest version of paho.mqtt.cpp

### ISSUE THREAD

**Issue by andreamanera** [eclipse/paho.mqtt.cpp#480]
Hello, 
I'd like to point out a small error in the repository (so small that I'd like to avoid opening a pull request), in fact in the  install_paho_mqtt_c.sh there is the line git checkout v1.3.7 after the lines to download the paho.mqtt.c repository and move into it, but this will result in an error during the build procedure of the paho.mqtt.cpp since, as specified in the README, this version of the c library is not suitable to build the latest version of the cpp library.

**Comment by fpagliughi** [comment]
Oh, thank you. The scripts in the top-level were mainly used to support the Travis CI, and I haven't thought to update them since that system became obsolete. But the script is still useful. I will update it.

...and hopefully get a new CI going soon.
