### ISSUE TITLE
Rustls C++ binding into the paho-mqtt

### ISSUE THREAD

**Issue by sarath3192** [eclipse/paho.mqtt.cpp#486]
I am working on a project where I have to integrate rustls C++  bindings Link (https://github.com/rustls/rustls-ffi?tab=readme-ov-file) into paho-mqtt C++ implementation. Is this possible?
If yes, please give details what to consider while doing this.

**Comment by fpagliughi** [comment]
Like the Paho Rust crate, this C++ library wraps the Paho C lib which does all the protocol I/O. To change the TLS implementation used, you would need to update the C lib.
