### ISSUE TITLE
Paho C library can be built along with the C++ library in a single step?

### ISSUE THREAD

**Issue by Ambica2022** [eclipse/paho.mqtt.cpp#489]
Hi,

I tried steps mentioned here https://github.com/eclipse/paho.mqtt.cpp?tab=readme-ov-file#building-the-paho-c-library-1 to build both paho C++ and C at a time. But not happening and encountering an error like C is not available. How to do this? Any clue? Thanks in advance.

Regards,
Ambica

**Comment by hmb** [comment]
Hi @Ambica2022, two things come to mind here:

- Did you clone and init the git submodules here?
- I hat to explicitly use the dedicated branch (v1.3,2), on master I had compilation errors

This results in the following build steps, for which I use a small Makefile:

````Makefile
PAHO_SRCDIR = paho.mqtt.cpp
PAHO_BUILDDIR = paho_build
PAHO_DESTDIR = ../paho_install

paho.mqtt.cpp/CHANGELOG.md:
	git clone --branch v1.3.2 --recurse-submodules https://github.com/eclipse/paho.mqtt.cpp.git

pahocpp-clone: paho.mqtt.cpp/CHANGELOG.md

pahocpp-cmake: pahocpp-clone
	cmake -B "$(PAHO_BUILDDIR)" -S "$(PAHO_SRCDIR)" -DPAHO_WITH_MQTT_C=ON

pahocpp: pahocpp-cmake
	DESTDIR=$(PAHO_DESTDIR) cmake --build "$(PAHO_BUILDDIR)" --target install
````

Then `make pahocpp` does the trick for me.

Good Luck
Holger

**Comment by Ambica2022** [comment]
Hi @hmb,

Thank you. It really helps. But when I use library with other CMake project encountering the below error.
/usr/bin/ld: cannot find -leclipse-paho-mqtt-c::paho-mqtt3as
collect2: error: ld returned 1 exit status

All CMake variables related to paho C++ library are properly set in my project's CMakeLists.txt file. 
I guess no CMake variables related to paho C library need to be set in my project's CMakeLists.txt file. Any clue on this?

Thanks,
Ambica.

**Comment by Ambica2022** [comment]
Thank you @hmb 

Regards,
Ambica
