### ISSUE TITLE
Build errors in Visual Studio 2022

### ISSUE THREAD

**Issue by Wolfgg73** [eclipse/paho.mqtt.cpp#490]
In the recent months, I finished a series of programs, all based on the PAHO MQTT CPP package. They all worked in Debug mode, very well. 
When I finally started to build the release versions, I received a series of Linker errors. There were several posts about the issues. My understanding was that I made a mistake just at the beginning of the project.  

So I decided to start from scratch and re-cloned the C and C++ codes. I started the cross-compiling process. After several tries and re-tries (and reading), I ended up twice with created builds without error messages. However, when using them, I always end up now with the following errors - in debug and release mode. I have the feeling going in circles.
Looking for nudges. ;-) . I would also appreciate paying for a virtual meeting session with an experienced software developer, helping me out here. 

Configuration: Visual Studio 2022, CMakeGUI. 

Rebuild started at 14:51...
1>------ Rebuild All started: Project: ml4TwinCrossCompiled, Configuration: Debug x64 ------
1>ml4TwinCrossCompiled.cpp
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_closesocket referenced in function Socket_close_only
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_connect referenced in function Socket_new
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_ioctlsocket referenced in function Socket_setnonblocking
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_getpeername referenced in function Socket_getpeer
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_htons referenced in function Socket_new
1>paho-mqtt3a-static.lib(WebSocket.obj) : error LNK2001: unresolved external symbol __imp_htons
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_recv referenced in function Socket_getch
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_shutdown referenced in function Socket_close_only
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_socket referenced in function Socket_new
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_WSAStartup referenced in function Socket_outInitialize
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_WSACleanup referenced in function Socket_outTerminate
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_WSAGetLastError referenced in function Socket_error
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_WSASend referenced in function Socket_writev
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_WSAAddressToStringW referenced in function Socket_getaddrname
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_WSAPoll referenced in function Socket_getReadySocket
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_getaddrinfo referenced in function Socket_new
1>paho-mqtt3a-static.lib(Socket.obj) : error LNK2019: unresolved external symbol __imp_freeaddrinfo referenced in function Socket_new
1>paho-mqtt3a-static.lib(MQTTAsyncUtils.obj) : error LNK2019: unresolved external symbol __imp_getsockopt referenced in function MQTTAsync_connecting
1>paho-mqtt3a-static.lib(WebSocket.obj) : error LNK2019: unresolved external symbol __imp_ntohs referenced in function WebSocket_receiveFrame
1>E:\menschlicht\Repos\ml4TwinCrossCompiled\x64\Debug\ml4TwinCrossCompiled.exe : fatal error LNK1120: 18 unresolved externals
1>Done building project "ml4TwinCrossCompiled.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Rebuild completed at 14:52 and took 01.402 seconds ==========

**Comment by Wolfgg73** [comment]
Sorted. Did not create myself debug and release versions 
cmake --build build/ --target install --config Debug
cmake --build build/ --target install --config Release

**Comment by Wolfgg73** [comment]
And added #pragma comment(lib, "Ws2_32.lib")

**Comment by fpagliughi** [comment]
The transient dependency for `ws2_32.lib` should now be fixed in master, coming to the v1.4 release.

**Comment by fpagliughi** [comment]
I believe this is fixed. If not, please re-open.
