### ISSUE TITLE
paho-mqtt3a-static not found（does not already exist）

### ISSUE THREAD

**Issue by 1096233486** [eclipse/paho.mqtt.cpp#508]
please help me😥,my problem like this:
im install on windows,i have success install c,but i can't install c++.
print :"CMake Error at src/CMakeLists.txt:82 (target_link_libraries):
  Target "paho-mqttpp3-static" links to:

    eclipse-paho-mqtt-c::paho-mqtt3a-static

  but the target was not found.  Possible reasons include:"
  cmake-gui:cmake version 3.30.1;vs:17 2022
who can help me,thank you very much!
![image](https://github.com/user-attachments/assets/9cb5ad8b-9f7e-4704-94d9-8fe01378b336)

**Comment by fpagliughi** [comment]
See #500

**Comment by fpagliughi** [comment]
Looks like #500 answers this. Feel free to reopen if not.
