### ISSUE TITLE
'utf-8' codec can't decode byte 0xa6 in position 86: invalid start byte

### ISSUE THREAD

**Issue by carlosjoserg** [eclipse/paho.mqtt.cpp#516]
Hi there, I'm having the same or at least very similar issue as the one described here --> https://github.com/eclipse/paho.mqtt.python/issues/173

Anyone using `paho.mqtt.cpp` experiencing the same?

The main problem is that I haven't been able to reproduce the issue, it just "happens" once in a while. Any idea what the cause might be?

Thanks!

**Comment by fpagliughi** [comment]
Can you show the error, and perhaps a trace from the library showing the error. I haven't seen something like this.

**Comment by carlosjoserg** [comment]
Thanks @fpagliughi ! We found out that, in our case, it seems that is due to an error in a layer above the paho library, so closing the issue for the moment. Best,
