### ISSUE TITLE
Not publish when conncetion restablished

### ISSUE THREAD

**Issue by ravikasyap1717** [eclipse/paho.mqtt.cpp#54]
Hello Sir, 

After running the code,suppose connection lost and passes messgae.It throws exception and come back out of program.Like in python it keeps the message in queue and as soon as connection established it publish all previous message.
Which api should you which will work as python publish.My code is 

[pub.txt](https://github.com/eclipse/paho.mqtt.cpp/files/796137/pub.txt)
 
also i am not able to get.message() in mqtt exception.
How will it support Automatic Reconnect and Offline Buffering.

Thanks
Ravi

**Comment by fpagliughi** [comment]
This should all be working in the latest code from the develop branch: automatic reconnect, easy manual reconnect [via async_client::reconnect()], and off-line buffering.

See the updated samples.
