### ISSUE TITLE
CMake doesn't build against Paho C development tree

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.cpp#67]
As we support new versions of the underlying MQTT C library, it's often convenient to build against the development tree of the C library, without installing it (and overwriting a stable version). This is supported in our GNU Make build system using the DEVELOP=1 flag.

The problem is that the C library does not use the standard include/ and lib/ placement of files, as required by CMake:

    ## extract Paho MQTT C include directory
    get_filename_component(PAHO_MQTT_C_INC_DIR ${PAHO_MQTT_C_PATH}/include ABSOLUTE)

    ## extract Paho MQTT C library directory
    get_filename_component(PAHO_MQTT_C_LIB_DIR ${PAHO_MQTT_C_PATH}/lib ABSOLUTE)

In the dev tree, 
Headers are in ${PAHO_MQTT_C_PATH}/src
Libraries are in ${PAHO_MQTT_C_PATH}/build/output

So, just setting PAHO_MQTT_C_PATH isn't sufficient.

@guilhermeferreira

**Comment by guilhermeferreira** [comment]
@fpagliughi check pull request #69.

**Comment by fpagliughi** [comment]
Works great, thanks!

**Comment by fpagliughi** [comment]
Actually, the library builds but the samples don't.
Do you need to also do something similar for the samples?

I got this:

 $ cmake -DPAHO_BUILD_SAMPLES=TRUE -DPAHO_MQTT_C_PATH=../../paho.mqtt.c ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fmp/mqtt/paho.mqtt.cpp.git/build

 $ make
Scanning dependencies of target common_obj
[  5%] Building CXX object src/CMakeFiles/common_obj.dir/async_client.cpp.o
[ 11%] Building CXX object src/CMakeFiles/common_obj.dir/client.cpp.o
[ 17%] Building CXX object src/CMakeFiles/common_obj.dir/disconnect_options.cpp.o
[ 23%] Building CXX object src/CMakeFiles/common_obj.dir/iclient_persistence.cpp.o
[ 29%] Building CXX object src/CMakeFiles/common_obj.dir/message.cpp.o
[ 35%] Building CXX object src/CMakeFiles/common_obj.dir/response_options.cpp.o
[ 41%] Building CXX object src/CMakeFiles/common_obj.dir/token.cpp.o
[ 47%] Building CXX object src/CMakeFiles/common_obj.dir/topic.cpp.o
[ 52%] Building CXX object src/CMakeFiles/common_obj.dir/connect_options.cpp.o
[ 58%] Building CXX object src/CMakeFiles/common_obj.dir/will_options.cpp.o
[ 58%] Built target common_obj
Scanning dependencies of target paho-mqttpp3
[ 64%] Linking CXX shared library libpaho-mqttpp3.so
[ 64%] Built target paho-mqttpp3
Scanning dependencies of target sync_publish
[ 70%] Building CXX object src/samples/CMakeFiles/sync_publish.dir/sync_publish.cpp.o
In file included from /home/fmp/mqtt/paho.mqtt.cpp.git/src/mqtt/client.h:27:0,
                 from /home/fmp/mqtt/paho.mqtt.cpp.git/src/samples/sync_publish.cpp:27:
/home/fmp/mqtt/paho.mqtt.cpp.git/src/mqtt/async_client.h:27:23: fatal error: MQTTAsync.h: No such file or directory
compilation terminated.
src/samples/CMakeFiles/sync_publish.dir/build.make:62: recipe for target 'src/samples/CMakeFiles/sync_publish.dir/sync_publish.cpp.o' failed
make[2]: *** [src/samples/CMakeFiles/sync_publish.dir/sync_publish.cpp.o] Error 1
CMakeFiles/Makefile2:201: recipe for target 'src/samples/CMakeFiles/sync_publish.dir/all' failed
make[1]: *** [src/samples/CMakeFiles/sync_publish.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by guilhermeferreira** [comment]
Yes @fpagliughi, I missed the samples' CMakeLists.txt. My fault.

[get_filename_component(PAHO_MQTT_C_INC_DIR ${PAHO_MQTT_C_PATH}/include ABSOLUTE)](https://github.com/eclipse/paho.mqtt.cpp/blob/develop/src/samples/CMakeLists.txt#L20)

[get_filename_component(PAHO_MQTT_CPP_INC_DIR ${CMAKE_SOURCE_DIR}/src ABSOLUTE)](https://github.com/eclipse/paho.mqtt.cpp/blob/develop/src/samples/CMakeLists.txt#L23)

I guess we can reuse the same variables available in the src/CMakeLists.txt. I'll try that.

**Comment by guilhermeferreira** [comment]
@fpagliughi please check the solution in pull request #72.

Also, there is a problem with the SSL conditional compilation. I'll provide a solution for this in the next few hours.

**Comment by fpagliughi** [comment]
I don't think that we need to be _so_ worried about conditionally compiling SSL features. The Paho C library needs to turn it off so that it can compile on a system lacking the OpenSSL library.

But the C++ library, with SSL, just manages a few strings in the `ssl_options` class, so it's not a huge burden to support it. If linked against a C library that doesn't support SSL, we're just told that the "ssh://..." connection type is unknown.

I'm a little more worried about someone compiling out SSL support from the C++ library, and then running it with a C library that does support SSL. In that case, are we properly initializing the connect options?

With that worry in mind I removed a few of the conditional compilation #if's from the code, for now. But in the long run it's OK to have that support as long as we know that it works with each combination of support - or lack there of - in both libraries.
