### ISSUE TITLE
Provide a way to pass TLS options to underlying Paho C Client lib

### ISSUE THREAD

**Issue by prateekbansal** [eclipse/paho.mqtt.cpp#7]
I need to enable TLS option for my MQTT client. I need to have a way to set SSL options when the `OPENSSL` compiler flag is enabled.

**Comment by guilhermeferreira** [comment]
Hi, you can check my branch #13. It's still experimental. Any advice is welcome.

**Comment by fpagliughi** [comment]
Added in 43cc619d0c098ebc9b7eae05cb1d89eb8b6d095b and patched/updated in 2dd74796d5ef4e26fa1f0a74f1e4ec8b9cf08e2f
