### ISSUE TITLE
CMake needs to specify -std=c++11 for older compilers

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.cpp#70]
Tested CMake with a variety of compilers on Mint17/Ubuntu 14.04:
  g++-4.8, 4.9, 5.4, 6.2
  clang++3.6, 3.8

Of the compilers tested, only g++-6 built properly. The other compilers require the flag "--std=c++11" 
g++ 6.x defaults to -std=gnu++14, but I believe all the others still use C++98 by default.

I suppose we can force the `c++11` standard. The library doesn't currently use anything from C++14, though I believe it would still be compatible with applications compiled to a newer standard. But if CMake could detect the compiler and _not_ set the standard backward for g++ 6 or newer, that would be cool.

This is the type of output I got from builds with all those other compilers:

  $ cmake -DCMAKE_CXX_COMPILER=g++-4.8 -DPAHO_MQTT_C_PATH=../../paho.mqtt.c ..
  -- The C compiler identification is GNU 4.9.4
  -- The CXX compiler identification is GNU 4.8.5
  ...
  -- Build files have been written to: /home/fmp/mqtt/paho.mqtt.cpp.merge.git/build
  $ make
  Scanning dependencies of target common_obj
  [ 10%] Building CXX object src/CMakeFiles/common_obj.dir/async_client.cpp.o
  In file included from /usr/include/c++/4.8/thread:35:0,
                 from /home/fmp/mqtt/paho.mqtt.cpp.merge.git/src/mqtt/token.h:33,
                 from /home/fmp/mqtt/paho.mqtt.cpp.merge.git/src/mqtt/async_client.h:28,
                 from /home/fmp/mqtt/paho.mqtt.cpp.merge.git/src/async_client.cpp:19:
  /usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support  for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
   #error This file requires compiler and library support for the \
    ^

@guilhermeferreira

**Comment by fpagliughi** [comment]
Oh, BTW this was with CMake v2.8.12

Perhaps versions prior to CMake v3.1, don't honor the CMAKE_CXX_STANDARD setting?
set(CMAKE_CXX_STANDARD 11)

**Comment by guilhermeferreira** [comment]
You are right. It seems a problem related to the combination of certain GCC and CMake versions. I'll check that.

**Comment by fpagliughi** [comment]
If this proves difficult, then don't worry about it. I don't want to spend too much time looking backwards. We can make a note of it in the build instructions and move on.

**Comment by fpagliughi** [comment]
This is likely the best we'll get without a lot of effort. I added instructions on how to upgrade the CMake on Ubuntu 14.04 to the README.md file. 4049f827c2990b80ee8d5da29a874bd5446adc60

**Comment by guilhermeferreira** [comment]
I haven't seen this yet. Please, you might keep it opened. Right now I can't say how complicated it is.

**Comment by fpagliughi** [comment]
Sure, if you want to keep looking at it.

**Comment by guilhermeferreira** [comment]
Hey @fpagliughi, check PR #89

**Comment by dontsovcmc** [comment]
It helps, thanks!
