### ISSUE TITLE
ssl connection problem

### ISSUE THREAD

**Issue by codavide** [eclipse/paho.mqtt.cpp#71]
Hi,
I'm trying to use the paho.mqtt.cpp library to make a connectiion to my local mqtt mosquitto broker. 
I have generated the certificates for my server and configured mosquitto using this file
[mosquitto-m2mqtt.conf.txt](https://github.com/eclipse/paho.mqtt.cpp/files/909478/mosquitto-m2mqtt.conf.txt)

Then, I have compiled the paho-mqtt-cpp project and I have tried to use the ssl_publish sample to make a connection to my server, modifying the sample code in this way:

const string DFLT_ADDRESS {"ssl://127.0.0.0.1:1883"};

sslopts.set_trust_store("/home/pi/mosquitto-certs/m2mqtt_ca.crt");

And I have commented the line with the setting of user and password, since I'm not using them.

When I launch the ssl_publish, this is the output:

Initializing for server 'ssl://127.0.0.0.1:1883'...
  ...OK

Connecting...
Waiting for the connection...
Error: MQTT exception -1

I think that the broker is working, because using another java application I'm able to connect to it, using that certificate.

Do you have any suggestions? Am I doing something wrong?

Thanks,
Davide

**Comment by fpagliughi** [comment]
I finally found something that could do this... The GNU Makefile in the samples directory was linking the ssl_publish sample to the non-SSL version of the Paho C library. I just pushed the fix for that to the 'develop' branch.

Please make sure that you're linking to the Paho C library `paho-mqtt3as` (with the 's' at the end).

I tested this against the certificates in the Paho C test directory. I ran mosquitto with the configuration from there:

```
git clone https://github.com/eclipse/paho.mqtt.c.git
cd paho.mqtt.c
mosquitto -c test/tls-testing/mosquitto.conf
```

And then I used the file "test-root-ca.crt" from that directory (paho.mqq.c/test/tls-testing) as the trust store for ssl_publish. That all worked for me.

Other than that, the C++ library just passes the names of the SSL/TLS certificates down to the C library. If there are still issues, perhaps we can get help from the folks working directly with the C library.

**Comment by codavide** [comment]
Thank you very much for the suggestions!

I will try it immediately and then I will inform you if this work.

**Comment by codavide** [comment]
OK,
thank you again,
I have tested ssl_publish on an ubuntu machine and,, following your iindications, it works properly, 
But I have stll the same problem indicated in my first post, running it in my raspberry (with the same configuration and certificates).

Some other hints:
- sync_publisher works also on the raspberry, it iconnects itself to the mosquitto correctly.
- I have started mosquitto in verbose mode and when I start the ssl_publish client, it doesn't print on console (it is not a TLS handshake problem). It doesn't receive the connection.

Please, let me know if you have some other suggestion,

**Comment by fpagliughi** [comment]
So, if I understand... It works over localhost on either an Ubuntu PC or a Raspberry Pi, but if you try to connect a client on the Pi to the mosquitto broker on a PC, it doesn't work?

Does it work with another client across this connection? (Java client or maybe mosquitto utility like mosquitto_pub)? Could there be a firewall getting in the way? Or the server configured for only localhost?

I have a few hundred RPi's at my office, so I can try this as well. But I won't be there for a few days.

**Comment by codavide** [comment]
No sorry I have not been clear,
I have installed the paho.mqtt library and the mosquitto server both on the ubuntu PC and on the raspberry Pi, and for both, I have tested the localhost connection, running mosquitto using the same configuration that you have indicated: test/tls-testing/mosquitto.conf.

If I run ssl_publish on the Ubuntu PC, the connection to the local mosquitto works.
if I run ssl_publish on the Raspberry Pi, the connection to the local msquitto doesn't work.

I hope to have been more clear now,

**Comment by fpagliughi** [comment]
Oh. OK. I've got it now. I will test that as soon as I can.

**Comment by fpagliughi** [comment]
I tested on a RaspberryPi, and it worked as expected. I did not see a problem.

I'm using Raspbian Jessie on an RPi2, and I did a full apt-get update/upgrade before starting the tests. This also updated my version of mosquitto:
```
$ uname -a
Linux thrivepi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

$ mosquitto -h
mosquitto version 1.4.11 (build date Mon, 20 Feb 2017 22:47:27 +0000)
...
```
I tested with the latest development version of both Paho C & C++ (the 'develop' branches of each, as of this morning) and did a native build of both using GCC v 4.9.2.

The sample showed the usual output:
```
$ ./ssl_publish 
Initializing for server 'ssl://localhost:18885'...
  ...OK

Connecting...
Waiting for the connection...
  ...OK

Sending message...
	Delivery complete for token:   ...OK

Sending next message...
1
	Delivery complete for token: 2
  ...OK

Disconnecting...
  ...OK
```
and mosquitto (running with the verbose '-v' option) showed:
```
1492447514: New connection from 127.0.0.1 on port 18885.
1492447514: New client connected from 127.0.0.1 as CppAsyncPublisherSSL (c1, k60, u'testuser').
1492447514: Sending CONNACK to CppAsyncPublisherSSL (0, 0)
1492447514: Received PUBLISH from CppAsyncPublisherSSL (d0, q1, r0, m1, 'hello', ... (0 bytes))
1492447514: Sending PUBACK to CppAsyncPublisherSSL (Mid: 1)
1492447514: Received PUBLISH from CppAsyncPublisherSSL (d0, q1, r0, m2, 'hello', ... (0 bytes))
1492447514: Sending PUBACK to CppAsyncPublisherSSL (Mid: 2)
1492447514: Received DISCONNECT from CppAsyncPublisherSSL
1492447514: Client CppAsyncPublisherSSL disconnected.
```

**Comment by codavide** [comment]
OK, thank you very much for the test,
in my tests I have used the master version of paho-mqtt-c and not the develop branch. I will try with that branch and then I will let you know the result.

**Comment by fpagliughi** [comment]
This seems to be working now.
