### ISSUE TITLE
[Suggestion] Make connect_options::opts_ visible for derived classes

### ISSUE THREAD

**Issue by okvorb** [eclipse/paho.mqtt.cpp#77]
Now there is no way to set/get data from underlying C connection structure if no setter/getter method explicitly defined. It is very easy to fix by applying protected visibility for opts_ member.

**Comment by fpagliughi** [comment]
That seems reasonable one way or the other - make the options classes overridable or finish the full coverage of the C struct with getters/setters. 

I was planning on adding full coverage of the underlying C struct for the 1.0 release of the library within the next few weeks, although I have yet to look at the automatic-reconnect capability of the C library and the implications it might have,

But I hadn't thought of making the options classes overridable. Other than making the data members protected, I suppose the classes would need virtual destructors.

Just out of curiosity, what are you trying to accomplish by overriding the connect_options class?

**Comment by okvorb** [comment]
I just want to enable ssl options and automatic reconnect feature. That is why I need to get access to the underlying C struct. Actually I have just made opts_ member protected and created derived class and that's it! Everything works fine. There is no need to have virtual destructor for connect_options class because it is a super simple wrapper for C struct and it is reasonable to leave it so. The only thing I am missing now is offline buffering options (MQTTAsync_createOptions). Are you planning to implement it for the 1.0 release? Consider to replace MQTTAsync_create calls with MQTTAsync_createWithOptions analog that accepts additional argument of MQTTAsync_createOptions type. I can create a pull request. Does it make sense? I am looking forward to the 1.0 release. It's the only really nice c++ mqtt client that I know for now.

**Comment by fpagliughi** [comment]
The SSL options are already available. Have you been working with the latest 'develop' branch? 

And, yes. The idea for the C++ v1.0 release is to have full coverage of all the features of the upcoming Paho C v1.2 library, which will be released at the same time.

**Comment by okvorb** [comment]
I have been working with master branch but will have a look at the develop branch. Thanks.

**Comment by fpagliughi** [comment]
OK. Sorry to flip-flop!
The latest (fairly stable) code was just pushed to 'master'. This builds against the released Paho C, v1.1.

The 'develop' branch will be changing rapidly over the next few weeks as we push to the C++ v1.0 release. This will build against the upcoming Paho C v1.2 (the current 'develop' branch of the C library).

So use the develop branch with caution.

**Comment by fpagliughi** [comment]
I think I'm closing in on all of your requirements. Have a look at the latest code in the develop branch. The `createWithOptions` is covered with some new  client constructors, and the `connect_options` covers the latest version of the underlying C connect structure. I'm sure I've missed something, but will give it a review or two before the release. But if you spot something, let me know.

**Comment by okvorb** [comment]
It looks like everything is covered for now. Thanks.
