### ISSUE TITLE
[Breaking change] Convert integer time values to std::chrono duration values 

### ISSUE THREAD

**Issue by fpagliughi** [eclipse/paho.mqtt.cpp#78]
In order to avoid confusion about different time units throughout the API, convert methods that take integer time values to take chrono duration types.

From:
```
void set_keep_alive_interval(int keepAliveInterval);
```
to:
```
template <class Rep, class Period>
void set_keep_alive_interval(const std::chrono::duration<Rep, Period>& keepAliveInterval) { ... }
```

These can also co-exist to keep backward compatibility. So we can have both.

But the getters that return a time value should return an appropriate duration value, like:
```
std::chrono::seconds get_keep_alive_interval() const;
```

**Comment by guilhermeferreira** [comment]
@fpagliughi , are you considering the use of suffixes `_for` and `_until` in the Paho API? Those are used by the C++ Standard Library. The `_for` indicates the use of `std::chrono::duration` parameter, while the `_until` uses `std::chrono::time_point`. I guess the `token`´s method `wait_for_completion()` falls in this category too. 

```
class connection_options {
  void keep_alive_for(std::chrono::duration d);
  void keep_alive_until(std::chrono::time_point tp);
};

class token {
  void wait_completion_for(std::chrono::duration d);
  void wait_completion_until(std::chrono::time_point tp);
};
```

**Comment by fpagliughi** [comment]
I typically use `_for` and `_until` to do blocking waits, but `wait_completion_for` sounds more like Yoda than proper English. IIRC, I took the names from the Java API, or at least the "completion" part. If anything, I would probably drop that as redundant. Of course you would be waiting for the token to complete... what else? And, I usually do a non-blocking ``try_wait()`` to complete the wait functions:
```
class token {
  void wait();
  bool try_wait();
  bool wait_for(std::chrono::duration d);
  bool wait_until(std::chrono::time_point tp);
};
```

But as for setting a timeout value for a class/operation, then, no, I don't use `_for` or `_until`. The timeout is always a duration - setting a generic timeout to a fixed point in time doesn't seem to make sense. And using `_for` indicates something immediate  - not setting a value that will be used later.
