### ISSUE TITLE
Authentication parameters empty when using long password and/or username in connOpts

### ISSUE THREAD

**Issue by tomasbol** [eclipse/paho.mqtt.cpp#79]
Hi,

I noticed a problem when using a long password or username in the connOpts or the async_client.
The use of long strings in the `connOpts.set_user_name()` and `connOpts.set_password`-methods has as result that the User Name and Password-field of the MQTT Connect Command are empty (noticed this in Wireshark).

The problem seems to happen when the library makes a copy of the connect_options in the following method: `itoken_ptr async_client::connect(connect_options opts)`. I looks like the copy of the connect_options goes out of scope and as a result the destructor of the connect_options class removes the username and password string. I don't know why this only happens for long passwords and usernames.

As a workaround for my project, I used a pointer to the connect_options in all the connect() methods instead, to avoid the copying of the connect_options.

For example:
`
itoken_ptr async_client::connect(connect_options* opts)
{
	itoken_ptr tok = std::make_shared<token>(*this);
	add_token(tok);

	opts->set_token(std::dynamic_pointer_cast<token>(tok));

	int rc = MQTTAsync_connect(cli_, &opts->opts_);

	if (rc != MQTTASYNC_SUCCESS) {
		remove_token(tok);
		throw exception(rc);
	}

	return tok;
}
`

Kind Regards,
Tomas

**Comment by fpagliughi** [comment]
Thanks for pointing this out. First I want to make sure that each of the "options" classes (connect, will, ssl, etc) follow proper copy and move semantics, so I will look for the underlying bug which caused the problem. Can you tell me what you mean by "long" string?

And note that next commit to the develop branch will likely convert the password to binary (see #57), so the underlying code is changing rapidly.

In the long run, I intend to optimize the internal behavior of the classes to reduce the copying of large payloads. I'll likely move to a const reference type of class internally so you could make cheap copies of messages and options without copying the payloads... unless, of course you wanted to clone or change them, in which case it would copy-on-write.

But, in the meantime, I will look to add a connect() which takes a pointer.

Of course, if you don't need the options after the connect, you can just move them into the client:
```
connect_options opts(...);
cli.connect(std::move(opts));
```

**Comment by tomasbol** [comment]
The length of the string that I used was 58 characters. When I used shorter strings, the problem did not seem to occur. 

Indeed, a move instruction could also be a solution or workaround for this problem.

**Comment by fpagliughi** [comment]
Oh, wow, That's not very long. I will make a test case.

**Comment by fpagliughi** [comment]
From the beginning, I was resisting using a pointer to the connect_options because connect() modifies the object by updating the context token. It seemed like an undesired side effect.

I'm thinking of an update that would affect this, in PR #90. It would replace the string-type containers for the various buffers (payloads, username, password, etc) with reference types. So, effectively, the connect_option'ss would contain (smart) pointers to the user name and password, and copying the options would be relatively fast and independent of the size of the username and password.

Please have a look and comment.

**Comment by fpagliughi** [comment]
This seems to have been fixed in a recent update.
