### ISSUE TITLE
Header mqtt/types.h not installed

### ISSUE THREAD

**Issue by gitplcc** [eclipse/paho.mqtt.cpp#84]
Header mqtt/types.h referenced by:

- mqtt/connect_options.h
- mqtt/ipersistable.h
- mqtt/message.h
- mqtt/token.h
- mqtt/will_options.h

not installed  with `make install`.

**Comment by fpagliughi** [comment]
Fixed with 8d46466d2c941e741db1f11833c44c3fd44b4736
