### ISSUE TITLE
Fix installation on Cygwin (missing DLL)

### ISSUE THREAD

**Issue by gitplcc** [eclipse/paho.mqtt.cpp#86]
Linkage library <prefix>/lib/libpaho-mqttpp3.dll.a is installed, but <prefix>/bin/libpaho-mqttpp3.dll is not.

**Comment by guilhermeferreira** [comment]
@gitplcc Using CMake, Autotools or GNU Make?

**Comment by gitplcc** [comment]
Using CMake. Not checked for other build tools.
