### ISSUE TITLE
Sample programs not working on RPi

### ISSUE THREAD

**Issue by priema** [eclipse/paho.mqtt.cpp#99]
I have a problem with the sample programs:

```
pi@raspberrypi:~/paho.mqtt.cpp/src/samples $ sudo ./async_publish 
Initializing for server 'tcp://192.168.1.34:1883'...
  ...OK

Connecting...
pi@raspberrypi:~
```

After 'connecting'  the program ends.

What I noticed is that the program creates a folder:
`pi@raspberrypi:~/paho.mqtt.cpp/src/samples/AsyncPublisher-192.168.1.34-1883 $ `

Same with async_subscribe program.

What can I do to fix this behaviour?

**Comment by fpagliughi** [comment]
The code bases for the Paho C and C++ libraries are changing rapidly in preparation of the upcoming release, and it seems that mismatched versions can cause some problems, including a mismatched SSL vs non-SSL version.

Try the very latest develop branches for both libraries. I tried it with SSL enabled this morning, and that worked for me on an RPi.

**Comment by fpagliughi** [comment]
This appears to be working with the latest update.
